using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Qms.Application.Security;
using Qms.Application.WorkItems;
using Qms.Contracts.Common;
using Qms.Contracts.WorkItems;
using Qms.Domain.AuditTrail;
using Qms.Domain.ElectronicSignatures;
using Qms.Domain.Notifications;
using Qms.Domain.QualityRecords;
using Qms.Domain.WorkItems;
using Qms.Domain.Workflows;
using Qms.Infrastructure.Identity;
using Qms.Infrastructure.Persistence;

namespace Qms.Infrastructure.WorkItems;

public sealed class WorkItemService(QmsDbContext db, TimeProvider time, ICurrentUser user, UserManager<ApplicationUser> users) : IWorkItemService
{
    public async Task<WorkItemOptionsResponse> GetOptionsAsync(CancellationToken ct)
    {
        var people = await (from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.IsActive orderby u.DisplayName select new WorkItemIdentityOption(u.Id,u.DisplayName,d == null ? null : d.Name)).ToListAsync(ct);
        var defs = await db.WorkItemLookupDefinitions.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Name).ToListAsync(ct);
        IReadOnlyList<WorkItemCodeOption> Of(string c)=>defs.Where(x=>x.Category==c).Select(x=>new WorkItemCodeOption(x.Code,x.Name)).ToList();
        return new(people,Of("Category"),Of("Priority"));
    }
    public async Task<IReadOnlyList<WorkItemLookupDefinitionResponse>> ListLookupsAsync(CancellationToken ct)=>await db.WorkItemLookupDefinitions.AsNoTracking().OrderBy(x=>x.Category).ThenBy(x=>x.SortOrder).Select(x=>new WorkItemLookupDefinitionResponse(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive)).ToListAsync(ct);
    public async Task<WorkItemLookupDefinitionResponse> CreateLookupAsync(CreateWorkItemLookupDefinitionRequest r,CancellationToken ct){EnsureCategory(r.Category);if(await db.WorkItemLookupDefinitions.AnyAsync(x=>x.Category==r.Category.Trim()&&x.Code==r.Code.Trim(),ct))throw new InvalidOperationException("Aynı M.10 lookup kodu zaten mevcut.");var now=time.GetUtcNow();var x=WorkItemLookupDefinition.Create(r.Category,r.Code,r.Name,r.SortOrder,now);db.Add(x);db.Add(Event("WorkItemLookupDefinition",x.Id,1,"WorkItemLookupCreated",now,new{x.Category,x.Code,x.Name}));await db.SaveChangesAsync(ct);return new(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive);}
    public async Task<WorkItemLookupDefinitionResponse?> UpdateLookupAsync(Guid id,UpdateWorkItemLookupDefinitionRequest r,CancellationToken ct){var x=await db.WorkItemLookupDefinitions.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return null;var now=time.GetUtcNow();x.Update(r.Name,r.SortOrder,r.IsActive,now);db.Add(Event("WorkItemLookupDefinition",x.Id,1,"WorkItemLookupUpdated",now,new{x.Category,x.Code,x.Name,x.IsActive}));await db.SaveChangesAsync(ct);return new(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive);}
    public async Task<PagedResponse<WorkItemListItemResponse>> SearchAsync(WorkItemSearchRequest r,CancellationToken ct)
    {
        if(r.Page<1||r.PageSize is not(10 or 25 or 50 or 100))throw new ArgumentException("Sayfa bilgisi geçersizdir.");
        var q=from w in db.WorkItems.AsNoTracking() join qr in db.QualityRecords.AsNoTracking() on w.QualityRecordId equals qr.Id select new Row{Item=w,Number=qr.RecordNumber};
        foreach(var f in r.Filters??[]) {var v=f.Value?.Trim()??"";q=f.Field.Trim().ToLowerInvariant() switch{"recordnumber"=>q.Where(x=>x.Number.ToLower().Contains(v.ToLower())),"title"=>q.Where(x=>x.Item.Title.ToLower().Contains(v.ToLower())),"owner"=>q.Where(x=>x.Item.Owner.ToLower().Contains(v.ToLower())),"category"=>q.Where(x=>x.Item.Category==v),"priority"=>q.Where(x=>x.Item.Priority==v),"status"=>Enum.TryParse<WorkItemStatus>(v,true,out var s)?q.Where(x=>x.Item.Status==s):throw new ArgumentException("Durum geçersizdir."),_=>throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}")};}
        var total=await q.LongCountAsync(ct);var desc=r.SortDirection.Equals("desc",StringComparison.OrdinalIgnoreCase);q=r.SortBy.ToLowerInvariant() switch{"recordnumber"=>desc?q.OrderByDescending(x=>x.Number):q.OrderBy(x=>x.Number),"duedateutc"=>desc?q.OrderByDescending(x=>x.Item.DueAtUtc):q.OrderBy(x=>x.Item.DueAtUtc),"status"=>desc?q.OrderByDescending(x=>x.Item.Status):q.OrderBy(x=>x.Item.Status),_=>desc?q.OrderByDescending(x=>x.Item.CreatedAtUtc):q.OrderBy(x=>x.Item.CreatedAtUtc)};
        var now=time.GetUtcNow();var items=await q.Skip((r.Page-1)*r.PageSize).Take(r.PageSize).Select(x=>new WorkItemListItemResponse(x.Item.Id,x.Number,x.Item.Title,x.Item.Category,x.Item.Priority,x.Item.Owner,x.Item.DueAtUtc,x.Item.DueAtUtc<now&&x.Item.Status!=WorkItemStatus.Completed&&x.Item.Status!=WorkItemStatus.Cancelled,x.Item.Status.ToString(),x.Item.CreatedAtUtc,x.Item.Version)).ToListAsync(ct);return new(items,r.Page,r.PageSize,total,total==0?0:(int)Math.Ceiling(total/(double)r.PageSize));
    }
    public async Task<WorkItemDetailsResponse?> GetDetailsAsync(Guid id,CancellationToken ct)
    {
        var w=await db.WorkItems.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(w is null)return null;var qr=await db.QualityRecords.AsNoTracking().SingleAsync(x=>x.Id==w.QualityRecordId,ct);var ev=await db.AuditEvents.AsNoTracking().Where(x=>x.AggregateType=="WorkItem"&&x.AggregateId==id).OrderByDescending(x=>x.OccurredAtUtc).ToListAsync(ct);var sig=await db.ElectronicSignatures.AsNoTracking().Where(x=>x.QualityRecordId==w.QualityRecordId).OrderByDescending(x=>x.SignedAtUtc).ToListAsync(ct);
        var transitions=new List<WorkItemTransitionResponse>();foreach(var t in Transitions(w.Status)){var allowed=t.Code switch{"assign"=>qr.CreatedByUserId==user.Id||user.IsInRole(QmsRoles.Administrator)||user.IsInRole(QmsRoles.QualityAssurance),"start" or "submit"=>await CanAct(id,WorkflowTaskRoles.WorkItemOwner,ct),"verify"=>await CanAct(id,WorkflowTaskRoles.WorkItemVerifier,ct),_=>user.IsInRole(QmsRoles.Administrator)||user.IsInRole(QmsRoles.QualityAssurance)};if(allowed)transitions.Add(t);}
        var record=new WorkItemRecordResponse(w.Id,w.QualityRecordId,qr.RecordNumber,w.SourceModule,w.SourceRecordId,w.SourceRecordNumber,w.Category,w.Priority,w.Title,w.Description,w.OwnerUserId,w.Owner,w.OwnerDepartmentId,w.OwnerDepartment,w.VerifierUserId,w.Verifier,w.DueAtUtc,w.DueAtUtc<time.GetUtcNow()&&w.Status is not(WorkItemStatus.Completed or WorkItemStatus.Cancelled),w.CompletionEvidence,w.VerificationNote,w.Status.ToString(),w.CreatedAtUtc,w.UpdatedAtUtc,w.StartedAtUtc,w.SubmittedAtUtc,w.CompletedAtUtc,w.CancelledAtUtc,w.Version);
        return new(record,ev.Select(x=>new WorkItemEventResponse(x.Id,x.AggregateVersion,x.EventType,x.ActorDisplayNameSnapshot,x.OccurredAtUtc,x.Reason,x.Payload.RootElement.Clone())).ToList(),sig.Select(x=>new WorkItemSignatureResponse(x.Id,x.RecordVersion,x.SignerUserId,x.SignerDisplayNameSnapshot,x.Meaning,x.SignedAtUtc,x.ContentHash,x.Comment)).ToList(),transitions);
    }
    public async Task<WorkItemDetailsResponse> CreateAsync(CreateWorkItemRequest r,CancellationToken ct)
    {
        if(!user.DepartmentId.HasValue)throw new InvalidOperationException("İş kaydı oluşturan kullanıcının etkin bir bölüm ataması olmalıdır.");await Lookup("Category",r.Category,"Kategori",ct);await Lookup("Priority",r.Priority,"Öncelik",ct);var owner=await Resolve(r.OwnerUserId,"İş sorumlusu",ct);var verifier=await Resolve(r.VerifierUserId,"Doğrulayıcı",ct);if(owner.Id==verifier.Id)throw new InvalidOperationException("Görev ayrılığı gereği iş sorumlusu ve doğrulayıcı aynı kişi olamaz.");if(r.SourceRecordId.HasValue&&!await db.QualityRecords.AnyAsync(x=>x.Id==r.SourceRecordId,ct))throw new ArgumentException("Kaynak kalite kaydı bulunamadı.");
        var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);var number=$"IS-{now.Year}-{await Next("work-item",now.Year,tx,ct):000000}";var qr=QualityRecord.Create(number,"M.10",user.Id,user.DepartmentId.Value,now,JsonSerializer.SerializeToDocument(new{r.SourceModule,r.SourceRecordId,r.SourceRecordNumber}));qr.Submit(now);var w=WorkItem.Create(qr.Id,r.SourceModule,r.SourceRecordId,r.SourceRecordNumber,r.Category,r.Priority,r.Title,r.Description,owner.Id,owner.Name,owner.DepartmentId,owner.Department,verifier.Id,verifier.Name,r.DueAtUtc.ToUniversalTime(),now);db.Add(qr);db.Add(w);db.Add(Audit(w,"WorkItemCreated",now,new{number,r.Category,r.Priority,ownerUserId=owner.Id,verifierUserId=verifier.Id}));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return (await GetDetailsAsync(w.Id,ct))!;
    }
    public async Task<WorkItemDetailsResponse?> TransitionAsync(Guid id,TransitionWorkItemRequest r,CancellationToken ct)
    {
        var w=await db.WorkItems.SingleOrDefaultAsync(x=>x.Id==id,ct);if(w is null)return null;var qr=await db.QualityRecords.SingleAsync(x=>x.Id==w.QualityRecordId,ct);var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);string type;
        switch(r.Transition.Trim().ToLowerInvariant()){
            case "assign": if(qr.CreatedByUserId!=user.Id&&!user.IsInRole(QmsRoles.Administrator)&&!user.IsInRole(QmsRoles.QualityAssurance))throw new QmsForbiddenException("Kaydı yalnızca oluşturan kullanıcı veya kalite yöneticisi atayabilir.");w.Assign(r.ExpectedVersion,now);await Assign(w.Id,WorkflowTaskRoles.WorkItemOwner,w.OwnerUserId,now,w.DueAtUtc,ct);type="WorkItemAssigned";break;
            case "start":await EnsureActor(id,WorkflowTaskRoles.WorkItemOwner,ct);w.Start(r.ExpectedVersion,now);type="WorkItemStarted";break;
            case "submit":await EnsureActor(id,WorkflowTaskRoles.WorkItemOwner,ct);w.Submit(r.ExpectedVersion,r.Evidence??"",now);await Complete(id,WorkflowTaskRoles.WorkItemOwner,now,ct);await Assign(w.Id,WorkflowTaskRoles.WorkItemVerifier,w.VerifierUserId,now,w.DueAtUtc,ct);type="WorkItemSubmitted";break;
            case "verify":await EnsureActor(id,WorkflowTaskRoles.WorkItemVerifier,ct);await Signature(r,ct);w.Verify(r.ExpectedVersion,r.Approved,r.Note??"",now);db.Add(ElectronicSignature.Create(w.QualityRecordId,w.Version,user.Id,user.DisplayName,r.Approved?"İş tamamlama ve kanıt doğrulama onayı":"İş kanıtı ret ve yeniden çalışma kararı",now,Hash(w.Id,w.Version,r.Approved?"approve":"reject",r.Note),r.Note));await Complete(id,WorkflowTaskRoles.WorkItemVerifier,now,ct);if(r.Approved){qr.Close(now,false);await CompleteAll(id,now,ct);}else await Assign(w.Id,WorkflowTaskRoles.WorkItemOwner,w.OwnerUserId,now,w.DueAtUtc,ct);type=r.Approved?"WorkItemVerified":"WorkItemRejected";break;
            case "cancel":if(!user.IsInRole(QmsRoles.Administrator)&&!user.IsInRole(QmsRoles.QualityAssurance))throw new QmsForbiddenException("İşi yalnızca kalite yöneticisi iptal edebilir.");await Signature(r,ct);w.Cancel(r.ExpectedVersion,r.Note??"",now);db.Add(ElectronicSignature.Create(w.QualityRecordId,w.Version,user.Id,user.DisplayName,"İş kaydı iptal onayı",now,Hash(w.Id,w.Version,"cancel",r.Note),r.Note));await CompleteAll(id,now,ct);type="WorkItemCancelled";break;
            default:throw new ArgumentException("İş geçişi geçersizdir.");}
        db.Add(Audit(w,type,now,new{r.Transition,r.Approved},r.Note??r.Evidence));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);
    }
    private static IReadOnlyList<WorkItemTransitionResponse> Transitions(WorkItemStatus s)=>s switch{WorkItemStatus.Draft=>[new("assign","Sorumluya ata")],WorkItemStatus.Assigned=>[new("start","Çalışmayı başlat"),new("cancel","İşi iptal et",true)],WorkItemStatus.InProgress=>[new("submit","Kanıtla doğrulamaya gönder"),new("cancel","İşi iptal et",true)],WorkItemStatus.PendingVerification=>[new("verify","Kanıtı değerlendir",true),new("cancel","İşi iptal et",true)],_=>[]};
    private async Task Assign(Guid id,string role,Guid uid,DateTimeOffset now,DateTimeOffset? due,CancellationToken ct){if(await db.WorkflowTaskAssignments.AnyAsync(x=>x.AggregateType=="WorkItem"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active,ct))return;var p=await Resolve(uid,"Görev kullanıcısı",ct);db.Add(WorkflowTaskAssignment.Create("WorkItem",id,role,p.Id,p.DepartmentId,now,due,assignedUserNameSnapshot:p.Name,assignedDepartmentNameSnapshot:p.Department));db.Add(UserNotification.Create(p.Id,"M.10","Yeni iş takip görevi",role==WorkflowTaskRoles.WorkItemOwner?"Tamamlanması gereken bir iş size atandı.":"Doğrulanması gereken bir iş size atandı.",$"/modules/m10?open={id}",now));}
    private async Task Complete(Guid id,string role,DateTimeOffset now,CancellationToken ct){foreach(var t in await db.WorkflowTaskAssignments.Where(x=>x.AggregateType=="WorkItem"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active).ToListAsync(ct))t.Complete(now);}
    private async Task CompleteAll(Guid id,DateTimeOffset now,CancellationToken ct){foreach(var t in await db.WorkflowTaskAssignments.Where(x=>x.AggregateType=="WorkItem"&&x.AggregateId==id&&x.Status==WorkflowTaskStatus.Active).ToListAsync(ct))t.Complete(now);}
    private async Task EnsureActor(Guid id,string role,CancellationToken ct){if(!await CanAct(id,role,ct))throw new QmsForbiddenException("Bu iş görevi size veya etkin bir delegasyonla size atanmamış.");}
    private async Task<bool> CanAct(Guid id,string role,CancellationToken ct){var owners=await db.WorkflowTaskAssignments.AsNoTracking().Where(x=>x.AggregateType=="WorkItem"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active).Select(x=>x.AssignedUserId).ToListAsync(ct);if(owners.Contains(user.Id))return true;var now=time.GetUtcNow();return owners.Count>0&&await db.Delegations.AsNoTracking().AnyAsync(x=>owners.Contains(x.DelegatorUserId)&&x.DelegateUserId==user.Id&&x.RevokedAtUtc==null&&x.StartsAtUtc<=now&&x.EndsAtUtc>=now&&(x.Scope=="M.10"||x.Scope=="ALL"),ct);}
    private async Task Signature(TransitionWorkItemRequest r,CancellationToken ct){if(!r.SignatureMeaningAccepted||string.IsNullOrWhiteSpace(r.SignaturePassword))throw new ArgumentException("Elektronik imza için parola ve anlam kabulü zorunludur.");var a=await users.FindByIdAsync(user.Id.ToString())??throw new QmsForbiddenException("İmzalayan kullanıcı bulunamadı.");if(!a.IsActive||!await users.CheckPasswordAsync(a,r.SignaturePassword))throw new QmsForbiddenException("Elektronik imza parolası geçersizdir.");}
    private async Task Lookup(string c,string code,string field,CancellationToken ct){if(!await db.WorkItemLookupDefinitions.AsNoTracking().AnyAsync(x=>x.Category==c&&x.Code==code.Trim()&&x.IsActive,ct))throw new ArgumentException($"{field} etkin M.10 lookup kayıtlarından seçilmelidir.");}
    private async Task<(Guid Id,string Name,Guid? DepartmentId,string? Department)> Resolve(Guid id,string field,CancellationToken ct){var p=await(from u in db.Users.AsNoTracking()join d in db.Departments.AsNoTracking()on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty()where u.Id==id&&u.IsActive select new{u.Id,u.DisplayName,u.DepartmentId,Department=d==null?null:d.Name}).SingleOrDefaultAsync(ct);return p is null?throw new ArgumentException($"{field} etkin sistem kullanıcılarından seçilmelidir."):(p.Id,p.DisplayName,p.DepartmentId,p.Department);}
    private static void EnsureCategory(string c){if(c.Trim() is not("Category" or "Priority"))throw new ArgumentException("M.10 lookup kategorisi Category veya Priority olmalıdır.");}
    private AuditEvent Audit(WorkItem w,string type,DateTimeOffset now,object payload,string? reason=null)=>Event("WorkItem",w.Id,w.Version,type,now,payload,reason);
    private AuditEvent Event(string aggregate,Guid id,long version,string type,DateTimeOffset now,object payload,string? reason=null)=>AuditEvent.Create(aggregate,id,version,type,user.Id,user.DisplayName,now,Guid.CreateVersion7().ToString(),JsonSerializer.SerializeToDocument(payload),reason);
    private static string Hash(Guid id,long v,string op,string? note)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{id:N}|{v}|{op}|{note?.Trim()}"))).ToLowerInvariant();
    private async Task<long> Next(string type,int year,IDbContextTransaction tx,CancellationToken ct){var c=db.Database.GetDbConnection();if(c.State!=ConnectionState.Open)await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.Transaction=tx.GetDbTransaction();cmd.CommandText="INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@type,@year,1) ON CONFLICT (\"RecordType\",\"CalendarYear\") DO UPDATE SET \"LastValue\"=core.record_number_sequence.\"LastValue\"+1 RETURNING \"LastValue\";";Add(cmd,"type",type);Add(cmd,"year",year);return Convert.ToInt64(await cmd.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);}
    private static void Add(DbCommand c,string n,object v){var p=c.CreateParameter();p.ParameterName=n;p.Value=v;c.Parameters.Add(p);}
    private sealed class Row{public required WorkItem Item{get;init;}public required string Number{get;init;}}
}
