using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using PdfSharp.Fonts;
using Qms.Application.WorkItems;
using Qms.Contracts.WorkItems;

namespace Qms.Infrastructure.WorkItems;
public sealed class WorkItemFinalReportService(IConfiguration configuration):IWorkItemFinalReportService
{
    private const string Font="QmsDejaVuSans";private static readonly Lock FontLock=new();
    public async Task<WorkItemFinalReportFile> EnsureGeneratedAsync(WorkItemDetailsResponse d,CancellationToken ct){if(d.Record.Status!="Completed")throw new InvalidOperationException("Nihai PDF yalnız doğrulanarak tamamlanmış işler için üretilebilir.");var root=configuration["FileStorage:RootPath"]??Path.Combine(AppContext.BaseDirectory,"qms-files");var dir=Path.Combine(root,"work-items",d.Record.Id.ToString("N"));Directory.CreateDirectory(dir);var name=$"{d.Record.RecordNumber}-nihai-is-kaydi-v{d.Record.Version}.pdf";var path=Path.Combine(dir,name);var hp=path+".sha256";var reportIsNew = !File.Exists(path); if (reportIsNew){EnsureFont();var bytes=Build(d,Snapshot(d));await File.WriteAllBytesAsync(path,bytes,ct);await File.WriteAllTextAsync(hp,Convert.ToHexStringLower(SHA256.HashData(bytes)),Encoding.ASCII,ct);}var content=await File.ReadAllBytesAsync(path,ct);var actual=Convert.ToHexStringLower(SHA256.HashData(content));var expected=(await File.ReadAllTextAsync(hp,ct)).Trim();if(!CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(actual),Encoding.ASCII.GetBytes(expected)))throw new InvalidOperationException("Nihai M.10 PDF bütünlük doğrulamasını geçemedi.");await Qms.Infrastructure.Integrity.FinalReportIntegrity.SealNewOrVerifyAsync(configuration, path, actual, reportIsNew); return new(content,name,actual);}
    private static byte[] Build(WorkItemDetailsResponse d,string snapshot){var r=d.Record;var doc=new Document{Info={Title=$"{r.RecordNumber} Nihai İş Kaydı",Author="QMS"}};doc.Styles["Normal"]!.Font.Name=Font;doc.Styles["Normal"]!.Font.Size=9;var s=doc.AddSection();s.PageSetup.PageFormat=PageFormat.A4;s.PageSetup.TopMargin=Unit.FromCentimeter(1.4);s.PageSetup.BottomMargin=Unit.FromCentimeter(1.6);s.PageSetup.LeftMargin=s.PageSetup.RightMargin=Unit.FromCentimeter(1.5);Brand(s,"QMS  |  M.10 İŞ TAKİP VE AKSİYON");var title=s.AddParagraph(r.Title);title.Format.Font.Size=19;title.Format.Font.Bold=true;title.Format.Font.Color=Color.Parse("#0F5F61");s.AddParagraph($"{r.RecordNumber} | Kayıt sürümü {r.Version} | NİHAİ - TAMAMLANDI");Heading(s,"1. İş tanımı ve izlenebilirlik");Grid(s,["Kategori",r.Category,"Öncelik",r.Priority,"Kaynak",r.SourceRecordNumber is null?"Bağımsız iş kaydı":$"{r.SourceModule} · {r.SourceRecordNumber}","Hedef",F(r.DueAtUtc),"Sorumlu",$"{r.Owner} · {r.OwnerDepartment??"Bölüm yok"}","Doğrulayıcı",r.Verifier]);Block(s,"İş tanımı / kabul kriteri",r.Description);Heading(s,"2. Tamamlama ve bağımsız doğrulama");Block(s,"Tamamlama kanıtı",r.CompletionEvidence??"-");Block(s,"Doğrulama notu",r.VerificationNote??"-");var sig=Table(s,["E-imza anlamı","İmzalayan","Tarih / sürüm","İçerik hash"]);foreach(var x in d.Signatures)Row(sig,x.Meaning,x.Signer,$"{F(x.SignedAtUtc)} / v{x.RecordVersion}",x.ContentHash[..Math.Min(16,x.ContentHash.Length)]+"...");Heading(s,"3. Kontrollü denetim izi");var trail=Table(s,["Sürüm / olay","İşlemi yapan","Tarih","Gerekçe"]);foreach(var x in d.AuditTrail.OrderBy(x=>x.Version))Row(trail,$"v{x.Version} / {x.EventType}",x.Actor,F(x.OccurredAtUtc),x.Reason??"-");var proof=s.AddParagraph();proof.Format.SpaceBefore=10;proof.Format.Shading.Color=Color.Parse("#EAF4F2");proof.AddFormattedText("KAYIT SNAPSHOT SHA-256\n",TextFormat.Bold);proof.AddText(snapshot);var footer=s.Footers.Primary.AddParagraph();footer.Format.Alignment=ParagraphAlignment.Center;footer.AddText($"{r.RecordNumber} | Sayfa ");footer.AddPageField();footer.AddText(" / ");footer.AddNumPagesField();var renderer=new PdfDocumentRenderer{Document=doc};renderer.RenderDocument();using var ms=new MemoryStream();renderer.PdfDocument.Save(ms,false);return ms.ToArray();}
    private static void Brand(Section s,string v){var p=s.AddParagraph(v);p.Format.Font.Bold=true;p.Format.Font.Color=Color.Parse("#0F7773");}private static void Heading(Section s,string v){var p=s.AddParagraph(v);p.Format.Font.Size=13;p.Format.Font.Bold=true;p.Format.Font.Color=Color.Parse("#173C46");p.Format.SpaceBefore=9;p.Format.SpaceAfter=4;}private static void Block(Section s,string l,string v){var p=s.AddParagraph();p.Format.SpaceAfter=5;p.AddFormattedText(l+"\n",TextFormat.Bold);p.AddText(v);}private static void Grid(Section s,string[]v){var t=Table(s,["Alan","Değer"]);for(var i=0;i<v.Length;i+=2)Row(t,v[i],v[i+1]);}private static Table Table(Section s,string[]h){var t=s.AddTable();t.Borders.Color=Color.Parse("#CBD9D7");t.Borders.Width=.5;foreach(var _ in h)t.AddColumn(Unit.FromCentimeter(17.4/h.Length));var r=t.AddRow();r.HeadingFormat=true;r.Shading.Color=Color.Parse("#EAF4F2");for(var i=0;i<h.Length;i++)Cell(r.Cells[i],h[i],true);return t;}private static void Row(Table t,params string[]v){var r=t.AddRow();for(var i=0;i<v.Length;i++)Cell(r.Cells[i],v[i]);}private static void Cell(Cell c,string v,bool bold=false){var p=c.AddParagraph(v);p.Format.Font.Bold=bold;p.Format.Font.Size=8;c.VerticalAlignment=VerticalAlignment.Center;}private static string Snapshot(WorkItemDetailsResponse d)=>Convert.ToHexStringLower(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(d)));private static string F(DateTimeOffset? v)=>v?.ToOffset(TimeSpan.FromHours(3)).ToString("dd.MM.yyyy HH:mm 'TRT'")??"-";private static void EnsureFont(){if(GlobalFontSettings.FontResolver is not null)return;lock(FontLock)GlobalFontSettings.FontResolver??=new Resolver();}private sealed class Resolver:IFontResolver{private static readonly string Regular=Path.Combine("/usr/share/fonts/truetype/dejavu","DejaVuSans.ttf");private static readonly string Bold=Path.Combine("/usr/share/fonts/truetype/dejavu","DejaVuSans-Bold.ttf");public byte[]GetFont(string face)=>File.ReadAllBytes(face.EndsWith("Bold",StringComparison.Ordinal)?Bold:Regular);public FontResolverInfo ResolveTypeface(string family,bool bold,bool italic)=>new(bold?"QmsBold":"QmsRegular",false,false);}
}
