using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Qms.Application.Complaints;
using Qms.Application.Security;
using Qms.Contracts.Common;
using Qms.Contracts.Complaints;
using Qms.Domain.AuditTrail;
using Qms.Domain.Capas;
using Qms.Domain.Complaints;
using Qms.Domain.Deviations;
using Qms.Domain.ElectronicSignatures;
using Qms.Domain.Notifications;
using Qms.Domain.QualityRecords;
using Qms.Domain.Workflows;
using Qms.Infrastructure.Persistence;
using Qms.Infrastructure.Identity;

namespace Qms.Infrastructure.Complaints;

public sealed class ComplaintService(QmsDbContext db, TimeProvider time, ICurrentUser user, UserManager<ApplicationUser> userManager) : IComplaintService
{
    private static readonly HashSet<string> LookupCategories = ["Channel", "Country", "ComplaintType"];

    public async Task<PagedResponse<ComplaintListItemResponse>> SearchAsync(ComplaintSearchRequest request, CancellationToken ct)
    {
        if (request.Page < 1 || request.PageSize is not (10 or 25 or 50 or 100)) throw new ArgumentException("Sayfa ve sayfa boyutu geçersizdir.");
        var query = from complaint in db.Complaints.AsNoTracking() join record in db.QualityRecords.AsNoTracking() on complaint.QualityRecordId equals record.Id select new ComplaintRow { Complaint = complaint, RecordNumber = record.RecordNumber };
        foreach (var filter in request.Filters ?? []) query = ApplyFilter(query, filter);
        var total = await query.LongCountAsync(ct); query = ApplySort(query, request.SortBy, request.SortDirection);
        var items = await query.Skip((request.Page - 1) * request.PageSize).Take(request.PageSize).Select(x => new ComplaintListItemResponse(x.Complaint.Id, x.RecordNumber, x.Complaint.CustomerName, x.Complaint.Country, x.Complaint.Product, x.Complaint.BatchNumber, x.Complaint.ComplaintType, x.Complaint.Severity.ToString(), x.Complaint.Status.ToString(), x.Complaint.Owner, x.Complaint.PreliminaryResponseDueAtUtc, x.Complaint.FinalResponseDueAtUtc, x.Complaint.SuspectedAdverseEvent, x.Complaint.TrendFlagged, x.Complaint.SimilarComplaintCount, x.Complaint.CreatedAtUtc, x.Complaint.Version)).ToListAsync(ct);
        return new(items, request.Page, request.PageSize, total, total == 0 ? 0 : (int)Math.Ceiling(total / (double)request.PageSize));
    }

    public async Task<ComplaintDetailsResponse?> GetDetailsAsync(Guid id, CancellationToken ct)
    {
        var c = await db.Complaints.AsNoTracking().Include(x => x.Investigations).Include(x => x.Responses).SingleOrDefaultAsync(x => x.Id == id, ct); if (c is null) return null;
        var recordNumber = await db.QualityRecords.Where(x => x.Id == c.QualityRecordId).Select(x => x.RecordNumber).SingleAsync(ct);
        var ids = new[] { c.LinkedDeviationId, c.LinkedCapaId, c.PharmacovigilanceRecordId }.Where(x => x.HasValue).Select(x => x!.Value).ToArray();
        var linked = new Dictionary<Guid, string>();
        if (c.LinkedDeviationId is Guid deviationId) { var qid = await db.Deviations.Where(x => x.Id == deviationId).Select(x => x.QualityRecordId).SingleOrDefaultAsync(ct); if (qid != Guid.Empty) linked[deviationId] = await db.QualityRecords.Where(x => x.Id == qid).Select(x => x.RecordNumber).SingleAsync(ct); }
        if (c.LinkedCapaId is Guid capaId) { var qid = await db.Capas.Where(x => x.Id == capaId).Select(x => x.QualityRecordId).SingleOrDefaultAsync(ct); if (qid != Guid.Empty) linked[capaId] = await db.QualityRecords.Where(x => x.Id == qid).Select(x => x.RecordNumber).SingleAsync(ct); }
        if (c.PharmacovigilanceRecordId is Guid pvId) linked[pvId] = await db.QualityRecords.Where(x => x.Id == pvId).Select(x => x.RecordNumber).SingleAsync(ct);
        var auditEvents = await db.AuditEvents.AsNoTracking().Where(x => x.AggregateType == "Complaint" && x.AggregateId == id).OrderByDescending(x => x.OccurredAtUtc).ToListAsync(ct);
        var audit = auditEvents.Select(x => new ComplaintAuditEventResponse(x.Id, x.AggregateVersion, x.EventType, x.ActorDisplayNameSnapshot, x.OccurredAtUtc, x.Reason, x.Payload.RootElement.Clone())).ToList();
        var record = new ComplaintRecordResponse(c.Id, c.QualityRecordId, recordNumber, c.Channel, c.CustomerName, c.Country, c.Product, c.BatchNumber, c.EventAtUtc, c.ReceivedAtUtc, c.ComplaintType, c.Description, c.Severity.ToString(), c.HasHealthImpact, c.SuspectedAdverseEvent, c.SampleExpected, c.ReturnExpected, c.AttachmentSummary, c.OwnerUserId, c.Owner, c.PreliminaryResponseDueAtUtc, c.FinalResponseDueAtUtc, c.SimilarComplaintCount, c.TrendFlagged, c.LinkedDeviationId, c.LinkedDeviationId is Guid d ? linked.GetValueOrDefault(d) : null, c.LinkedCapaId, c.LinkedCapaId is Guid ca ? linked.GetValueOrDefault(ca) : null, c.PharmacovigilanceRecordId, c.PharmacovigilanceRecordId is Guid p ? linked.GetValueOrDefault(p) : null, c.PharmacovigilanceStatus, c.ImpactAssessment, c.ConfirmedRootCause, c.CapaRequired, c.ClosureNote, c.Status.ToString(), c.CreatedAtUtc, c.UpdatedAtUtc, c.ClosedAtUtc, c.Version);
        var signatures = await db.ElectronicSignatures.AsNoTracking().Where(x => x.QualityRecordId == c.QualityRecordId).OrderBy(x => x.SignedAtUtc).Select(x => new ComplaintSignatureResponse(x.Id, x.RecordVersion, x.SignerUserId, x.SignerDisplayNameSnapshot, x.Meaning, x.SignedAtUtc, x.ContentHash, x.Comment)).ToListAsync(ct);
        var roles = await CurrentTaskRoles(id, ct);
        return new(record, c.Investigations.OrderBy(x => x.Department).Select(x => new ComplaintInvestigationResponse(x.Id, x.DepartmentId, x.Department, x.InvestigatorUserId, x.Investigator, x.Status.ToString(), x.Findings, x.RootCauseContribution, x.CompletedAtUtc)).ToList(), c.Responses.OrderByDescending(x => x.CreatedAtUtc).Select(x => new ComplaintResponseVersionResponse(x.Id, x.ResponseType.ToString(), x.VersionNumber, x.Content, x.Status.ToString(), x.PreparedByUserId, x.PreparedBy, x.ApprovedByUserId, x.ApprovedBy, x.CreatedAtUtc, x.ApprovedAtUtc)).ToList(), audit, signatures, Transitions(c.Status, roles), roles);
    }

    public async Task<ComplaintDetailsResponse> CreateAsync(CreateComplaintRequest request, CancellationToken ct)
    {
        if (!Enum.TryParse<ComplaintSeverity>(request.Severity, true, out var severity)) throw new ArgumentException("Şikâyet önem derecesi geçersizdir.");
        await EnsureLookup("Channel", request.Channel, ct); await EnsureLookup("Country", request.Country, ct); await EnsureLookup("ComplaintType", request.ComplaintType, ct);
        var owner = await ActiveUser(request.OwnerUserId, ct); if (!await IsComplaintCoordinator(owner.Id, ct)) throw new ArgumentException("Seçilen kayıt sahibi M.06 koordinasyon yetkisine sahip değil."); var investigations = await ResolveInvestigations(request.InvestigationDepartmentIds, request.OwnerUserId, ct);
        var now = time.GetUtcNow(); var received = request.ReceivedAtUtc.ToUniversalTime(); var similar = await db.Complaints.CountAsync(x => x.Product.ToLower() == request.Product.Trim().ToLower() && x.ComplaintType.ToLower() == request.ComplaintType.Trim().ToLower() && x.CreatedAtUtc >= now.AddMonths(-12), ct);
        await using var tx = await db.Database.BeginTransactionAsync(ct); var number = $"ŞK-{now.Year}-{await NextNumber("complaint", now.Year, tx, ct):000000}"; var creatorDepartmentId = user.DepartmentId ?? throw new InvalidOperationException("Şikâyet kaydı oluşturacak kullanıcının etkin organizasyon bölümü olmalıdır."); var qr = QualityRecord.Create(number, "complaint", user.Id, creatorDepartmentId, now);
        var complaint = Complaint.Create(qr.Id, request.Channel, request.CustomerName, request.Country, request.Product, request.BatchNumber, request.EventAtUtc.ToUniversalTime(), received, request.ComplaintType, request.Description, severity, request.HasHealthImpact, request.SuspectedAdverseEvent, request.SampleExpected, request.ReturnExpected, request.AttachmentSummary ?? "", owner.Id, owner.Name, request.PreliminaryResponseDueAtUtc.ToUniversalTime(), request.FinalResponseDueAtUtc.ToUniversalTime(), similar, investigations, now);
        db.QualityRecords.Add(qr); db.Complaints.Add(complaint); await Assign(complaint.Id, WorkflowTaskRoles.ComplaintCoordinator, owner.Id, now, complaint.PreliminaryResponseDueAtUtc, ct); db.AuditEvents.Add(Audit(complaint, "ComplaintCreated", now, new { number, complaint.Product, complaint.BatchNumber, complaint.Severity, complaint.SimilarComplaintCount, complaint.TrendFlagged, ownerUserId = owner.Id, investigationDepartmentIds = investigations.Select(x => x.DepartmentId) })); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return (await GetDetailsAsync(complaint.Id, ct))!;
    }

    public async Task<ComplaintDetailsResponse?> TransitionAsync(Guid id, TransitionComplaintRequest request, CancellationToken ct)
    {
        var c = await Load(id, ct); if (c is null) return null; var qr = await db.QualityRecords.SingleAsync(x => x.Id == c.QualityRecordId, ct); var now = time.GetUtcNow(); var transition = request.Transition.Trim().ToLowerInvariant(); var from = c.Status;
        var requiredRole = transition == "close" ? WorkflowTaskRoles.ResponseApprover : WorkflowTaskRoles.ComplaintCoordinator; await EnsureActor(id, requiredRole, ct); if (transition == "close") await EnsureSignature(request.SignaturePassword, request.SignatureMeaningAccepted, ct);
        await using var tx = await db.Database.BeginTransactionAsync(ct);
        switch (transition)
        {
            case "start-triage": c.StartTriage(request.ExpectedVersion, now); qr.Submit(now); break;
            case "complete-triage":
                EnsureManager(); Guid? deviationId = null; Guid? pvId = null;
                if (c.ComplaintType.Equals("ProductQuality", StringComparison.OrdinalIgnoreCase) && c.Severity != ComplaintSeverity.Minor) deviationId = await CreateDeviation(c, now, tx, ct);
                if (c.SuspectedAdverseEvent) pvId = await CreatePvReferral(c, now, tx, ct);
                c.CompleteTriage(request.ExpectedVersion, deviationId, pvId, now); foreach (var investigation in c.Investigations) await Assign(c.Id, $"ComplaintInvestigation:{investigation.Id}", investigation.InvestigatorUserId, now, c.FinalResponseDueAtUtc, ct); break;
            case "start-investigation": c.StartInvestigation(request.ExpectedVersion, now); break;
            case "finish-investigations": c.FinishInvestigations(request.ExpectedVersion, now); break;
            case "close": EnsureApprover(qr); c.Close(request.ExpectedVersion, request.Note ?? "", now); qr.Close(now, false); await CompleteAllTasks(id, now, ct); db.ElectronicSignatures.Add(ElectronicSignature.Create(qr.Id, c.Version, user.Id, user.DisplayName, "Müşteri şikâyeti nihai kapanış onayı", now, SignatureHash(c.Id, c.Version, transition, request.Note), request.Note)); break;
            default: throw new ArgumentException("Bilinmeyen şikâyet durum geçişi.");
        }
        db.AuditEvents.Add(Audit(c, "ComplaintStatusChanged", now, new { from = from.ToString(), to = c.Status.ToString(), transition }, request.Note)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct);
    }

    public async Task<ComplaintDetailsResponse?> AddResponseAsync(Guid id, AddComplaintResponseRequest request, CancellationToken ct) { await EnsureActor(id, WorkflowTaskRoles.ComplaintCoordinator, ct); return await Mutate(id, ct, (c, now) => { if (!Enum.TryParse<ComplaintResponseType>(request.ResponseType, true, out var type)) throw new ArgumentException("Yanıt türü geçersizdir."); var response = c.AddResponse(request.ExpectedVersion, type, request.Content, user.Id, user.DisplayName, now); db.ComplaintResponses.Add(response); return ("ComplaintResponseDrafted", (object)new { response.ResponseType, response.VersionNumber }, request.Content); }, async (c, now) => await AssignApprover(c, now, ct)); }
    public async Task<ComplaintDetailsResponse?> ApproveResponseAsync(Guid id, Guid responseId, ApproveComplaintResponseRequest request, CancellationToken ct) { await EnsureActor(id, WorkflowTaskRoles.ResponseApprover, ct); await EnsureSignature(request.SignaturePassword, request.SignatureMeaningAccepted, ct); return await Mutate(id, ct, (c, now) => { EnsureApprover(null); c.ApproveResponse(request.ExpectedVersion, responseId, user.Id, user.DisplayName, now); var response = c.Responses.Single(x => x.Id == responseId); db.ElectronicSignatures.Add(ElectronicSignature.Create(c.QualityRecordId, c.Version, user.Id, user.DisplayName, $"{response.ResponseType} müşteri yanıtı onayı", now, SignatureHash(c.Id, c.Version, "response-approval", response.Content), null)); return ("ComplaintResponseApproved", (object)new { response.ResponseType, response.VersionNumber }, (string?)null); }, async (c, now) => { if (c.Responses.Single(x => x.Id == responseId).ResponseType == ComplaintResponseType.Preliminary) await CompleteTasks(id, WorkflowTaskRoles.ResponseApprover, now, ct); }); }
    public async Task<ComplaintDetailsResponse?> CompleteInvestigationAsync(Guid id, Guid investigationId, CompleteComplaintInvestigationRequest request, CancellationToken ct) { var role = $"ComplaintInvestigation:{investigationId}"; await EnsureActor(id, role, ct); return await Mutate(id, ct, (c, now) => { EnsureInvestigator(); c.CompleteInvestigation(request.ExpectedVersion, investigationId, request.Findings, request.RootCauseContribution, now); return ("ComplaintInvestigationCompleted", (object)new { investigationId }, request.Findings); }, async (_, now) => await CompleteTasks(id, role, now, ct)); }
    public async Task<ComplaintDetailsResponse?> CompleteImpactAsync(Guid id, CompleteComplaintImpactRequest request, CancellationToken ct) { await EnsureActor(id, WorkflowTaskRoles.ComplaintCoordinator, ct); return await Mutate(id, ct, (c, now) => { EnsureManager(); c.CompleteImpact(request.ExpectedVersion, request.ImpactAssessment, request.ConfirmedRootCause, now); return ("ComplaintImpactAssessed", (object)new { request.ConfirmedRootCause }, request.ImpactAssessment); }); }

    public async Task<ComplaintDetailsResponse?> DecideCapaAsync(Guid id, DecideComplaintCapaRequest request, CancellationToken ct)
    {
        var c = await Load(id, ct); if (c is null) return null; await EnsureActor(id, WorkflowTaskRoles.ComplaintCoordinator, ct); EnsureManager(); var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); Guid? capaId = null;
        if (request.CapaRequired)
        {
            var capaOwner = await ActiveUser(request.OwnerUserId ?? c.OwnerUserId, ct); var departmentId = user.DepartmentId ?? throw new InvalidOperationException("DÖF açacak kullanıcının organizasyon bölümü olmalıdır."); var target = request.TargetDateUtc?.ToUniversalTime() ?? now.AddDays(30); var number = $"DÖF-{now.Year}-{await NextNumber("capa", now.Year, tx, ct):000000}"; var qr = QualityRecord.Create(number, "capa", user.Id, departmentId, now);
            var capa = Capa.Create(qr.Id, null, "Complaint", $"{c.Product} müşteri şikâyeti için DÖF", c.Description, c.ConfirmedRootCause ?? "Şikâyet araştırması", "Müşteri etkisini kontrol altına alma", capaOwner.Name, target, request.EffectivenessRequired, request.EffectivenessRequired ? "Tekrar şikâyet trendi izleme" : "", request.EffectivenessRequired ? "Aynı ürün ve şikâyet tipi" : "", request.EffectivenessRequired ? 30 : 0, request.EffectivenessRequired ? "Gözlem döneminde tekrar oluşmaması" : "", request.EffectivenessRequired ? "Kalite Güvence" : "", now);
            db.QualityRecords.Add(qr); db.Capas.Add(capa); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Capa", capa.Id, WorkflowTaskRoles.Initiator, user.Id, user.DepartmentId, now, target)); db.AuditEvents.Add(AuditEvent.Create("Capa", capa.Id, capa.Version, "CapaCreatedFromComplaint", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { complaintId = c.Id, complaintNumber = await db.QualityRecords.Where(x => x.Id == c.QualityRecordId).Select(x => x.RecordNumber).SingleAsync(ct) }))); capaId = capa.Id;
        }
        c.DecideCapa(request.ExpectedVersion, request.CapaRequired, capaId, now); db.AuditEvents.Add(Audit(c, "ComplaintCapaDecisionRecorded", now, new { request.CapaRequired, capaId })); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct);
    }

    public async Task<ComplaintOptionsResponse> GetOptionsAsync(CancellationToken ct)
    {
        var coordinatorIds = await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id where role.Name == QmsRoles.Administrator || role.Name == QmsRoles.QualityAssurance || role.Name == QmsRoles.DepartmentManager select link.UserId).Distinct().ToListAsync(ct); var owners = await (from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.IsActive && coordinatorIds.Contains(u.Id) orderby u.DisplayName select new ComplaintUserOptionResponse(u.Id, u.DisplayName, u.DepartmentId, d == null ? null : d.Name)).ToListAsync(ct);
        var departments = new List<ComplaintDepartmentOptionResponse>(); foreach (var d in await db.Departments.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.Name).ToListAsync(ct)) { var investigator = await ResolveInvestigator(d.Id, null, ct); if (investigator is not null) departments.Add(new(d.Id, d.Code, d.Name, investigator.Value.Id, investigator.Value.Name)); }
        var definitions = await db.ComplaintLookupDefinitions.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync(ct); IReadOnlyList<ComplaintLookupOptionResponse> Values(string category) => definitions.Where(x => x.Category == category).Select(x => new ComplaintLookupOptionResponse(x.Code, x.Name)).ToList();
        return new(owners, departments, Values("Channel"), Values("Country"), Values("ComplaintType"));
    }
    public async Task<IReadOnlyList<ComplaintLookupDefinitionResponse>> ListLookupDefinitionsAsync(CancellationToken ct) => await db.ComplaintLookupDefinitions.AsNoTracking().OrderBy(x => x.Category).ThenBy(x => x.SortOrder).Select(x => new ComplaintLookupDefinitionResponse(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive)).ToListAsync(ct);
    public async Task<ComplaintLookupDefinitionResponse> CreateLookupDefinitionAsync(CreateComplaintLookupDefinitionRequest request, CancellationToken ct) { var category = request.Category.Trim(); if (!LookupCategories.Contains(category)) throw new ArgumentException("M.06 lookup kategorisi geçersizdir."); if (await db.ComplaintLookupDefinitions.AnyAsync(x => x.Category == category && x.Code == request.Code.Trim(), ct)) throw new InvalidOperationException("Aynı kategori ve kodla lookup zaten mevcut."); var now = time.GetUtcNow(); var x = ComplaintLookupDefinition.Create(category, request.Code, request.Name, request.SortOrder, now); db.ComplaintLookupDefinitions.Add(x); db.AuditEvents.Add(AuditEvent.Create("ComplaintLookupDefinition", x.Id, 1, "ComplaintLookupCreated", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { x.Category, x.Code, x.Name, x.SortOrder }))); await db.SaveChangesAsync(ct); return new(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive); }
    public async Task<ComplaintLookupDefinitionResponse?> UpdateLookupDefinitionAsync(Guid id, UpdateComplaintLookupDefinitionRequest request, CancellationToken ct) { var x = await db.ComplaintLookupDefinitions.SingleOrDefaultAsync(x => x.Id == id, ct); if (x is null) return null; var now = time.GetUtcNow(); x.Update(request.Name, request.SortOrder, request.IsActive, now); db.AuditEvents.Add(AuditEvent.Create("ComplaintLookupDefinition", x.Id, 1, "ComplaintLookupUpdated", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { x.Category, x.Code, x.Name, x.SortOrder, x.IsActive }))); await db.SaveChangesAsync(ct); return new(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive); }

    private async Task<ComplaintDetailsResponse?> Mutate(Guid id, CancellationToken ct, Func<Complaint, DateTimeOffset, (string Type, object Payload, string? Reason)> action, Func<Complaint, DateTimeOffset, Task>? after = null) { var c = await Load(id, ct); if (c is null) return null; var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var a = action(c, now); if (after is not null) await after(c, now); db.AuditEvents.Add(Audit(c, a.Type, now, a.Payload, a.Reason)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    private Task<Complaint?> Load(Guid id, CancellationToken ct) => db.Complaints.Include(x => x.Investigations).Include(x => x.Responses).SingleOrDefaultAsync(x => x.Id == id, ct);
    private async Task<Guid> CreateDeviation(Complaint c, DateTimeOffset now, IDbContextTransaction tx, CancellationToken ct) { var departmentId = user.DepartmentId ?? throw new InvalidOperationException("Sapma açacak kullanıcının organizasyon bölümü olmalıdır."); var number = $"SP-{now.Year}-{await NextNumber("deviation", now.Year, tx, ct):000000}"; var qr = QualityRecord.Create(number, "deviation", user.Id, departmentId, now); var sev = c.Severity == ComplaintSeverity.Critical ? 5 : 4; var deviation = Deviation.CreateDraft(qr.Id, $"{c.Product} müşteri şikâyeti", c.Description, "Onaylı ürün kalite gereklilikleri", "Şikâyet edilen batch/seri için dağıtım ve numune değerlendirmesi", "Müşteri Şikâyeti", "Kalite Güvence", "Pazar sonrası ürün", c.EventAtUtc, c.ReceivedAtUtc, c.TrendFlagged ? 4 : 2, sev, 3, now); db.QualityRecords.Add(qr); db.Deviations.Add(deviation); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Deviation", deviation.Id, WorkflowTaskRoles.Initiator, user.Id, departmentId, now, deviation.TargetDateUtc, assignedUserNameSnapshot: user.DisplayName)); db.AuditEvents.Add(AuditEvent.Create("Deviation", deviation.Id, deviation.Version, "DeviationCreatedFromComplaint", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { complaintId = c.Id, product = c.Product, c.BatchNumber }))); return deviation.Id; }
    private async Task<Guid> CreatePvReferral(Complaint c, DateTimeOffset now, IDbContextTransaction tx, CancellationToken ct) { var departmentId = user.DepartmentId ?? throw new InvalidOperationException("Farmakovijilans aktarımı yapacak kullanıcının organizasyon bölümü olmalıdır."); var number = $"FV-{now.Year}-{await NextNumber("pharmacovigilance", now.Year, tx, ct):000000}"; var qr = QualityRecord.Create(number, "pharmacovigilance", user.Id, departmentId, now, JsonSerializer.SerializeToDocument(new { sourceComplaintId = c.Id, c.Product, c.BatchNumber, severity = c.Severity.ToString(), privacyBoundary = "NoCustomerOrHealthNarrativeTransferred" })); db.QualityRecords.Add(qr); return qr.Id; }
    private void EnsureManager() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.DepartmentManager)) return; throw new QmsForbiddenException("Şikâyet koordinasyonu için KG veya bölüm yöneticisi rolü gerekir."); }
    private void EnsureInvestigator() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.Investigator) || user.IsInRole(QmsRoles.DepartmentManager)) return; throw new QmsForbiddenException("Araştırma işlemi için araştırmacı rolü gerekir."); }
    private void EnsureApprover(QualityRecord? record) { if (record is not null && record.CreatedByUserId == user.Id && !user.IsInRole(QmsRoles.Administrator)) throw new QmsForbiddenException("Görev ayrılığı: Şikâyeti oluşturan kullanıcı nihai kapanışı onaylayamaz."); if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.Approver) || user.IsInRole(QmsRoles.QualifiedPerson)) return; throw new QmsForbiddenException("Yanıt onayı için onaylayan rolü gerekir."); }
    private async Task EnsureLookup(string category, string code, CancellationToken ct) { if (!await db.ComplaintLookupDefinitions.AsNoTracking().AnyAsync(x => x.Category == category && x.Code == code.Trim() && x.IsActive, ct)) throw new ArgumentException($"Seçilen {category} tanımı etkin M.06 lookup kayıtlarında bulunamadı."); }
    private async Task<(Guid Id, string Name)> ActiveUser(Guid id, CancellationToken ct) => await db.Users.AsNoTracking().Where(x => x.Id == id && x.IsActive).Select(x => new ValueTuple<Guid, string>(x.Id, x.DisplayName)).SingleOrDefaultAsync(ct) is var result && result.Item1 != Guid.Empty ? result : throw new ArgumentException("Seçilen kullanıcı etkin değil.");
    private async Task<bool> IsComplaintCoordinator(Guid id, CancellationToken ct) => await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id where link.UserId == id && (role.Name == QmsRoles.Administrator || role.Name == QmsRoles.QualityAssurance || role.Name == QmsRoles.DepartmentManager) select link).AnyAsync(ct);
    private async Task<IReadOnlyList<(Guid DepartmentId, string Department, Guid InvestigatorUserId, string Investigator)>> ResolveInvestigations(IReadOnlyList<Guid> ids, Guid excludedUserId, CancellationToken ct) { var result = new List<(Guid, string, Guid, string)>(); foreach (var id in ids.Distinct()) { var department = await db.Departments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.IsActive, ct) ?? throw new ArgumentException("Seçilen araştırma bölümü etkin değil."); var investigator = await ResolveInvestigator(id, excludedUserId, ct) ?? throw new InvalidOperationException($"{department.Name} için atanabilir etkin şikâyet araştırmacısı bulunamadı."); result.Add((department.Id, department.Name, investigator.Id, investigator.Name)); } if (result.Count == 0) throw new ArgumentException("En az bir araştırma bölümü seçilmelidir."); return result; }
    private async Task<(Guid Id, string Name)?> ResolveInvestigator(Guid departmentId, Guid? excludedUserId, CancellationToken ct) { var candidate = await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id join target in db.Users.AsNoTracking() on link.UserId equals target.Id where (role.Name == QmsRoles.Investigator || role.Name == QmsRoles.DepartmentManager || role.Name == QmsRoles.QualityAssurance) && target.IsActive && target.DepartmentId == departmentId && target.Id != excludedUserId orderby role.Name == QmsRoles.Investigator ? 0 : 1, target.DisplayName select new { target.Id, target.DisplayName }).FirstOrDefaultAsync(ct); return candidate is null ? null : (candidate.Id, candidate.DisplayName); }
    private async Task AssignApprover(Complaint complaint, DateTimeOffset now, CancellationToken ct) { var preparerIds = complaint.Responses.Where(x => x.Status == ComplaintResponseStatus.Draft).Select(x => x.PreparedByUserId).ToArray(); var approver = await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id join target in db.Users.AsNoTracking() on link.UserId equals target.Id where (role.Name == QmsRoles.Approver || role.Name == QmsRoles.QualifiedPerson || role.Name == QmsRoles.QualityAssurance) && target.IsActive && !preparerIds.Contains(target.Id) orderby role.Name == QmsRoles.QualifiedPerson ? 0 : 1, target.DisplayName select target.Id).FirstOrDefaultAsync(ct); if (approver == Guid.Empty) throw new InvalidOperationException("Yanıtı hazırlayan kişiden farklı atanabilir etkin M.06 onaylayıcısı bulunamadı."); if (!await db.WorkflowTaskAssignments.AnyAsync(x => x.AggregateType == "Complaint" && x.AggregateId == complaint.Id && x.TaskRole == WorkflowTaskRoles.ResponseApprover && x.Status == WorkflowTaskStatus.Active, ct)) await Assign(complaint.Id, WorkflowTaskRoles.ResponseApprover, approver, now, complaint.FinalResponseDueAtUtc, ct); }
    private async Task Assign(Guid id, string role, Guid userId, DateTimeOffset now, DateTimeOffset? due, CancellationToken ct) { var target = await (from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.Id == userId && u.IsActive select new { u.Id, u.DisplayName, u.DepartmentId, DepartmentName = d == null ? null : d.Name }).SingleOrDefaultAsync(ct) ?? throw new InvalidOperationException("M.06 görevi için seçilen kullanıcı etkin değil."); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Complaint", id, role, target.Id, target.DepartmentId, now, due, assignedUserNameSnapshot: target.DisplayName, assignedDepartmentNameSnapshot: target.DepartmentName)); db.UserNotifications.Add(UserNotification.Create(target.Id, "M.06", "Yeni müşteri şikâyeti görevi", $"{role} görevi size atandı.", $"/modules/m06?open={id}", now)); }
    private async Task EnsureActor(Guid id, string role, CancellationToken ct) { if (!await CanAct(id, role, ct)) throw new QmsForbiddenException("Bu şikâyet görevi size veya etkin bir delegasyonla size atanmamış."); }
    private async Task<bool> CanAct(Guid id, string role, CancellationToken ct) { var owners = await db.WorkflowTaskAssignments.AsNoTracking().Where(x => x.AggregateType == "Complaint" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active).Select(x => x.AssignedUserId).ToListAsync(ct); if (owners.Contains(user.Id)) return true; var now = time.GetUtcNow(); return owners.Count > 0 && await db.Delegations.AsNoTracking().AnyAsync(x => owners.Contains(x.DelegatorUserId) && x.DelegateUserId == user.Id && x.RevokedAtUtc == null && x.StartsAtUtc <= now && x.EndsAtUtc >= now && (x.Scope == "M.06" || x.Scope == "ALL"), ct); }
    private async Task<IReadOnlyList<string>> CurrentTaskRoles(Guid id, CancellationToken ct) { var roles = await db.WorkflowTaskAssignments.AsNoTracking().Where(x => x.AggregateType == "Complaint" && x.AggregateId == id && x.Status == WorkflowTaskStatus.Active).Select(x => x.TaskRole).Distinct().ToListAsync(ct); var result = new List<string>(); foreach (var role in roles) if (await CanAct(id, role, ct)) result.Add(role); return result; }
    private async Task CompleteTasks(Guid id, string role, DateTimeOffset now, CancellationToken ct) { var tasks = await db.WorkflowTaskAssignments.Where(x => x.AggregateType == "Complaint" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active).ToListAsync(ct); foreach (var task in tasks) task.Complete(now); }
    private async Task CompleteAllTasks(Guid id, DateTimeOffset now, CancellationToken ct) { var tasks = await db.WorkflowTaskAssignments.Where(x => x.AggregateType == "Complaint" && x.AggregateId == id && x.Status == WorkflowTaskStatus.Active).ToListAsync(ct); foreach (var task in tasks) task.Complete(now); }
    private async Task EnsureSignature(string? password, bool accepted, CancellationToken ct) { if (!accepted || string.IsNullOrWhiteSpace(password)) throw new ArgumentException("Elektronik imza için parola ve anlam kabulü zorunludur."); var target = await userManager.FindByIdAsync(user.Id.ToString()) ?? throw new QmsForbiddenException("İmzalayan kullanıcı bulunamadı."); if (!await userManager.CheckPasswordAsync(target, password)) throw new QmsForbiddenException("Elektronik imza parolası geçersizdir."); }
    private AuditEvent Audit(Complaint c, string type, DateTimeOffset now, object payload, string? reason = null) => AuditEvent.Create("Complaint", c.Id, c.Version, type, user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(payload), reason);
    private static string SignatureHash(Guid id, long version, string action, string? note) => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes($"{id:N}|{version}|{action}|{note}")));
    private static IReadOnlyList<ComplaintTransitionResponse> Transitions(ComplaintStatus status, IReadOnlyList<string> roles) { var all = status switch { ComplaintStatus.Received => new[] { new ComplaintTransitionResponse("start-triage", "Triyajı başlat", false) }, ComplaintStatus.Triage => [new("complete-triage", "Triyajı tamamla ve bağlantıları oluştur", false)], ComplaintStatus.PreliminaryResponse => [new("start-investigation", "Araştırmaları başlat", false)], ComplaintStatus.Investigation => [new("finish-investigations", "Etki değerlendirmesine geç", false)], ComplaintStatus.FinalResponseApproval => [new("close", "Şikâyeti kapat", true)], _ => [] }; return all.Where(x => roles.Contains(x.Code == "close" ? WorkflowTaskRoles.ResponseApprover : WorkflowTaskRoles.ComplaintCoordinator)).ToList(); }
    private static IQueryable<ComplaintRow> ApplyFilter(IQueryable<ComplaintRow> q, ColumnFilterRequest f) { var field=f.Field.Trim().ToLowerInvariant();var op=f.Operator.Trim().ToLowerInvariant();var value=f.Value?.Trim()??"";return field switch { "recordnumber"=>op=="equals"?q.Where(x=>x.RecordNumber==value):q.Where(x=>x.RecordNumber.ToLower().Contains(value.ToLower())), "customername"=>op=="equals"?q.Where(x=>x.Complaint.CustomerName==value):q.Where(x=>x.Complaint.CustomerName.ToLower().Contains(value.ToLower())), "product"=>op=="equals"?q.Where(x=>x.Complaint.Product==value):q.Where(x=>x.Complaint.Product.ToLower().Contains(value.ToLower())), "batchnumber"=>q.Where(x=>x.Complaint.BatchNumber!=null&&x.Complaint.BatchNumber.ToLower().Contains(value.ToLower())), "complainttype"=>op=="equals"?q.Where(x=>x.Complaint.ComplaintType==value):q.Where(x=>x.Complaint.ComplaintType.ToLower().Contains(value.ToLower())), "owner"=>op=="equals"?q.Where(x=>x.Complaint.Owner==value):q.Where(x=>x.Complaint.Owner.ToLower().Contains(value.ToLower())), "severity"=>Enum.TryParse<ComplaintSeverity>(value,true,out var severity)?q.Where(x=>x.Complaint.Severity==severity):throw new ArgumentException("Önem derecesi geçersizdir."), "status"=>Enum.TryParse<ComplaintStatus>(value,true,out var status)?q.Where(x=>x.Complaint.Status==status):throw new ArgumentException("Şikâyet durumu geçersizdir."), "suspectedadverseevent"=>bool.TryParse(value,out var adverse)?q.Where(x=>x.Complaint.SuspectedAdverseEvent==adverse):throw new ArgumentException("Boolean filtre geçersizdir."), "trendflagged"=>bool.TryParse(value,out var trend)?q.Where(x=>x.Complaint.TrendFlagged==trend):throw new ArgumentException("Boolean filtre geçersizdir."), "finalresponsedueatutc"=>DateFilter(q,op,f.Value,f.ValueTo,true), "createdatutc"=>DateFilter(q,op,f.Value,f.ValueTo,false), _=>throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}")}; }
    private static IQueryable<ComplaintRow> DateFilter(IQueryable<ComplaintRow> q,string op,string? a,string? b,bool due){var from=DateTimeOffset.Parse(a??"",CultureInfo.InvariantCulture).ToUniversalTime();var to=string.IsNullOrWhiteSpace(b)?from.AddDays(1):DateTimeOffset.Parse(b,CultureInfo.InvariantCulture).ToUniversalTime();return(op,due)switch{("before",true)=>q.Where(x=>x.Complaint.FinalResponseDueAtUtc<from),("after",true)=>q.Where(x=>x.Complaint.FinalResponseDueAtUtc>from),(_,true)=>q.Where(x=>x.Complaint.FinalResponseDueAtUtc>=from&&x.Complaint.FinalResponseDueAtUtc<to),("before",false)=>q.Where(x=>x.Complaint.CreatedAtUtc<from),("after",false)=>q.Where(x=>x.Complaint.CreatedAtUtc>from),_=>q.Where(x=>x.Complaint.CreatedAtUtc>=from&&x.Complaint.CreatedAtUtc<to)};}
    private static IQueryable<ComplaintRow> ApplySort(IQueryable<ComplaintRow> q,string field,string direction){var d=direction.Equals("desc",StringComparison.OrdinalIgnoreCase);return field.Trim().ToLowerInvariant()switch{"recordnumber"=>d?q.OrderByDescending(x=>x.RecordNumber):q.OrderBy(x=>x.RecordNumber),"customername"=>d?q.OrderByDescending(x=>x.Complaint.CustomerName):q.OrderBy(x=>x.Complaint.CustomerName),"product"=>d?q.OrderByDescending(x=>x.Complaint.Product):q.OrderBy(x=>x.Complaint.Product),"severity"=>d?q.OrderByDescending(x=>x.Complaint.Severity):q.OrderBy(x=>x.Complaint.Severity),"status"=>d?q.OrderByDescending(x=>x.Complaint.Status):q.OrderBy(x=>x.Complaint.Status),"finalresponsedueatutc"=>d?q.OrderByDescending(x=>x.Complaint.FinalResponseDueAtUtc):q.OrderBy(x=>x.Complaint.FinalResponseDueAtUtc),_=>d?q.OrderByDescending(x=>x.Complaint.CreatedAtUtc):q.OrderBy(x=>x.Complaint.CreatedAtUtc)};}
    private async Task<long> NextNumber(string type,int year,IDbContextTransaction tx,CancellationToken ct){var connection=db.Database.GetDbConnection();if(connection.State!=ConnectionState.Open)await connection.OpenAsync(ct);await using var command=connection.CreateCommand();command.Transaction=tx.GetDbTransaction();command.CommandText="INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@recordType, @calendarYear, 1) ON CONFLICT (\"RecordType\", \"CalendarYear\") DO UPDATE SET \"LastValue\" = core.record_number_sequence.\"LastValue\" + 1 RETURNING \"LastValue\";";Add(command,"recordType",type);Add(command,"calendarYear",year);return Convert.ToInt64(await command.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);}
    private static void Add(DbCommand command,string name,object value){var p=command.CreateParameter();p.ParameterName=name;p.Value=value;command.Parameters.Add(p);} private sealed class ComplaintRow{public required Complaint Complaint{get;init;}public required string RecordNumber{get;init;}}
}
