using System.Text.Json;

namespace Qms.Contracts.Complaints;

public sealed record ComplaintListItemResponse(Guid Id, string RecordNumber, string CustomerName, string Country, string Product, string? BatchNumber, string ComplaintType, string Severity, string Status, string Owner, DateTimeOffset PreliminaryResponseDueAtUtc, DateTimeOffset FinalResponseDueAtUtc, bool SuspectedAdverseEvent, bool TrendFlagged, int SimilarComplaintCount, DateTimeOffset CreatedAtUtc, long Version);
public sealed record ComplaintRecordResponse(Guid Id, Guid QualityRecordId, string RecordNumber, string Channel, string CustomerName, string Country, string Product, string? BatchNumber, DateTimeOffset EventAtUtc, DateTimeOffset ReceivedAtUtc, string ComplaintType, string Description, string Severity, bool HasHealthImpact, bool SuspectedAdverseEvent, bool SampleExpected, bool ReturnExpected, string AttachmentSummary, string Owner, DateTimeOffset PreliminaryResponseDueAtUtc, DateTimeOffset FinalResponseDueAtUtc, int SimilarComplaintCount, bool TrendFlagged, Guid? LinkedDeviationId, string? LinkedDeviationNumber, Guid? LinkedCapaId, string? LinkedCapaNumber, Guid? PharmacovigilanceRecordId, string? PharmacovigilanceRecordNumber, string? PharmacovigilanceStatus, string? ImpactAssessment, string? ConfirmedRootCause, bool? CapaRequired, string? ClosureNote, string Status, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? ClosedAtUtc, long Version);
public sealed record ComplaintInvestigationResponse(Guid Id, string Department, string Investigator, string Status, string? Findings, string? RootCauseContribution, DateTimeOffset? CompletedAtUtc);
public sealed record ComplaintResponseVersionResponse(Guid Id, string ResponseType, int VersionNumber, string Content, string Status, string PreparedBy, string? ApprovedBy, DateTimeOffset CreatedAtUtc, DateTimeOffset? ApprovedAtUtc);
public sealed record ComplaintAuditEventResponse(Guid Id, long Version, string EventType, string Actor, DateTimeOffset OccurredAtUtc, string? Reason, JsonElement Payload);
public sealed record ComplaintTransitionResponse(string Code, string Label, bool NoteRequired);
public sealed record ComplaintDetailsResponse(ComplaintRecordResponse Record, IReadOnlyList<ComplaintInvestigationResponse> Investigations, IReadOnlyList<ComplaintResponseVersionResponse> Responses, IReadOnlyList<ComplaintAuditEventResponse> AuditTrail, IReadOnlyList<ComplaintTransitionResponse> AvailableTransitions);
