using System.Text.Json;

namespace Qms.Contracts.Complaints;

public sealed record ComplaintListItemResponse(Guid Id, string RecordNumber, string CustomerName, string Country, string Product, string? BatchNumber, string ComplaintType, string Severity, string Status, string Owner, DateTimeOffset PreliminaryResponseDueAtUtc, DateTimeOffset FinalResponseDueAtUtc, bool SuspectedAdverseEvent, bool TrendFlagged, int SimilarComplaintCount, DateTimeOffset CreatedAtUtc, long Version);
public sealed record ComplaintRecordResponse(Guid Id, Guid QualityRecordId, string RecordNumber, string Channel, string CustomerName, string Country, string Product, string? BatchNumber, DateTimeOffset EventAtUtc, DateTimeOffset ReceivedAtUtc, string ComplaintType, string Description, string Severity, bool HasHealthImpact, bool SuspectedAdverseEvent, bool SampleExpected, bool ReturnExpected, string AttachmentSummary, Guid OwnerUserId, string Owner, DateTimeOffset PreliminaryResponseDueAtUtc, DateTimeOffset FinalResponseDueAtUtc, int SimilarComplaintCount, bool TrendFlagged, Guid? LinkedDeviationId, string? LinkedDeviationNumber, Guid? LinkedCapaId, string? LinkedCapaNumber, Guid? PharmacovigilanceRecordId, string? PharmacovigilanceRecordNumber, string? PharmacovigilanceStatus, string? ImpactAssessment, string? ConfirmedRootCause, bool? CapaRequired, string? ClosureNote, string Status, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? ClosedAtUtc, long Version);
public sealed record ComplaintInvestigationResponse(Guid Id, Guid DepartmentId, string Department, Guid InvestigatorUserId, string Investigator, string Status, string? Findings, string? RootCauseContribution, DateTimeOffset? CompletedAtUtc);
public sealed record ComplaintResponseVersionResponse(Guid Id, string ResponseType, int VersionNumber, string Content, string Status, Guid PreparedByUserId, string PreparedBy, Guid? ApprovedByUserId, string? ApprovedBy, DateTimeOffset CreatedAtUtc, DateTimeOffset? ApprovedAtUtc);
public sealed record ComplaintAuditEventResponse(Guid Id, long Version, string EventType, string Actor, DateTimeOffset OccurredAtUtc, string? Reason, JsonElement Payload);
public sealed record ComplaintTransitionResponse(string Code, string Label, bool NoteRequired);
public sealed record ComplaintSignatureResponse(Guid Id, long RecordVersion, Guid SignerUserId, string Signer, string Meaning, DateTimeOffset SignedAtUtc, string ContentHash, string? Comment);
public sealed record ComplaintDetailsResponse(ComplaintRecordResponse Record, IReadOnlyList<ComplaintInvestigationResponse> Investigations, IReadOnlyList<ComplaintResponseVersionResponse> Responses, IReadOnlyList<ComplaintAuditEventResponse> AuditTrail, IReadOnlyList<ComplaintSignatureResponse> Signatures, IReadOnlyList<ComplaintTransitionResponse> AvailableTransitions, IReadOnlyList<string> ActionableTaskRoles);
public sealed record ComplaintLookupOptionResponse(string Code, string Name);
public sealed record ComplaintUserOptionResponse(Guid Id, string Name, Guid? DepartmentId, string? Department);
public sealed record ComplaintDepartmentOptionResponse(Guid Id, string Code, string Name, Guid InvestigatorUserId, string Investigator);
public sealed record ComplaintOptionsResponse(IReadOnlyList<ComplaintUserOptionResponse> Owners, IReadOnlyList<ComplaintDepartmentOptionResponse> Departments, IReadOnlyList<ComplaintLookupOptionResponse> Channels, IReadOnlyList<ComplaintLookupOptionResponse> Countries, IReadOnlyList<ComplaintLookupOptionResponse> ComplaintTypes);
public sealed record ComplaintLookupDefinitionResponse(Guid Id, string Category, string Code, string Name, int SortOrder, bool IsActive);
