using System.Data; using System.Data.Common; using System.Globalization; using System.Text.Json; using Microsoft.EntityFrameworkCore; using Microsoft.EntityFrameworkCore.Storage; using Qms.Application.ExternalAudits; using Qms.Application.ElectronicSignatures; using Qms.Application.Security; using Qms.Contracts.Common; using Qms.Contracts.ExternalAudits; using Qms.Domain.AuditTrail; using Qms.Domain.Capas; using Qms.Domain.Documents; using Qms.Domain.ExternalAudits; using Qms.Domain.QualityRecords; using Qms.Domain.Workflows; using Qms.Infrastructure.Persistence;
using Microsoft.AspNetCore.Identity;
using Qms.Infrastructure.Identity;
using Qms.Domain.Notifications;
using Qms.Infrastructure.Security;
namespace Qms.Infrastructure.ExternalAudits;
public sealed class ExternalAuditService(QmsDbContext db,TimeProvider time,ICurrentUser user,UserManager<ApplicationUser> users,IElectronicSignatureService signatures):IExternalAuditService
{
    public async Task<ExternalAuditOptionsResponse> GetOptionsAsync(CancellationToken ct)
    {
        var people=await(from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.IsActive orderby u.DisplayName select new ExternalAuditIdentityOption(u.Id,u.DisplayName,d==null?null:d.Name)).ToListAsync(ct);
        var documents=await VisibleDocuments().Where(x=>x.Status==ControlledDocumentStatus.Effective).OrderBy(x=>x.DocumentCode).Select(x=>new ExternalAuditDocumentOption(x.Id,x.DocumentCode,x.Title)).ToListAsync(ct);
        var definitions=await db.ExternalAuditLookupDefinitions.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Name).ToListAsync(ct);
        IReadOnlyList<ExternalAuditCodeOption> Values(string category)=>definitions.Where(x=>x.Category==category).Select(x=>new ExternalAuditCodeOption(x.Code,x.Name)).ToList();
        var classes=Enum.GetValues<ExternalAuditFindingClassification>().Select(x=>new ExternalAuditCodeOption(x.ToString(),x switch{ExternalAuditFindingClassification.Critical=>"Kritik",ExternalAuditFindingClassification.Major=>"Majör",ExternalAuditFindingClassification.Minor=>"Minör",_=>"Gözlem"})).ToList();
        return new(people,people,documents,Values("AuditKind"),Values("Country"),Values("Confidentiality"),classes);
    }
    public async Task<IReadOnlyList<ExternalAuditLookupDefinitionResponse>> ListLookupDefinitionsAsync(CancellationToken ct)=>await db.ExternalAuditLookupDefinitions.AsNoTracking().OrderBy(x=>x.Category).ThenBy(x=>x.SortOrder).Select(x=>new ExternalAuditLookupDefinitionResponse(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive)).ToListAsync(ct);
    public async Task<ExternalAuditLookupDefinitionResponse> CreateLookupDefinitionAsync(CreateExternalAuditLookupDefinitionRequest r,CancellationToken ct){EnsureLookupCategory(r.Category);if(await db.ExternalAuditLookupDefinitions.AnyAsync(x=>x.Category==r.Category.Trim()&&x.Code==r.Code.Trim(),ct))throw new InvalidOperationException("Aynı M.08 lookup kodu zaten mevcut.");var now=time.GetUtcNow();var x=ExternalAuditLookupDefinition.Create(r.Category,r.Code,r.Name,r.SortOrder,now);db.ExternalAuditLookupDefinitions.Add(x);db.AuditEvents.Add(AuditEvent.Create("ExternalAuditLookupDefinition",x.Id,1,"ExternalAuditLookupCreated",user.Id,user.DisplayName,now,Qms.Infrastructure.Integrity.AuditCorrelation.Current,JsonSerializer.SerializeToDocument(new{x.Category,x.Code,x.Name,x.SortOrder})));await db.SaveChangesAsync(ct);return new(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive);}
    public async Task<ExternalAuditLookupDefinitionResponse?> UpdateLookupDefinitionAsync(Guid id,UpdateExternalAuditLookupDefinitionRequest r,CancellationToken ct){var x=await db.ExternalAuditLookupDefinitions.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return null;var now=time.GetUtcNow();x.Update(r.Name,r.SortOrder,r.IsActive,now);db.AuditEvents.Add(AuditEvent.Create("ExternalAuditLookupDefinition",x.Id,1,"ExternalAuditLookupUpdated",user.Id,user.DisplayName,now,Qms.Infrastructure.Integrity.AuditCorrelation.Current,JsonSerializer.SerializeToDocument(new{x.Category,x.Code,x.Name,x.SortOrder,x.IsActive})));await db.SaveChangesAsync(ct);return new(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive);}
    public async Task<PagedResponse<ExternalAuditListItemResponse>> SearchAsync(ExternalAuditSearchRequest r,CancellationToken ct){if(r.Page<1||r.PageSize is not(10 or 25 or 50 or 100))throw new ArgumentException("Sayfa bilgisi geçersizdir.");var q=from a in db.ExternalAudits.AsNoTracking()join qr in db.VisibleQualityRecords(user)on a.QualityRecordId equals qr.Id select new Row{Audit=a,Number=qr.RecordNumber};foreach(var f in r.Filters??[])q=Filter(q,f);var total=await q.LongCountAsync(ct);q=Sort(q,r.SortBy,r.SortDirection);var items=await q.Skip((r.Page-1)*r.PageSize).Take(r.PageSize).Select(x=>new ExternalAuditListItemResponse(x.Audit.Id,x.Number,x.Audit.Title,x.Audit.AuditKind,x.Audit.AuditorOrganization,x.Audit.IsGovernmentAuthority,x.Audit.AuthorityCountry,x.Audit.Owner,x.Audit.PlannedStartUtc,x.Audit.ResponseDueAtUtc,x.Audit.Status.ToString(),x.Audit.Findings.Count,x.Audit.Findings.Count(f=>f.Status!=ExternalAuditFindingStatus.Closed),x.Audit.DocumentRequests.Count,x.Audit.DocumentRequests.Count(d=>d.Status==ExternalAuditDocumentStatus.Exported),x.Audit.CreatedAtUtc,x.Audit.Version)).ToListAsync(ct);return new(items,r.Page,r.PageSize,total,total==0?0:(int)Math.Ceiling(total/(double)r.PageSize));}
    public async Task<ExternalAuditDetailsResponse?> GetDetailsAsync(Guid id,CancellationToken ct)
    {
        var a=await db.ExternalAudits.AsNoTracking().AsSplitQuery().Include(x=>x.DocumentRequests).Include(x=>x.Findings).SingleOrDefaultAsync(x=>x.Id==id,ct);if(a is null)return null;
        var number=await db.VisibleQualityRecords(user).Where(x=>x.Id==a.QualityRecordId).Select(x=>x.RecordNumber).SingleOrDefaultAsync(ct);if(number is null)return null;
        var capaIds=a.Findings.Where(x=>x.LinkedCapaId.HasValue).Select(x=>x.LinkedCapaId!.Value).ToArray();
        var capaNumbers=await(from c in db.Capas.AsNoTracking()join qr in db.VisibleQualityRecords(user)on c.QualityRecordId equals qr.Id where capaIds.Contains(c.Id)select new{c.Id,qr.RecordNumber}).ToDictionaryAsync(x=>x.Id,x=>x.RecordNumber,ct);
        var accesses=await db.ExternalAuditPackageAccesses.AsNoTracking().Where(x=>x.ExternalAuditId==id).OrderByDescending(x=>x.AccessedAtUtc).ToListAsync(ct);
        var events=await db.AuditEvents.AsNoTracking().Where(x=>x.AggregateType=="ExternalAudit"&&x.AggregateId==id).OrderByDescending(x=>x.OccurredAtUtc).ToListAsync(ct);
        var signatures=await db.ElectronicSignatures.AsNoTracking().Where(x=>x.QualityRecordId==a.QualityRecordId).OrderBy(x=>x.SignedAtUtc).Select(x=>new ExternalAuditSignatureResponse(x.Id,x.RecordVersion,x.SignerUserId,x.SignerDisplayNameSnapshot,x.Meaning,x.SignedAtUtc,x.ContentHash,x.Comment)).ToListAsync(ct);
        var roles=await CurrentTaskRoles(id,ct);
        var record=new ExternalAuditRecordResponse(a.Id,a.QualityRecordId,number,a.Title,a.AuditKind,a.AuditorOrganization,a.IsGovernmentAuthority,a.AuthorityCountry,a.OfficialReference,a.Scope,a.Site,a.Owner,a.NotifiedAtUtc,a.PlannedStartUtc,a.PlannedEndUtc,a.ResponseDueAtUtc,a.AuthorizedCloserUserId,a.AuthorizedCloser,a.ClosureLetterReference,a.ClosureEvidence,a.AuthorityAccepted,a.ClosureLetterReceivedAtUtc,a.ClosureNote,a.Status.ToString(),a.CreatedAtUtc,a.UpdatedAtUtc,a.ClosedAtUtc,a.Version);
        return new(record,a.DocumentRequests.OrderBy(x=>x.DocumentCode).Select(x=>new ExternalAuditDocumentResponse(x.Id,x.ControlledDocumentId,x.DocumentCode,x.Title,x.Confidentiality,x.Status.ToString(),x.ExportVersion,x.ExportedAtUtc)).ToList(),accesses.Select(x=>new ExternalAuditPackageAccessResponse(x.Id,x.DocumentRequestId,x.ExportedBy,x.Recipient,x.Purpose,x.Evidence,x.ExportVersion,x.AccessedAtUtc)).ToList(),a.Findings.OrderBy(x=>x.Number).Select(x=>new ExternalAuditFindingResponse(x.Id,x.Number,x.Title,x.Description,x.OfficialReference,x.Classification.ToString(),x.CapaRequired,x.LinkedCapaId,x.LinkedCapaId is Guid cid?capaNumbers.GetValueOrDefault(cid):null,x.Owner,x.ResponseDueAtUtc,x.OfficialResponse,x.Commitment,x.CommitmentDueAtUtc,x.VerificationNote,x.Status.ToString(),x.CreatedAtUtc,x.ClosedAtUtc)).ToList(),events.Select(x=>new ExternalAuditEventResponse(x.Id,x.AggregateVersion,x.EventType,x.ActorDisplayNameSnapshot,x.OccurredAtUtc,x.Reason,x.Payload.RootElement.Clone())).ToList(),signatures,Transitions(a.Status).Where(x=>roles.Contains(RoleForTransition(x.Code))).ToList(),roles);
    }
    public async Task<ExternalAuditDetailsResponse> CreateAsync(CreateExternalAuditRequest r,CancellationToken ct)
    {
        EnsureCreate();
        var owner = await ResolveUser(r.OwnerUserId, "Dış denetim sorumlusu", ct);
        ApplicationUser? closer = null;
        if (r.AuthorizedCloserUserId is Guid requestedCloserId)
            closer = await ResolveUser(requestedCloserId, "Kapanış yetkilisi", ct);
        if (closer is null)
            throw new ArgumentException("Bağımsız kapanış yetkilisi zorunludur.");
        if (closer.Id==user.Id&&!user.IsInRole(QmsRoles.Administrator))
            throw new ArgumentException("Görev ayrılığı: Kaydı oluşturan kullanıcı kapanış yetkilisi olamaz.");
        if (user.DepartmentId is null)
            throw new InvalidOperationException("Kaydı açan kullanıcının aktif organizasyon bölümü bulunmalıdır.");
        var controlledDocumentIds = r.DocumentRequests
            .Where(x => x.ControlledDocumentId.HasValue)
            .Select(x => x.ControlledDocumentId!.Value)
            .Distinct()
            .ToArray();

        var controlledDocuments = await VisibleDocuments()
            .Where(x => controlledDocumentIds.Contains(x.Id) && x.Status == ControlledDocumentStatus.Effective)
            .Select(x => new { x.Id, x.DocumentCode, x.Title, x.Confidentiality })
            .ToDictionaryAsync(x => x.Id, ct);
        if (controlledDocuments.Count != controlledDocumentIds.Length)
            throw new ArgumentException("Talep paketine yalnız erişim yetkiniz bulunan, yürürlükteki M.04 dokümanları bağlanabilir.");
        var documentRequests = r.DocumentRequests.Select(request =>
        {
            if (request.ControlledDocumentId is not Guid documentId)
                return (request.ControlledDocumentId, request.DocumentCode, request.Title, request.Confidentiality);
            var document = controlledDocuments[documentId];
            return ((Guid?)document.Id, document.DocumentCode, document.Title, document.Confidentiality);
        }).ToArray();

        var now = time.GetUtcNow();
        await using var tx = await db.Database.BeginTransactionAsync(ct);
        var number = $"DD-{now.Year}-{await Next("external-audit", now.Year, tx, ct):000000}";
        var qr = QualityRecord.Create(number, "external-audit", user.Id, user.DepartmentId.Value, now);
        var audit = ExternalAudit.Create(
            qr.Id,
            r.Title,
            r.AuditKind,
            r.AuditorOrganization,
            r.IsGovernmentAuthority,
            r.AuthorityCountry,
            r.OfficialReference,
            r.Scope,
            r.Site,
            owner.DisplayName,
            r.NotifiedAtUtc.ToUniversalTime(),
            r.PlannedStartUtc.ToUniversalTime(),
            r.PlannedEndUtc.ToUniversalTime(),
            r.ResponseDueAtUtc.ToUniversalTime(),
            r.AuthorizedCloserUserId,
            closer?.DisplayName,
            documentRequests,
            now);
        audit.AssignOwnerIdentity(owner.Id);
        db.QualityRecords.Add(qr);
        db.ExternalAudits.Add(audit);
        await Assign(audit.Id,WorkflowTaskRoles.ExternalAuditCoordinator,owner.Id,now,audit.ResponseDueAtUtc,ct);
        await Assign(audit.Id,WorkflowTaskRoles.DocumentPackageController,owner.Id,now,audit.PlannedStartUtc,ct);
        await Assign(audit.Id,WorkflowTaskRoles.ExternalAuditeeResponder,owner.Id,now,audit.ResponseDueAtUtc,ct);
        if (audit.AuthorizedCloserUserId is Guid closerId)
            await Assign(audit.Id,WorkflowTaskRoles.ExternalAuditAuthorizedCloser,closerId,now,audit.ResponseDueAtUtc,ct);
        db.AuditEvents.Add(Audit(audit, "ExternalAuditCreated", now, new { number, r.IsGovernmentAuthority, r.AuditorOrganization, r.OfficialReference }));
        await db.SaveChangesAsync(ct);
        await tx.CommitAsync(ct);
        return (await GetDetailsAsync(audit.Id, ct))!;
    }
    async Task<ExternalAuditDetailsResponse> IExternalAuditService.CreateAsync(CreateExternalAuditRequest r,CancellationToken ct){await RequireLookup("AuditKind",r.AuditKind,"Denetim türü",ct);await RequireLookup("Country",r.AuthorityCountry,"Ülke",ct);foreach(var item in r.DocumentRequests)await RequireLookup("Confidentiality",item.Confidentiality,"Gizlilik",ct);return await CreateAsync(r,ct);}
    public async Task<ExternalAuditDetailsResponse?> TransitionAsync(Guid id,TransitionExternalAuditRequest r,CancellationToken ct)
    {
        var a=await Load(id,ct);if(a is null)return null;var transition=r.Transition.Trim().ToLowerInvariant();await EnsureActor(id,RoleForTransition(transition),ct);
        var qr=await db.QualityRecords.SingleAsync(x=>x.Id==a.QualityRecordId,ct);EnsureTransition(a,transition,qr);if(transition=="close")await signatures.AuthenticateAsync(r.SignaturePassword,r.SignatureMeaningAccepted,ct);
        var now=time.GetUtcNow();var from=a.Status;await using var tx=await db.Database.BeginTransactionAsync(ct);a.Transition(r.ExpectedVersion,transition,r.Note,now);
        if(transition=="start-preparation")qr.Submit(now);
        if(transition=="start-audit")await CompleteTasks(id,WorkflowTaskRoles.DocumentPackageController,now,ct);
        if(transition=="open-response-plan")await CompleteTasks(id,WorkflowTaskRoles.ExternalAuditCoordinator,now,ct);
        if(transition=="start-capa-actions")await CompleteTasks(id,WorkflowTaskRoles.ExternalAuditeeResponder,now,ct);
        if(transition=="close"){qr.Close(now,false);await CompleteAllTasks(id,now,ct);db.ElectronicSignatures.Add(signatures.CreateInternal(qr.Id,"ExternalAudit",a.Id,a.Version,"close","Dış denetim nihai kapanış onayı",new{audit=a,documentRequests=a.DocumentRequests,findings=a.Findings,r.Note},now,r.Note));}
        db.AuditEvents.Add(Audit(a,"ExternalAuditStatusChanged",now,new{from=from.ToString(),to=a.Status.ToString(),transition},r.Note));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);
    }
    public async Task<ExternalAuditDetailsResponse?> ExportDocumentAsync(Guid id,Guid requestId,ExportExternalAuditDocumentRequest r,CancellationToken ct){EnsurePrepare();await EnsureActor(id,WorkflowTaskRoles.DocumentPackageController,ct);var a=await Load(id,ct);if(a is null)return null;var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);var access=a.ExportDocument(r.ExpectedVersion,requestId,user.Id,user.DisplayName,r.Recipient,r.Purpose,r.Evidence,now);db.ExternalAuditPackageAccesses.Add(access);db.AuditEvents.Add(Audit(a,"ExternalAuditDocumentExported",now,new{requestId,r.Recipient,access.ExportVersion},r.Purpose));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    public async Task<ExternalAuditDetailsResponse?> AddFindingAsync(Guid id,AddExternalAuditFindingRequest r,CancellationToken ct){EnsurePrepare();if(!Enum.TryParse<ExternalAuditFindingClassification>(r.Classification,true,out var classification))throw new ArgumentException("Bulgu sınıfı geçersizdir.");var a=await Load(id,ct);if(a is null)return null;var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);var needsCapa=r.CapaRequired||classification is ExternalAuditFindingClassification.Critical or ExternalAuditFindingClassification.Major;Guid? capaId=null;if(needsCapa){var creatorDepartment=user.DepartmentId??throw new InvalidOperationException("DÖF açacak kullanıcının organizasyon bölümü zorunludur.");var cnum=$"DÖF-{now.Year}-{await Next("capa",now.Year,tx,ct):000000}";var qr=QualityRecord.Create(cnum,"capa",user.Id,creatorDepartment,now);var capa=Capa.Create(qr.Id,null,"ExternalAudit",r.Title,r.Description,$"Dış denetim bulgusu: {r.OfficialReference}","Resmi bulguyu kontrol altına alma",r.Owner,r.ResponseDueAtUtc.ToUniversalTime(),true,"Taahhüt ve otorite kabul kanıtı","Dış denetim kapsamı",30,"Aynı bulgunun tekrar etmemesi","Kalite Güvence",now);db.QualityRecords.Add(qr);db.Capas.Add(capa);db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Capa",capa.Id,WorkflowTaskRoles.Initiator,user.Id,creatorDepartment,now,capa.TargetDateUtc));capaId=capa.Id;db.AuditEvents.Add(AuditEvent.Create("Capa",capa.Id,capa.Version,"CapaCreatedFromExternalAuditFinding",user.Id,user.DisplayName,now,Qms.Infrastructure.Integrity.AuditCorrelation.Current,JsonSerializer.SerializeToDocument(new{externalAuditId=a.Id})));}var fnum=$"DBG-{now.Year}-{await Next("external-audit-finding",now.Year,tx,ct):000000}";var finding=ExternalAuditFinding.Create(a.Id,fnum,r.Title,r.Description,r.OfficialReference,classification,needsCapa,capaId,r.Owner,r.ResponseDueAtUtc.ToUniversalTime(),now);a.AddFinding(r.ExpectedVersion,finding,now);db.ExternalAuditFindings.Add(finding);db.AuditEvents.Add(Audit(a,"ExternalAuditFindingCreated",now,new{finding.Number,finding.Classification,capaId}));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    async Task<ExternalAuditDetailsResponse?> IExternalAuditService.AddFindingAsync(Guid id,AddExternalAuditFindingRequest r,CancellationToken ct){await EnsureActor(id,WorkflowTaskRoles.ExternalAuditCoordinator,ct);var owner=await ResolveUser(r.OwnerUserId,"Bulgu sorumlusu",ct);var result=await AddFindingAsync(id,r with{Owner=owner.DisplayName},ct);if(result is not null){var finding=result.Findings.OrderByDescending(x=>x.CreatedAtUtc).First();var entity=await db.ExternalAuditFindings.SingleAsync(x=>x.Id==finding.Id,ct);entity.AssignOwnerIdentity(owner.Id);var now=time.GetUtcNow();await Assign(id,$"ExternalAuditFinding:{finding.Id}",owner.Id,now,r.ResponseDueAtUtc.ToUniversalTime(),ct);await db.SaveChangesAsync(ct);}return result is null?null:await GetDetailsAsync(id,ct);}
    public async Task<ExternalAuditDetailsResponse?> RespondFindingAsync(Guid id,Guid findingId,RespondExternalAuditFindingRequest r,CancellationToken ct){EnsureRespond();await EnsureActor(id,$"ExternalAuditFinding:{findingId}",ct);var result=await Mutate(id,ct,(a,now)=>{a.RespondFinding(r.ExpectedVersion,findingId,r.OfficialResponse,r.Commitment,r.CommitmentDueAtUtc.ToUniversalTime(),now);return("ExternalAuditFindingResponseSubmitted",(object)new{findingId,r.CommitmentDueAtUtc},r.OfficialResponse);});if(result is not null){await CompleteTasks(id,$"ExternalAuditFinding:{findingId}",time.GetUtcNow(),ct);await db.SaveChangesAsync(ct);}return result is null?null:await GetDetailsAsync(id,ct);}
    public async Task<ExternalAuditDetailsResponse?> CloseFindingAsync(Guid id,Guid findingId,CloseExternalAuditFindingRequest r,CancellationToken ct){EnsureApprove();await EnsureActor(id,WorkflowTaskRoles.ExternalAuditAuthorizedCloser,ct);await signatures.AuthenticateAsync(r.SignaturePassword,r.SignatureMeaningAccepted,ct);var a=await Load(id,ct);if(a is null)return null;var finding=a.Findings.SingleOrDefault(x=>x.Id==findingId)??throw new ArgumentException("Bulgu bulunamadı.");var capaClosed=!finding.CapaRequired||finding.LinkedCapaId is Guid cid&&await db.Capas.AnyAsync(x=>x.Id==cid&&x.Status==CapaStatus.Closed,ct);var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);a.CloseFinding(r.ExpectedVersion,findingId,r.VerificationNote,capaClosed,now);db.ElectronicSignatures.Add(signatures.CreateInternal(a.QualityRecordId,"ExternalAudit",a.Id,a.Version,"finding-close",$"{finding.Number} dış denetim bulgusu doğrulama ve kapanış onayı",new{audit=a,finding},now,r.VerificationNote));db.AuditEvents.Add(Audit(a,"ExternalAuditFindingClosed",now,new{findingId,finding.LinkedCapaId},r.VerificationNote));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    public async Task<ExternalAuditDetailsResponse?> RecordClosureLetterAsync(Guid id,RecordExternalAuditClosureLetterRequest r,CancellationToken ct){EnsureApprove();await EnsureActor(id,WorkflowTaskRoles.ExternalAuditAuthorizedCloser,ct);await signatures.AuthenticateAsync(r.SignaturePassword,r.SignatureMeaningAccepted,ct);var a=await Load(id,ct);if(a is null)return null;var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);a.RecordClosureLetter(r.ExpectedVersion,r.Reference,r.ReceivedAtUtc.ToUniversalTime(),r.Evidence,r.Accepted,now);db.ElectronicSignatures.Add(signatures.CreateInternal(a.QualityRecordId,"ExternalAudit",a.Id,a.Version,"closure-letter","Dış denetim kapanış mektubu ve otorite kabul doğrulaması",new{audit=a,r.Reference,r.ReceivedAtUtc,r.Evidence,r.Accepted},now,r.Evidence));db.AuditEvents.Add(Audit(a,"ExternalAuditClosureLetterRecorded",now,new{r.Reference,r.Accepted},r.Evidence));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    private IQueryable<ControlledDocument> VisibleDocuments()
    {
        var documents = from document in db.ControlledDocuments.AsNoTracking()
                        join record in db.VisibleQualityRecords(user)
                            on document.QualityRecordId equals record.Id
                        select document;
        if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance)
            || user.IsInRole(QmsRoles.DocumentController)) return documents;
        return documents.Where(document => document.Confidentiality != "Confidential"
            || document.OwnerUserId == user.Id
            || db.RecordAccessGrants.Any(grant => grant.QualityRecordId == document.QualityRecordId
                && grant.UserId == user.Id));
    }
    private async Task<ApplicationUser> ResolveUser(Guid id,string field,CancellationToken ct){if(id==Guid.Empty)throw new ArgumentException($"{field} seçilmelidir.");var value=await users.Users.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.IsActive,ct);return value??throw new ArgumentException($"{field} aktif bir kullanıcı olmalıdır.");}
    private async Task Assign(Guid id,string role,Guid userId,DateTimeOffset now,DateTimeOffset? due,CancellationToken ct){var target=await(from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.Id==userId&&u.IsActive select new{u.Id,u.DisplayName,u.DepartmentId,Department=d==null?null:d.Name}).SingleOrDefaultAsync(ct)??throw new InvalidOperationException("M.08 görevi için seçilen kullanıcı etkin değil.");db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("ExternalAudit",id,role,target.Id,target.DepartmentId,now,due,assignedUserNameSnapshot:target.DisplayName,assignedDepartmentNameSnapshot:target.Department));db.UserNotifications.Add(UserNotification.Create(target.Id,"M.08","Yeni dış denetim görevi",$"{role} görevi size atandı.",$"/modules/m08?open={id}",now));}
    private async Task EnsureActor(Guid id,string role,CancellationToken ct){if(!await CanAct(id,role,ct))throw new QmsForbiddenException("Bu dış denetim görevi size veya etkin bir delegasyonla size atanmamış.");}
    private async Task<bool> CanAct(Guid id,string role,CancellationToken ct){var owners=await db.WorkflowTaskAssignments.AsNoTracking().Where(x=>x.AggregateType=="ExternalAudit"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active).Select(x=>x.AssignedUserId).ToListAsync(ct);if(owners.Contains(user.Id))return true;var now=time.GetUtcNow();return owners.Count>0&&await db.Delegations.AsNoTracking().AnyAsync(x=>owners.Contains(x.DelegatorUserId)&&x.DelegateUserId==user.Id&&x.RevokedAtUtc==null&&x.StartsAtUtc<=now&&x.EndsAtUtc>=now&&(x.Scope=="M.08"||x.Scope=="ALL"),ct);}
    private async Task<IReadOnlyList<string>> CurrentTaskRoles(Guid id,CancellationToken ct){var roles=await db.WorkflowTaskAssignments.AsNoTracking().Where(x=>x.AggregateType=="ExternalAudit"&&x.AggregateId==id&&x.Status==WorkflowTaskStatus.Active).Select(x=>x.TaskRole).Distinct().ToListAsync(ct);var result=new List<string>();foreach(var role in roles)if(await CanAct(id,role,ct))result.Add(role);return result;}
    private async Task CompleteTasks(Guid id,string role,DateTimeOffset now,CancellationToken ct){foreach(var task in await db.WorkflowTaskAssignments.Where(x=>x.AggregateType=="ExternalAudit"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active).ToListAsync(ct))task.Complete(now);}
    private async Task CompleteAllTasks(Guid id,DateTimeOffset now,CancellationToken ct){foreach(var task in await db.WorkflowTaskAssignments.Where(x=>x.AggregateType=="ExternalAudit"&&x.AggregateId==id&&x.Status==WorkflowTaskStatus.Active).ToListAsync(ct))task.Complete(now);}
    private static void EnsureLookupCategory(string category){if(category.Trim() is not ("AuditKind" or "Country" or "Confidentiality"))throw new ArgumentException("M.08 lookup kategorisi geçersizdir.");}
    private async Task RequireLookup(string category,string code,string field,CancellationToken ct){if(!await db.ExternalAuditLookupDefinitions.AsNoTracking().AnyAsync(x=>x.Category==category&&x.Code==code.Trim()&&x.IsActive,ct))throw new ArgumentException($"{field} etkin M.08 lookup kayıtlarından seçilmelidir.");}
    private static string RoleForTransition(string transition)=>transition switch{"start-preparation" or "complete-audit" or "open-response-plan"=>WorkflowTaskRoles.ExternalAuditCoordinator,"start-audit"=>WorkflowTaskRoles.DocumentPackageController,"start-capa-actions"=>WorkflowTaskRoles.ExternalAuditeeResponder,_=>WorkflowTaskRoles.ExternalAuditAuthorizedCloser};
    private async Task<ExternalAuditDetailsResponse?> Mutate(Guid id,CancellationToken ct,Func<ExternalAudit,DateTimeOffset,(string Type,object Payload,string? Reason)> action){var a=await Load(id,ct);if(a is null)return null;var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);var e=action(a,now);db.AuditEvents.Add(Audit(a,e.Type,now,e.Payload,e.Reason));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);} private Task<ExternalAudit?> Load(Guid id,CancellationToken ct)=>db.ExternalAudits.AsSplitQuery().Include(x=>x.DocumentRequests).Include(x=>x.Findings).SingleOrDefaultAsync(x=>x.Id==id&&db.VisibleQualityRecords(user).Any(record=>record.Id==x.QualityRecordId),ct);
    private void EnsureCreate(){if(user.IsInRole(QmsRoles.Administrator)||user.IsInRole(QmsRoles.QualityAssurance)||user.IsInRole(QmsRoles.DepartmentManager))return;throw new QmsForbiddenException("Dış denetim kaydı için KG veya bölüm yöneticisi rolü gerekir.");} private void EnsurePrepare(){if(user.IsInRole(QmsRoles.Administrator)||user.IsInRole(QmsRoles.QualityAssurance)||user.IsInRole(QmsRoles.DocumentController)||user.IsInRole(QmsRoles.Investigator))return;throw new QmsForbiddenException("Dış denetim hazırlığı için koordinatör/doküman kontrol yetkisi gerekir.");} private void EnsureRespond(){if(user.IsInRole(QmsRoles.Administrator)||user.IsInRole(QmsRoles.QualityAssurance)||user.IsInRole(QmsRoles.DepartmentManager)||user.IsInRole(QmsRoles.ActionOwner))return;throw new QmsForbiddenException("Resmi bulgu yanıtı için bölüm yetkisi gerekir.");} private void EnsureApprove(){if(user.IsInRole(QmsRoles.Administrator)||user.IsInRole(QmsRoles.QualityAssurance)||user.IsInRole(QmsRoles.Approver)||user.IsInRole(QmsRoles.QualifiedPerson))return;throw new QmsForbiddenException("Dış denetim doğrulaması için onaylayan rolü gerekir.");}
    private void EnsureTransition(ExternalAudit a,string transition,QualityRecord record){if(transition is "start-preparation")EnsureCreate();else if(transition is "start-audit" or "complete-audit" or "open-response-plan")EnsurePrepare();else if(transition=="start-capa-actions")EnsureRespond();else{EnsureApprove();if(transition=="close"&&a.IsGovernmentAuthority&&!user.IsInRole(QmsRoles.Administrator)&&!user.IsInRole(QmsRoles.QualifiedPerson)&&user.Id!=a.AuthorizedCloserUserId)throw new QmsForbiddenException("Devlet kurumu denetimini yalnız Mesul Müdür/atanmış yetkili kapatabilir.");if(transition=="close"&&record.CreatedByUserId==user.Id&&!user.IsInRole(QmsRoles.Administrator))throw new QmsForbiddenException("Görev ayrılığı: Kaydı oluşturan kullanıcı dış denetim kapanışını onaylayamaz.");}}
    private AuditEvent Audit(ExternalAudit a,string type,DateTimeOffset now,object payload,string? reason=null)=>AuditEvent.Create("ExternalAudit",a.Id,a.Version,type,user.Id,user.DisplayName,now,Qms.Infrastructure.Integrity.AuditCorrelation.Current,JsonSerializer.SerializeToDocument(payload),reason);
    private static IReadOnlyList<ExternalAuditTransitionResponse> Transitions(ExternalAuditStatus s)=>s switch{ExternalAuditStatus.Notified=>[new("start-preparation","Hazırlığı başlat",false)],ExternalAuditStatus.Preparation=>[new("start-audit","Denetimi başlat",false)],ExternalAuditStatus.AuditInProgress=>[new("complete-audit","Denetimi ve bulgu girişini tamamla",false)],ExternalAuditStatus.Findings=>[new("open-response-plan","Resmi cevap planını aç",false)],ExternalAuditStatus.ResponsePlan=>[new("start-capa-actions","Cevapları DÖF/aksiyona gönder",false)],ExternalAuditStatus.CapaAction=>[new("complete-capa-actions","Kapanış mektubu aşamasına geç",false)],ExternalAuditStatus.ClosureLetter=>[new("submit-authority-closure","Yetkili kapanışına gönder",false)],ExternalAuditStatus.AuthorityClosure=>[new("close","Dış denetimi kapat",true)],_=>[]};
    private static IQueryable<Row> Filter(IQueryable<Row> q,ColumnFilterRequest f){var key=f.Field.Trim().ToLowerInvariant();var value=f.Value?.Trim()??"";return key switch{"recordnumber"=>q.Where(x=>x.Number.ToLower().Contains(value.ToLower())),"title"=>q.Where(x=>x.Audit.Title.ToLower().Contains(value.ToLower())),"auditororganization"=>q.Where(x=>x.Audit.AuditorOrganization.ToLower().Contains(value.ToLower())),"auditkind"=>q.Where(x=>x.Audit.AuditKind.ToLower().Contains(value.ToLower())),"authoritycountry"=>q.Where(x=>x.Audit.AuthorityCountry.ToLower().Contains(value.ToLower())),"owner"=>q.Where(x=>x.Audit.Owner.ToLower().Contains(value.ToLower())),"status"=>Enum.TryParse<ExternalAuditStatus>(value,true,out var s)?q.Where(x=>x.Audit.Status==s):throw new ArgumentException("Durum geçersizdir."),"isgovernmentauthority"=>bool.TryParse(value,out var b)?q.Where(x=>x.Audit.IsGovernmentAuthority==b):throw new ArgumentException("Kurum türü filtresi geçersizdir."),"plannedstartutc"=>Date(q,f.Operator,f.Value,f.ValueTo),_=>throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}")};} private static IQueryable<Row> Date(IQueryable<Row> q,string op,string? a,string? b){var from=DateTimeOffset.Parse(a??"",CultureInfo.InvariantCulture).ToUniversalTime();var to=string.IsNullOrWhiteSpace(b)?from.AddDays(1):DateTimeOffset.Parse(b,CultureInfo.InvariantCulture).ToUniversalTime();return op switch{"before"=>q.Where(x=>x.Audit.PlannedStartUtc<from),"after"=>q.Where(x=>x.Audit.PlannedStartUtc>from),_=>q.Where(x=>x.Audit.PlannedStartUtc>=from&&x.Audit.PlannedStartUtc<to)};} private static IQueryable<Row> Sort(IQueryable<Row> q,string f,string d){var desc=d.Equals("desc",StringComparison.OrdinalIgnoreCase);return f.ToLowerInvariant()switch{"recordnumber"=>desc?q.OrderByDescending(x=>x.Number):q.OrderBy(x=>x.Number),"title"=>desc?q.OrderByDescending(x=>x.Audit.Title):q.OrderBy(x=>x.Audit.Title),"plannedstartutc"=>desc?q.OrderByDescending(x=>x.Audit.PlannedStartUtc):q.OrderBy(x=>x.Audit.PlannedStartUtc),"status"=>desc?q.OrderByDescending(x=>x.Audit.Status):q.OrderBy(x=>x.Audit.Status),_=>desc?q.OrderByDescending(x=>x.Audit.CreatedAtUtc):q.OrderBy(x=>x.Audit.CreatedAtUtc)};}
    private async Task<long> Next(string type,int year,IDbContextTransaction tx,CancellationToken ct){var connection=db.Database.GetDbConnection();if(connection.State!=ConnectionState.Open)await connection.OpenAsync(ct);await using var command=connection.CreateCommand();command.Transaction=tx.GetDbTransaction();command.CommandText="INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@type,@year,1) ON CONFLICT (\"RecordType\",\"CalendarYear\") DO UPDATE SET \"LastValue\"=core.record_number_sequence.\"LastValue\"+1 RETURNING \"LastValue\";";Add(command,"type",type);Add(command,"year",year);return Convert.ToInt64(await command.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);} private static void Add(DbCommand c,string name,object value){var p=c.CreateParameter();p.ParameterName=name;p.Value=value;c.Parameters.Add(p);} private sealed class Row{public required ExternalAudit Audit{get;init;}public required string Number{get;init;}}
}
