import type { ColumnFilter, PagedResponse } from './deviations'
import { qmsFetch } from './http'

export type CapaStatus = 'Draft' | 'ScopeApproval' | 'RootCauseApproval' | 'ActionPlanning' | 'PlanApproval' | 'Implementation' | 'ActionVerification' | 'EffectivenessWaiting' | 'EffectivenessReview' | 'ClosureApproval' | 'Closed' | 'Voided'
export interface CapaListItem { id: string; recordNumber: string; sourceDeviationId: string | null; sourceRecordNumber: string | null; sourceType: string; title: string; owner: string; targetDateUtc: string; status: CapaStatus; actionCount: number; verifiedActionCount: number; createdAtUtc: string; version: number }
export interface CapaUserOption { id: string; displayName: string; departmentName: string | null }
export interface CapaLookups { owners: CapaUserOption[]; effectivenessEvaluators: CapaUserOption[]; sourceTypes: string[]; actionTypes: string[] }
export interface CreateCapaInput { sourceDeviationId?: string | null; sourceType: string; title: string; description: string; rootCause: string; immediateActions: string; ownerUserId: string; targetDateUtc: string; effectivenessRequired: boolean; effectivenessMethod?: string; effectivenessSample?: string; observationPeriodDays?: number; successCriteria?: string; effectivenessEvaluatorUserId?: string | null }
export interface CapaRecord extends CapaListItem { qualityRecordId: string; description: string; rootCause: string; immediateActions: string; ownerUserId: string | null; effectivenessRequired: boolean; effectivenessMethod: string; effectivenessSample: string; observationPeriodDays: number; successCriteria: string; effectivenessEvaluatorUserId: string | null; effectivenessEvaluator: string; effectivenessDueDateUtc: string | null; isEffective: boolean | null; effectivenessResult: string | null; closureNote: string | null; updatedAtUtc: string; closedAtUtc: string | null }
export interface CapaAction { id: string; actionType: string; description: string; ownerUserId: string | null; owner: string; targetDateUtc: string; status: 'Planned' | 'CompletionRequested' | 'Verified' | 'Rejected'; completionEvidence: string | null; verificationNote: string | null; completedAtUtc: string | null; verifiedAtUtc: string | null }
export interface CapaDetails { record: CapaRecord; actions: CapaAction[]; auditTrail: Array<{ id: string; version: number; eventType: string; actor: string; occurredAtUtc: string; reason: string | null; payload?: Record<string, unknown> }>; signatures: Array<{ id: string; recordVersion: number; signerUserId: string; signerName: string; meaning: string; signedAtUtc: string; contentHash: string; comment: string | null }>; availableTransitions: Array<{ code: string; label: string; noteRequired: boolean }> }

export async function searchCapas(input: { page: number; pageSize: 10 | 25 | 50 | 100; sortBy: string; sortDirection: 'asc' | 'desc'; filters: ColumnFilter[] }, signal?: AbortSignal): Promise<PagedResponse<CapaListItem>> { return request('/api/v1/capas/search', { method: 'POST', headers: json, body: JSON.stringify(input), signal }) }
export async function getCapaLookups(signal?: AbortSignal): Promise<CapaLookups> { return request('/api/v1/capas/lookups', { signal }) }
export async function createCapa(input: CreateCapaInput): Promise<CapaDetails> { return request(input.sourceDeviationId ? `/api/v1/deviations/${input.sourceDeviationId}/capa` : '/api/v1/capas', { method: 'POST', headers: json, body: JSON.stringify(input) }) }
export async function getCapaDetails(id: string, signal?: AbortSignal): Promise<CapaDetails> { return request(`/api/v1/capas/${id}/details`, { signal }) }
export async function downloadCapaFinalReport(id: string): Promise<{ blob: Blob; fileName: string; sha256: string | null }> { const response = await qmsFetch(`/api/v1/capas/${id}/final-report`); if (!response.ok) { const p = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(p?.detail ?? `Rapor alınamadı (${response.status})`) } const disposition = response.headers.get('content-disposition') ?? ''; const encoded = /filename\*=UTF-8''([^;]+)/i.exec(disposition)?.[1]; const plain = /filename="?([^";]+)"?/i.exec(disposition)?.[1]; return { blob: await response.blob(), fileName: encoded ? decodeURIComponent(encoded) : plain ?? 'dof-nihai-kayit.pdf', sha256: response.headers.get('x-content-sha256') } }
export async function addCapaAction(id: string, input: { expectedVersion: number; actionType: string; description: string; ownerUserId: string; targetDateUtc: string }): Promise<CapaDetails> { return request(`/api/v1/capas/${id}/actions`, { method: 'POST', headers: json, body: JSON.stringify(input) }) }
export async function completeCapaAction(id: string, actionId: string, expectedVersion: number, evidence: string): Promise<CapaDetails> { return request(`/api/v1/capas/${id}/actions/${actionId}/complete`, { method: 'POST', headers: json, body: JSON.stringify({ expectedVersion, evidence }) }) }
export async function verifyCapaAction(id: string, actionId: string, expectedVersion: number, approved: boolean, note: string): Promise<CapaDetails> { return request(`/api/v1/capas/${id}/actions/${actionId}/verify`, { method: 'POST', headers: json, body: JSON.stringify({ expectedVersion, approved, note }) }) }
export async function transitionCapa(id: string, expectedVersion: number, transition: string, note?: string, isEffective = false, signaturePassword?: string, signatureMeaningAccepted = false): Promise<CapaDetails> { return request(`/api/v1/capas/${id}/transitions`, { method: 'POST', headers: json, body: JSON.stringify({ expectedVersion, transition, note, isEffective, signaturePassword, signatureMeaningAccepted }) }) }
const json = { 'Content-Type': 'application/json' }
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await qmsFetch(url, init); if (!response.ok) { const problem = await response.json().catch(() => null) as { detail?: string; title?: string } | null; throw new Error(problem?.detail ?? problem?.title ?? `İstek başarısız (${response.status})`) } return response.json() as Promise<T> }
