using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Qms.Application.InternalAudits;
using Qms.Application.Security;
using Qms.Contracts.Common;
using Qms.Contracts.InternalAudits;
using Qms.Domain.AuditTrail;
using Qms.Domain.Capas;
using Qms.Domain.InternalAudits;
using Qms.Domain.QualityRecords;
using Qms.Domain.Workflows;
using Qms.Infrastructure.Persistence;
namespace Qms.Infrastructure.InternalAudits;

public sealed class InternalAuditService(QmsDbContext db, TimeProvider time, ICurrentUser user) : IInternalAuditService
{
    private static readonly Guid DefaultDepartment = Guid.Parse("01991f70-6f40-7000-8000-000000000002");
    public async Task<PagedResponse<InternalAuditListItemResponse>> SearchAsync(InternalAuditSearchRequest r, CancellationToken ct) { if (r.Page < 1 || r.PageSize is not (10 or 25 or 50 or 100)) throw new ArgumentException("Sayfa bilgisi geçersizdir."); var q = from a in db.InternalAudits.AsNoTracking() join qr in db.QualityRecords.AsNoTracking() on a.QualityRecordId equals qr.Id select new Row { Audit = a, Number = qr.RecordNumber }; foreach (var f in r.Filters ?? []) q = Filter(q, f); var total = await q.LongCountAsync(ct); q = Sort(q, r.SortBy, r.SortDirection); var items = await q.Skip((r.Page - 1) * r.PageSize).Take(r.PageSize).Select(x => new InternalAuditListItemResponse(x.Audit.Id, x.Number, x.Audit.PlanYear, x.Audit.Title, x.Audit.AuditType, x.Audit.AuditeeDepartment, x.Audit.LeadAuditor, x.Audit.PlannedStartUtc, x.Audit.PlannedEndUtc, x.Audit.IsUnplanned, x.Audit.Status.ToString(), x.Audit.Findings.Count, x.Audit.Findings.Count(f => f.Status != AuditFindingStatus.Closed), x.Audit.CreatedAtUtc, x.Audit.Version)).ToListAsync(ct); return new(items, r.Page, r.PageSize, total, total == 0 ? 0 : (int)Math.Ceiling(total / (double)r.PageSize)); }
    public async Task<InternalAuditDetailsResponse?> GetDetailsAsync(Guid id, CancellationToken ct) { var a = await db.InternalAudits.AsNoTracking().AsSplitQuery().Include(x => x.Checklist).Include(x => x.Findings).SingleOrDefaultAsync(x => x.Id == id, ct); if (a is null) return null; var number = await db.QualityRecords.Where(x => x.Id == a.QualityRecordId).Select(x => x.RecordNumber).SingleAsync(ct); var capaIds = a.Findings.Where(x => x.LinkedCapaId.HasValue).Select(x => x.LinkedCapaId!.Value).ToArray(); var capaNumbers = await (from c in db.Capas.AsNoTracking() join qr in db.QualityRecords.AsNoTracking() on c.QualityRecordId equals qr.Id where capaIds.Contains(c.Id) select new { c.Id, qr.RecordNumber }).ToDictionaryAsync(x => x.Id, x => x.RecordNumber, ct); var events = await db.AuditEvents.AsNoTracking().Where(x => x.AggregateType == "InternalAudit" && x.AggregateId == id).OrderByDescending(x => x.OccurredAtUtc).ToListAsync(ct); var record = new InternalAuditRecordResponse(a.Id, a.QualityRecordId, number, a.PlanYear, a.Title, a.AuditType, a.Scope, a.Objectives, a.Criteria, a.AuditeeDepartment, a.LeadAuditorUserId, a.LeadAuditor, a.LeadAuditorDepartment, a.PlannedStartUtc, a.PlannedEndUtc, a.IsUnplanned, a.UnplannedReason, a.ChecklistVersion, a.ChecklistLockedAtUtc, a.IndependenceConfirmed, a.Summary, a.Status.ToString(), a.CreatedAtUtc, a.UpdatedAtUtc, a.ClosedAtUtc, a.Version); return new(record, a.Checklist.OrderBy(x => x.Order).Select(x => new AuditChecklistItemResponse(x.Id, x.Order, x.Question, x.Reference, x.Status.ToString(), x.Evidence, x.Note, x.AnsweredAtUtc)).ToList(), a.Findings.OrderBy(x => x.Number).Select(x => new AuditFindingResponse(x.Id, x.Number, x.Title, x.Description, x.RequirementReference, x.Impact, x.Likelihood, x.RiskScore, x.Classification.ToString(), x.CapaRequired, x.LinkedCapaId, x.LinkedCapaId is Guid cid ? capaNumbers.GetValueOrDefault(cid) : null, x.Owner, x.TargetDateUtc, x.Response, x.CorrectiveAction, x.VerificationNote, x.Status.ToString(), x.CreatedAtUtc, x.ClosedAtUtc)).ToList(), events.Select(x => new InternalAuditEventResponse(x.Id, x.AggregateVersion, x.EventType, x.ActorDisplayNameSnapshot, x.OccurredAtUtc, x.Reason, x.Payload.RootElement.Clone())).ToList(), Transitions(a.Status)); }
    public async Task<InternalAuditDetailsResponse> CreateAsync(CreateInternalAuditRequest r, CancellationToken ct) { EnsurePlan(); var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var num = $"İD-{now.Year}-{await Next("internal-audit", now.Year, tx, ct):000000}"; var qr = QualityRecord.Create(num, "internal-audit", user.Id, user.DepartmentId ?? DefaultDepartment, now); var a = InternalAudit.Create(qr.Id, r.PlanYear, r.Title, r.AuditType, r.Scope, r.Objectives, r.Criteria, r.AuditeeDepartment, r.LeadAuditorUserId, r.LeadAuditor, r.LeadAuditorDepartment, r.PlannedStartUtc.ToUniversalTime(), r.PlannedEndUtc.ToUniversalTime(), r.IsUnplanned, r.UnplannedReason, r.ChecklistVersion, r.Questions.Select(x => (x.Question, x.Reference)), now); var auditorDepartmentId = await db.Departments.Where(x => x.IsActive && x.Name == r.LeadAuditorDepartment).Select(x => (Guid?)x.Id).FirstOrDefaultAsync(ct); var auditee = await db.Departments.Where(x => x.IsActive && x.Name == r.AuditeeDepartment).Select(x => new { x.Id, x.ManagerUserId }).FirstOrDefaultAsync(ct); var responderId = auditee?.ManagerUserId; if (!responderId.HasValue && auditee is not null) responderId = await db.Users.Where(x => x.IsActive && x.DepartmentId == auditee.Id).Select(x => (Guid?)x.Id).FirstOrDefaultAsync(ct); db.QualityRecords.Add(qr); db.InternalAudits.Add(a); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("InternalAudit", a.Id, WorkflowTaskRoles.AuditPlanner, user.Id, user.DepartmentId, now, a.PlannedStartUtc)); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("InternalAudit", a.Id, WorkflowTaskRoles.LeadAuditor, r.LeadAuditorUserId, auditorDepartmentId, now, a.PlannedEndUtc)); if (responderId.HasValue) db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("InternalAudit", a.Id, WorkflowTaskRoles.AuditeeResponder, responderId.Value, auditee!.Id, now, a.PlannedEndUtc)); db.AuditEvents.Add(Audit(a, "InternalAuditCreated", now, new { num, r.IsUnplanned, r.ChecklistVersion })); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return (await GetDetailsAsync(a.Id, ct))!; }
    public async Task<InternalAuditDetailsResponse?> TransitionAsync(Guid id, TransitionInternalAuditRequest r, CancellationToken ct) { var a = await Load(id, ct); if (a is null) return null; var qr = await db.QualityRecords.SingleAsync(x => x.Id == a.QualityRecordId, ct); var now = time.GetUtcNow(); var from = a.Status; EnsureTransition(r.Transition); await using var tx = await db.Database.BeginTransactionAsync(ct); a.Transition(r.ExpectedVersion, r.Transition, r.Note, now); if (r.Transition == "prepare") qr.Submit(now); if (r.Transition == "close") qr.Close(now, false); db.AuditEvents.Add(Audit(a, "InternalAuditStatusChanged", now, new { from = from.ToString(), to = a.Status.ToString(), transition = r.Transition }, r.Note)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    public Task<InternalAuditDetailsResponse?> AnswerAsync(Guid id, Guid itemId, AnswerAuditQuestionRequest r, CancellationToken ct) => Mutate(id, ct, (a, now) => { EnsureExecute(); if (!Enum.TryParse<AuditAnswerStatus>(r.Status, true, out var status)) throw new ArgumentException("Soru sonucu geçersizdir."); a.Answer(r.ExpectedVersion, itemId, status, r.Evidence, r.Note, now); return ("AuditQuestionAnswered", (object)new { itemId, status }, r.Note); });
    public async Task<InternalAuditDetailsResponse?> AddFindingAsync(Guid id, AddAuditFindingRequest r, CancellationToken ct) { EnsureExecute(); var a = await Load(id, ct); if (a is null) return null; var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var score = r.Impact * r.Likelihood; var needsCapa = r.CapaRequired || score >= 12; Guid? capaId = null; if (needsCapa) { var cnum = $"DÖF-{now.Year}-{await Next("capa", now.Year, tx, ct):000000}"; var qr = QualityRecord.Create(cnum, "capa", user.Id, user.DepartmentId ?? DefaultDepartment, now); var capa = Capa.Create(qr.Id, null, "InternalAudit", r.Title, r.Description, $"İç denetim bulgusu: {r.RequirementReference}", "Bulguyu kontrol altına alma", r.Owner, r.TargetDateUtc.ToUniversalTime(), true, "İç denetim tekrar doğrulaması", "Bulgu kapsamı", 30, "Aynı uygunsuzluğun tekrar etmemesi", "Kalite Güvence", now); db.QualityRecords.Add(qr); db.Capas.Add(capa); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Capa", capa.Id, WorkflowTaskRoles.Initiator, user.Id, user.DepartmentId, now, capa.TargetDateUtc)); capaId = capa.Id; db.AuditEvents.Add(AuditEvent.Create("Capa", capa.Id, capa.Version, "CapaCreatedFromInternalAuditFinding", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { auditId = a.Id }))); } var fnum = $"BLG-{now.Year}-{await Next("audit-finding", now.Year, tx, ct):000000}"; var finding = AuditFinding.Create(a.Id, fnum, r.Title, r.Description, r.RequirementReference, r.Impact, r.Likelihood, needsCapa, capaId, r.Owner, r.TargetDateUtc.ToUniversalTime(), now); a.AddFinding(r.ExpectedVersion, finding, now); db.AuditFindings.Add(finding); db.AuditEvents.Add(Audit(a, "AuditFindingCreated", now, new { finding.Number, finding.Classification, finding.RiskScore, capaId })); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    public Task<InternalAuditDetailsResponse?> RespondFindingAsync(Guid id, Guid findingId, RespondAuditFindingRequest r, CancellationToken ct) => Mutate(id, ct, (a, now) => { EnsureRespond(); a.RespondFinding(r.ExpectedVersion, findingId, r.Response, r.CorrectiveAction, now); return ("AuditFindingResponseSubmitted", (object)new { findingId }, r.Response); });
    public async Task<InternalAuditDetailsResponse?> CloseFindingAsync(Guid id, Guid findingId, CloseAuditFindingRequest r, CancellationToken ct) { EnsureApprove(); var a = await Load(id, ct); if (a is null) return null; var finding = a.Findings.SingleOrDefault(x => x.Id == findingId) ?? throw new ArgumentException("Bulgu bulunamadı."); var capaClosed = !finding.CapaRequired || finding.LinkedCapaId is Guid cid && await db.Capas.AnyAsync(x => x.Id == cid && x.Status == CapaStatus.Closed, ct); var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); a.CloseFinding(r.ExpectedVersion, findingId, r.VerificationNote, capaClosed, now); db.AuditEvents.Add(Audit(a, "AuditFindingClosed", now, new { findingId, finding.LinkedCapaId }, r.VerificationNote)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    private async Task<InternalAuditDetailsResponse?> Mutate(Guid id, CancellationToken ct, Func<InternalAudit, DateTimeOffset, (string Type, object Payload, string? Reason)> fn) { var a = await Load(id, ct); if (a is null) return null; var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var e = fn(a, now); db.AuditEvents.Add(Audit(a, e.Type, now, e.Payload, e.Reason)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    private Task<InternalAudit?> Load(Guid id, CancellationToken ct) => db.InternalAudits.AsSplitQuery().Include(x => x.Checklist).Include(x => x.Findings).SingleOrDefaultAsync(x => x.Id == id, ct);
    private void EnsurePlan() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance)) return; throw new QmsForbiddenException("Denetim planlama için KG rolü gerekir."); }
    private void EnsureExecute() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.Investigator)) return; throw new QmsForbiddenException("Denetim uygulaması için denetçi rolü gerekir."); }
    private void EnsureRespond() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.DepartmentManager) || user.IsInRole(QmsRoles.ActionOwner)) return; throw new QmsForbiddenException("Bulgu yanıtı için bölüm yetkisi gerekir."); }
    private void EnsureApprove() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.Approver)) return; throw new QmsForbiddenException("Denetim onayı için onaylayan rolü gerekir."); }
    private void EnsureTransition(string t) { if (t is "prepare" or "submit-plan") EnsurePlan(); else if (t == "complete-responses") EnsureRespond(); else if (t is "approve-plan" or "start-finding-closure" or "request-audit-closure" or "close") EnsureApprove(); else EnsureExecute(); }
    private AuditEvent Audit(InternalAudit a, string type, DateTimeOffset now, object payload, string? reason = null) => AuditEvent.Create("InternalAudit", a.Id, a.Version, type, user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(payload), reason); private static IReadOnlyList<InternalAuditTransitionResponse> Transitions(InternalAuditStatus s) => s switch { InternalAuditStatus.AnnualPlan => [new("prepare", "Hazırlığı başlat", false)], InternalAuditStatus.Preparation => [new("submit-plan", "Plan onayına gönder", false)], InternalAuditStatus.PlanApproval => [new("approve-plan", "Planı ve soru listesini kilitle", false)], InternalAuditStatus.Execution => [new("complete-execution", "Uygulamayı tamamla", false)], InternalAuditStatus.Findings => [new("confirm-findings", "Bulguları kesinleştir", false)], InternalAuditStatus.ResponseAction => [new("complete-responses", "Yanıtları doğrulamaya gönder", false)], InternalAuditStatus.CapaVerification => [new("start-finding-closure", "Bulgu kapanışını başlat", false)], InternalAuditStatus.FindingClosure => [new("request-audit-closure", "Denetim kapanışına gönder", false)], InternalAuditStatus.AuditClosure => [new("close", "Denetimi kapat", true)], _ => [] };
    private static IQueryable<Row> Filter(IQueryable<Row> q, ColumnFilterRequest f) { var k = f.Field.Trim().ToLowerInvariant(); var v = f.Value?.Trim() ?? ""; return k switch { "recordnumber" => q.Where(x => x.Number.ToLower().Contains(v.ToLower())), "title" => q.Where(x => x.Audit.Title.ToLower().Contains(v.ToLower())), "audittype" => q.Where(x => x.Audit.AuditType.ToLower().Contains(v.ToLower())), "auditeedepartment" => q.Where(x => x.Audit.AuditeeDepartment.ToLower().Contains(v.ToLower())), "leadauditor" => q.Where(x => x.Audit.LeadAuditor.ToLower().Contains(v.ToLower())), "status" => Enum.TryParse<InternalAuditStatus>(v, true, out var s) ? q.Where(x => x.Audit.Status == s) : throw new ArgumentException("Durum geçersizdir."), "isunplanned" => bool.TryParse(v, out var b) ? q.Where(x => x.Audit.IsUnplanned == b) : throw new ArgumentException("Plansız filtresi geçersizdir."), "planyear" => int.TryParse(v, out var y) ? q.Where(x => x.Audit.PlanYear == y) : throw new ArgumentException("Plan yılı geçersizdir."), "plannedstartutc" => Date(q, f.Operator, f.Value, f.ValueTo), _ => throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}") }; }
    private static IQueryable<Row> Date(IQueryable<Row> q, string op, string? a, string? b) { var from = DateTimeOffset.Parse(a ?? "", CultureInfo.InvariantCulture).ToUniversalTime(); var to = string.IsNullOrWhiteSpace(b) ? from.AddDays(1) : DateTimeOffset.Parse(b, CultureInfo.InvariantCulture).ToUniversalTime(); return op switch { "before" => q.Where(x => x.Audit.PlannedStartUtc < from), "after" => q.Where(x => x.Audit.PlannedStartUtc > from), _ => q.Where(x => x.Audit.PlannedStartUtc >= from && x.Audit.PlannedStartUtc < to) }; }
    private static IQueryable<Row> Sort(IQueryable<Row> q, string f, string d) { var x = d.Equals("desc", StringComparison.OrdinalIgnoreCase); return f.ToLowerInvariant() switch { "recordnumber" => x ? q.OrderByDescending(z => z.Number) : q.OrderBy(z => z.Number), "title" => x ? q.OrderByDescending(z => z.Audit.Title) : q.OrderBy(z => z.Audit.Title), "plannedstartutc" => x ? q.OrderByDescending(z => z.Audit.PlannedStartUtc) : q.OrderBy(z => z.Audit.PlannedStartUtc), "status" => x ? q.OrderByDescending(z => z.Audit.Status) : q.OrderBy(z => z.Audit.Status), _ => x ? q.OrderByDescending(z => z.Audit.CreatedAtUtc) : q.OrderBy(z => z.Audit.CreatedAtUtc) }; }
    private async Task<long> Next(string type, int year, IDbContextTransaction tx, CancellationToken ct) { var c = db.Database.GetDbConnection(); if (c.State != ConnectionState.Open) await c.OpenAsync(ct); await using var cmd = c.CreateCommand(); cmd.Transaction = tx.GetDbTransaction(); cmd.CommandText = "INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@type,@year,1) ON CONFLICT (\"RecordType\",\"CalendarYear\") DO UPDATE SET \"LastValue\"=core.record_number_sequence.\"LastValue\"+1 RETURNING \"LastValue\";"; Add(cmd, "type", type); Add(cmd, "year", year); return Convert.ToInt64(await cmd.ExecuteScalarAsync(ct), CultureInfo.InvariantCulture); }
    private static void Add(DbCommand c, string n, object v) { var p = c.CreateParameter(); p.ParameterName = n; p.Value = v; c.Parameters.Add(p); }
    private sealed class Row { public required InternalAudit Audit { get; init; } public required string Number { get; init; } }
}
