using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Qms.Application.InternalAudits;
using Qms.Application.Security;
using Qms.Contracts.Common;
using Qms.Contracts.InternalAudits;
using Qms.Domain.AuditTrail;
using Qms.Domain.Capas;
using Qms.Domain.ElectronicSignatures;
using Qms.Domain.InternalAudits;
using Qms.Domain.Notifications;
using Qms.Domain.QualityRecords;
using Qms.Domain.Workflows;
using Qms.Infrastructure.Persistence;
using Qms.Infrastructure.Identity;
namespace Qms.Infrastructure.InternalAudits;

public sealed class InternalAuditService(QmsDbContext db, TimeProvider time, ICurrentUser user, UserManager<ApplicationUser> userManager) : IInternalAuditService,IInternalAuditLookupService
{
    private static readonly Guid DefaultDepartment = Guid.Parse("01991f70-6f40-7000-8000-000000000002");
    public async Task<PagedResponse<InternalAuditListItemResponse>> SearchAsync(InternalAuditSearchRequest r, CancellationToken ct) { if (r.Page < 1 || r.PageSize is not (10 or 25 or 50 or 100)) throw new ArgumentException("Sayfa bilgisi geçersizdir."); var q = from a in db.InternalAudits.AsNoTracking() join qr in db.QualityRecords.AsNoTracking() on a.QualityRecordId equals qr.Id select new Row { Audit = a, Number = qr.RecordNumber }; foreach (var f in r.Filters ?? []) q = Filter(q, f); var total = await q.LongCountAsync(ct); q = Sort(q, r.SortBy, r.SortDirection); var items = await q.Skip((r.Page - 1) * r.PageSize).Take(r.PageSize).Select(x => new InternalAuditListItemResponse(x.Audit.Id, x.Number, x.Audit.PlanYear, x.Audit.Title, x.Audit.AuditType, x.Audit.AuditeeDepartment, x.Audit.LeadAuditor, x.Audit.PlannedStartUtc, x.Audit.PlannedEndUtc, x.Audit.IsUnplanned, x.Audit.Status.ToString(), x.Audit.Findings.Count, x.Audit.Findings.Count(f => f.Status != AuditFindingStatus.Closed), x.Audit.CreatedAtUtc, x.Audit.Version)).ToListAsync(ct); return new(items, r.Page, r.PageSize, total, total == 0 ? 0 : (int)Math.Ceiling(total / (double)r.PageSize)); }
    public async Task<InternalAuditOptionsResponse> GetOptionsAsync(CancellationToken ct) { var departments=await db.Departments.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new InternalAuditOption(x.Id,x.Name,null)).ToListAsync(ct);var users=await(from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.IsActive orderby u.DisplayName select new InternalAuditOption(u.Id,u.DisplayName,d==null?null:d.Name)).ToListAsync(ct);var types=await db.InternalAuditLookupDefinitions.AsNoTracking().Where(x=>x.Category=="AuditType"&&x.IsActive).OrderBy(x=>x.SortOrder).Select(x=>new InternalAuditCodeOption(x.Code,x.Name)).ToListAsync(ct);return new(departments,users,users,types); }
    public async Task<IReadOnlyList<InternalAuditLookupDefinitionResponse>>ListAsync(CancellationToken ct)=>await db.InternalAuditLookupDefinitions.AsNoTracking().OrderBy(x=>x.Category).ThenBy(x=>x.SortOrder).Select(x=>new InternalAuditLookupDefinitionResponse(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive)).ToListAsync(ct);
    public async Task<InternalAuditLookupDefinitionResponse>CreateAsync(CreateInternalAuditLookupDefinitionRequest r,CancellationToken ct){if(r.Category!="AuditType")throw new ArgumentException("M.07 lookup kategorisi geçersizdir.");if(await db.InternalAuditLookupDefinitions.AnyAsync(x=>x.Category==r.Category&&x.Code==r.Code.Trim(),ct))throw new InvalidOperationException("Aynı M.07 lookup kodu zaten mevcut.");var now=time.GetUtcNow();var x=InternalAuditLookupDefinition.Create(r.Category,r.Code,r.Name,r.SortOrder,now);db.InternalAuditLookupDefinitions.Add(x);db.AuditEvents.Add(AuditEvent.Create("InternalAuditLookupDefinition",x.Id,1,"InternalAuditLookupCreated",user.Id,user.DisplayName,now,Guid.CreateVersion7().ToString(),JsonSerializer.SerializeToDocument(new{x.Category,x.Code,x.Name,x.SortOrder})));await db.SaveChangesAsync(ct);return new(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive);}
    public async Task<InternalAuditLookupDefinitionResponse?>UpdateAsync(Guid id,UpdateInternalAuditLookupDefinitionRequest r,CancellationToken ct){var x=await db.InternalAuditLookupDefinitions.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return null;var now=time.GetUtcNow();x.Update(r.Name,r.SortOrder,r.IsActive,now);db.AuditEvents.Add(AuditEvent.Create("InternalAuditLookupDefinition",x.Id,1,"InternalAuditLookupUpdated",user.Id,user.DisplayName,now,Guid.CreateVersion7().ToString(),JsonSerializer.SerializeToDocument(new{x.Category,x.Code,x.Name,x.SortOrder,x.IsActive})));await db.SaveChangesAsync(ct);return new(x.Id,x.Category,x.Code,x.Name,x.SortOrder,x.IsActive);}
    async Task<InternalAuditDetailsResponse>IInternalAuditService.CreateAsync(CreateInternalAuditRequest r,CancellationToken ct){if(!await db.InternalAuditLookupDefinitions.AsNoTracking().AnyAsync(x=>x.Category=="AuditType"&&x.Code==r.AuditType&&x.IsActive,ct))throw new ArgumentException("Seçilen denetim türü etkin M.07 lookup kayıtlarında bulunamadı.");return await CreateAsync(r,ct);}
    public async Task<InternalAuditDetailsResponse?> GetDetailsAsync(Guid id, CancellationToken ct) {
        var a=await db.InternalAudits.AsNoTracking().AsSplitQuery().Include(x=>x.Checklist).Include(x=>x.Findings).SingleOrDefaultAsync(x=>x.Id==id,ct);if(a is null)return null;
        var number=await db.QualityRecords.Where(x=>x.Id==a.QualityRecordId).Select(x=>x.RecordNumber).SingleAsync(ct);var capaIds=a.Findings.Where(x=>x.LinkedCapaId.HasValue).Select(x=>x.LinkedCapaId!.Value).ToArray();var capaNumbers=await(from c in db.Capas.AsNoTracking() join qr in db.QualityRecords.AsNoTracking() on c.QualityRecordId equals qr.Id where capaIds.Contains(c.Id) select new{c.Id,qr.RecordNumber}).ToDictionaryAsync(x=>x.Id,x=>x.RecordNumber,ct);
        var events=await db.AuditEvents.AsNoTracking().Where(x=>x.AggregateType=="InternalAudit"&&x.AggregateId==id).OrderByDescending(x=>x.OccurredAtUtc).ToListAsync(ct);var signatures=await db.ElectronicSignatures.AsNoTracking().Where(x=>x.QualityRecordId==a.QualityRecordId).OrderBy(x=>x.SignedAtUtc).Select(x=>new InternalAuditSignatureResponse(x.Id,x.RecordVersion,x.SignerUserId,x.SignerDisplayNameSnapshot,x.Meaning,x.SignedAtUtc,x.ContentHash,x.Comment)).ToListAsync(ct);
        var record=new InternalAuditRecordResponse(a.Id,a.QualityRecordId,number,a.PlanYear,a.Title,a.AuditType,a.Scope,a.Objectives,a.Criteria,a.AuditeeDepartmentId,a.AuditeeDepartment,a.LeadAuditorUserId,a.LeadAuditor,a.LeadAuditorDepartment,a.PlannedStartUtc,a.PlannedEndUtc,a.IsUnplanned,a.UnplannedReason,a.ChecklistVersion,a.ChecklistLockedAtUtc,a.IndependenceConfirmed,a.Summary,a.Status.ToString(),a.CreatedAtUtc,a.UpdatedAtUtc,a.ClosedAtUtc,a.Version);
        var roles=await CurrentTaskRoles(id,ct);return new(record,a.Checklist.OrderBy(x=>x.Order).Select(x=>new AuditChecklistItemResponse(x.Id,x.Order,x.Question,x.Reference,x.Status.ToString(),x.Evidence,x.Note,x.AnsweredAtUtc)).ToList(),a.Findings.OrderBy(x=>x.Number).Select(x=>new AuditFindingResponse(x.Id,x.Number,x.Title,x.Description,x.RequirementReference,x.Impact,x.Likelihood,x.RiskScore,x.Classification.ToString(),x.CapaRequired,x.LinkedCapaId,x.LinkedCapaId is Guid cid?capaNumbers.GetValueOrDefault(cid):null,x.OwnerUserId,x.Owner,x.TargetDateUtc,x.Response,x.CorrectiveAction,x.VerificationNote,x.Status.ToString(),x.CreatedAtUtc,x.ClosedAtUtc)).ToList(),events.Select(x=>new InternalAuditEventResponse(x.Id,x.AggregateVersion,x.EventType,x.ActorDisplayNameSnapshot,x.OccurredAtUtc,x.Reason,x.Payload.RootElement.Clone())).ToList(),signatures,Transitions(a.Status).Where(x=>roles.Contains(x.Code switch{"prepare" or "submit-plan"=>WorkflowTaskRoles.AuditPlanner,"approve-plan" or "start-finding-closure" or "request-audit-closure" or "close"=>WorkflowTaskRoles.Approver,"complete-responses"=>WorkflowTaskRoles.AuditeeResponder,_=>WorkflowTaskRoles.LeadAuditor})).ToList(),roles);
    }
    public async Task<InternalAuditDetailsResponse> CreateAsync(CreateInternalAuditRequest r,CancellationToken ct){EnsurePlan();var now=time.GetUtcNow();var auditee=await db.Departments.AsNoTracking().Where(x=>x.Id==r.AuditeeDepartmentId&&x.IsActive).Select(x=>new{x.Id,x.Name,x.ManagerUserId}).SingleOrDefaultAsync(ct)??throw new ArgumentException("Seçilen denetlenen bölüm etkin değil.");var auditor=await(from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id where u.Id==r.LeadAuditorUserId&&u.IsActive select new{u.Id,u.DisplayName,u.DepartmentId,Department=d.Name}).SingleOrDefaultAsync(ct)??throw new ArgumentException("Seçilen baş denetçi etkin bir kullanıcı ve bölüme bağlı olmalıdır.");if(auditor.DepartmentId==auditee.Id)throw new InvalidOperationException("Baş denetçi denetlenen bölümden bağımsız olmalıdır.");var creatorDepartment=user.DepartmentId??throw new InvalidOperationException("Denetim planlayıcısının organizasyon bölümü zorunludur.");await using var tx=await db.Database.BeginTransactionAsync(ct);var num=$"İD-{now.Year}-{await Next("internal-audit",now.Year,tx,ct):000000}";var qr=QualityRecord.Create(num,"internal-audit",user.Id,creatorDepartment,now);var a=InternalAudit.Create(qr.Id,r.PlanYear,r.Title,r.AuditType,r.Scope,r.Objectives,r.Criteria,auditee.Id,auditee.Name,auditor.Id,auditor.DisplayName,auditor.Department,r.PlannedStartUtc.ToUniversalTime(),r.PlannedEndUtc.ToUniversalTime(),r.IsUnplanned,r.UnplannedReason,r.ChecklistVersion,r.Questions.Select(x=>(x.Question,x.Reference)),now);var responderId=auditee.ManagerUserId??await db.Users.Where(x=>x.IsActive&&x.DepartmentId==auditee.Id).Select(x=>(Guid?)x.Id).FirstOrDefaultAsync(ct)??throw new InvalidOperationException("Denetlenen bölüm için etkin yanıt sorumlusu bulunamadı.");db.QualityRecords.Add(qr);db.InternalAudits.Add(a);await Assign(a.Id,WorkflowTaskRoles.AuditPlanner,user.Id,now,a.PlannedStartUtc,ct);await Assign(a.Id,WorkflowTaskRoles.LeadAuditor,auditor.Id,now,a.PlannedEndUtc,ct);await Assign(a.Id,WorkflowTaskRoles.AuditeeResponder,responderId,now,a.PlannedEndUtc,ct);db.AuditEvents.Add(Audit(a,"InternalAuditCreated",now,new{num,r.IsUnplanned,r.ChecklistVersion,auditeeDepartmentId=auditee.Id,leadAuditorUserId=auditor.Id}));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return(await GetDetailsAsync(a.Id,ct))!;}
    public async Task<InternalAuditDetailsResponse?> TransitionAsync(Guid id,TransitionInternalAuditRequest r,CancellationToken ct){var a=await Load(id,ct);if(a is null)return null;var qr=await db.QualityRecords.SingleAsync(x=>x.Id==a.QualityRecordId,ct);var transition=r.Transition.Trim().ToLowerInvariant();var role=transition switch{"prepare" or "submit-plan"=>WorkflowTaskRoles.AuditPlanner,"approve-plan" or "start-finding-closure" or "request-audit-closure" or "close"=>WorkflowTaskRoles.Approver,"complete-responses"=>WorkflowTaskRoles.AuditeeResponder,_=>WorkflowTaskRoles.LeadAuditor};await EnsureActor(id,role,ct);if(transition is "approve-plan" or "close")await EnsureSignature(r.SignaturePassword,r.SignatureMeaningAccepted,ct);if(transition is "approve-plan" or "close"&&qr.CreatedByUserId==user.Id&&!user.IsInRole(QmsRoles.Administrator))throw new QmsForbiddenException("Görev ayrılığı: Denetimi oluşturan kullanıcı onay veya nihai kapanış imzası atamaz.");EnsureTransition(transition);var now=time.GetUtcNow();var from=a.Status;await using var tx=await db.Database.BeginTransactionAsync(ct);a.Transition(r.ExpectedVersion,transition,r.Note,now);if(transition=="prepare")qr.Submit(now);if(transition=="submit-plan"){await CompleteTasks(id,WorkflowTaskRoles.AuditPlanner,now,ct);await AssignApprover(a,qr.CreatedByUserId,now,ct);}if(transition=="approve-plan"){await CompleteTasks(id,WorkflowTaskRoles.Approver,now,ct);db.ElectronicSignatures.Add(ElectronicSignature.Create(qr.Id,a.Version,user.Id,user.DisplayName,"İç denetim planı ve soru listesi onayı",now,SignatureHash(a.Id,a.Version,transition,r.Note),r.Note));}if(transition=="confirm-findings")await CompleteTasks(id,WorkflowTaskRoles.LeadAuditor,now,ct);if(transition=="complete-responses"){await CompleteTasks(id,WorkflowTaskRoles.AuditeeResponder,now,ct);await AssignApprover(a,qr.CreatedByUserId,now,ct);}if(transition=="close"){qr.Close(now,false);await CompleteAllTasks(id,now,ct);db.ElectronicSignatures.Add(ElectronicSignature.Create(qr.Id,a.Version,user.Id,user.DisplayName,"İç denetim nihai kapanış onayı",now,SignatureHash(a.Id,a.Version,transition,r.Note),r.Note));}db.AuditEvents.Add(Audit(a,"InternalAuditStatusChanged",now,new{from=from.ToString(),to=a.Status.ToString(),transition},r.Note));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    public async Task<InternalAuditDetailsResponse?> AnswerAsync(Guid id,Guid itemId,AnswerAuditQuestionRequest r,CancellationToken ct){await EnsureActor(id,WorkflowTaskRoles.LeadAuditor,ct);return await Mutate(id,ct,(a,now)=>{EnsureExecute();if(!Enum.TryParse<AuditAnswerStatus>(r.Status,true,out var status))throw new ArgumentException("Soru sonucu geçersizdir.");a.Answer(r.ExpectedVersion,itemId,status,r.Evidence,r.Note,now);return("AuditQuestionAnswered",(object)new{itemId,status},r.Note);});}
    async Task<InternalAuditDetailsResponse?> IInternalAuditService.AddFindingAsync(Guid id,AddAuditFindingRequest r,CancellationToken ct){await EnsureActor(id,WorkflowTaskRoles.LeadAuditor,ct);return await AddFindingAsync(id,r,ct);}
    public async Task<InternalAuditDetailsResponse?> AddFindingAsync(Guid id,AddAuditFindingRequest r,CancellationToken ct){EnsureExecute();var a=await Load(id,ct);if(a is null)return null;var owner=await db.Users.AsNoTracking().Where(x=>x.Id==r.OwnerUserId&&x.IsActive).Select(x=>new{x.Id,x.DisplayName,x.DepartmentId}).SingleOrDefaultAsync(ct)??throw new ArgumentException("Seçilen bulgu sorumlusu etkin değil.");var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);var score=r.Impact*r.Likelihood;var needsCapa=r.CapaRequired||score>=12;Guid? capaId=null;if(needsCapa){var creatorDepartment=user.DepartmentId??throw new InvalidOperationException("DÖF açacak kullanıcının organizasyon bölümü zorunludur.");var cnum=$"DÖF-{now.Year}-{await Next("capa",now.Year,tx,ct):000000}";var qr=QualityRecord.Create(cnum,"capa",user.Id,creatorDepartment,now);var capa=Capa.Create(qr.Id,null,"InternalAudit",r.Title,r.Description,$"İç denetim bulgusu: {r.RequirementReference}","Bulguyu kontrol altına alma",owner.DisplayName,r.TargetDateUtc.ToUniversalTime(),true,"İç denetim tekrar doğrulaması","Bulgu kapsamı",30,"Aynı uygunsuzluğun tekrar etmemesi",a.AuditeeDepartment,now);db.QualityRecords.Add(qr);db.Capas.Add(capa);db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Capa",capa.Id,WorkflowTaskRoles.Initiator,user.Id,creatorDepartment,now,capa.TargetDateUtc,assignedUserNameSnapshot:user.DisplayName));capaId=capa.Id;db.AuditEvents.Add(AuditEvent.Create("Capa",capa.Id,capa.Version,"CapaCreatedFromInternalAuditFinding",user.Id,user.DisplayName,now,Guid.CreateVersion7().ToString(),JsonSerializer.SerializeToDocument(new{auditId=a.Id})));}var fnum=$"BLG-{now.Year}-{await Next("audit-finding",now.Year,tx,ct):000000}";var finding=AuditFinding.Create(a.Id,fnum,r.Title,r.Description,r.RequirementReference,r.Impact,r.Likelihood,needsCapa,capaId,owner.Id,owner.DisplayName,r.TargetDateUtc.ToUniversalTime(),now);a.AddFinding(r.ExpectedVersion,finding,now);db.AuditFindings.Add(finding);await Assign(a.Id,$"AuditFinding:{finding.Id}",owner.Id,now,finding.TargetDateUtc,ct);db.AuditEvents.Add(Audit(a,"AuditFindingCreated",now,new{finding.Number,finding.Classification,finding.RiskScore,capaId,ownerUserId=owner.Id}));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    public async Task<InternalAuditDetailsResponse?> RespondFindingAsync(Guid id,Guid findingId,RespondAuditFindingRequest r,CancellationToken ct){await EnsureActor(id,$"AuditFinding:{findingId}",ct);var result=await Mutate(id,ct,(a,now)=>{EnsureRespond();a.RespondFinding(r.ExpectedVersion,findingId,r.Response,r.CorrectiveAction,now);return("AuditFindingResponseSubmitted",(object)new{findingId},r.Response);});if(result is not null)await CompleteTasks(id,$"AuditFinding:{findingId}",time.GetUtcNow(),ct);await db.SaveChangesAsync(ct);return result is null?null:await GetDetailsAsync(id,ct);}
    public async Task<InternalAuditDetailsResponse?> CloseFindingAsync(Guid id,Guid findingId,CloseAuditFindingRequest r,CancellationToken ct){EnsureApprove();await EnsureActor(id,WorkflowTaskRoles.Approver,ct);await EnsureSignature(r.SignaturePassword,r.SignatureMeaningAccepted,ct);var a=await Load(id,ct);if(a is null)return null;var finding=a.Findings.SingleOrDefault(x=>x.Id==findingId)??throw new ArgumentException("Bulgu bulunamadı.");var capaClosed=!finding.CapaRequired||finding.LinkedCapaId is Guid cid&&await db.Capas.AnyAsync(x=>x.Id==cid&&x.Status==CapaStatus.Closed,ct);var now=time.GetUtcNow();await using var tx=await db.Database.BeginTransactionAsync(ct);a.CloseFinding(r.ExpectedVersion,findingId,r.VerificationNote,capaClosed,now);db.ElectronicSignatures.Add(ElectronicSignature.Create(a.QualityRecordId,a.Version,user.Id,user.DisplayName,$"{finding.Number} bulgu doğrulama ve kapanış onayı",now,SignatureHash(a.Id,a.Version,"finding-close",r.VerificationNote),r.VerificationNote));db.AuditEvents.Add(Audit(a,"AuditFindingClosed",now,new{findingId,finding.LinkedCapaId},r.VerificationNote));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetDetailsAsync(id,ct);}
    private async Task<InternalAuditDetailsResponse?> Mutate(Guid id, CancellationToken ct, Func<InternalAudit, DateTimeOffset, (string Type, object Payload, string? Reason)> fn) { var a = await Load(id, ct); if (a is null) return null; var now = time.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var e = fn(a, now); db.AuditEvents.Add(Audit(a, e.Type, now, e.Payload, e.Reason)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    private Task<InternalAudit?> Load(Guid id, CancellationToken ct) => db.InternalAudits.AsSplitQuery().Include(x => x.Checklist).Include(x => x.Findings).SingleOrDefaultAsync(x => x.Id == id, ct);
    private async Task Assign(Guid id,string role,Guid userId,DateTimeOffset now,DateTimeOffset? due,CancellationToken ct){var target=await(from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.Id==userId&&u.IsActive select new{u.Id,u.DisplayName,u.DepartmentId,Department=d==null?null:d.Name}).SingleOrDefaultAsync(ct)??throw new InvalidOperationException("M.07 görevi için seçilen kullanıcı etkin değil.");db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("InternalAudit",id,role,target.Id,target.DepartmentId,now,due,assignedUserNameSnapshot:target.DisplayName,assignedDepartmentNameSnapshot:target.Department));db.UserNotifications.Add(UserNotification.Create(target.Id,"M.07","Yeni iç denetim görevi",$"{role} görevi size atandı.",$"/modules/m07?open={id}",now));}
    private async Task AssignApprover(InternalAudit audit,Guid creatorId,DateTimeOffset now,CancellationToken ct){if(await db.WorkflowTaskAssignments.AnyAsync(x=>x.AggregateType=="InternalAudit"&&x.AggregateId==audit.Id&&x.TaskRole==WorkflowTaskRoles.Approver&&x.Status==WorkflowTaskStatus.Active,ct))return;var id=await(from ur in db.UserRoles.AsNoTracking() join r in db.Roles.AsNoTracking() on ur.RoleId equals r.Id join u in db.Users.AsNoTracking() on ur.UserId equals u.Id where u.IsActive&&u.Id!=creatorId&&u.Id!=audit.LeadAuditorUserId&&(r.Name==QmsRoles.Approver||r.Name==QmsRoles.QualityAssurance||r.Name==QmsRoles.Administrator) orderby r.Name==QmsRoles.Approver?0:1,u.DisplayName select u.Id).FirstOrDefaultAsync(ct);if(id==Guid.Empty)throw new InvalidOperationException("Planlayıcı ve baş denetçiden farklı etkin M.07 onaylayıcısı bulunamadı.");await Assign(audit.Id,WorkflowTaskRoles.Approver,id,now,audit.PlannedEndUtc,ct);}
    private async Task EnsureActor(Guid id,string role,CancellationToken ct){if(!await CanAct(id,role,ct))throw new QmsForbiddenException("Bu iç denetim görevi size veya etkin bir delegasyonla size atanmamış.");}
    private async Task<bool> CanAct(Guid id,string role,CancellationToken ct){var owners=await db.WorkflowTaskAssignments.AsNoTracking().Where(x=>x.AggregateType=="InternalAudit"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active).Select(x=>x.AssignedUserId).ToListAsync(ct);if(owners.Contains(user.Id))return true;var now=time.GetUtcNow();return owners.Count>0&&await db.Delegations.AsNoTracking().AnyAsync(x=>owners.Contains(x.DelegatorUserId)&&x.DelegateUserId==user.Id&&x.RevokedAtUtc==null&&x.StartsAtUtc<=now&&x.EndsAtUtc>=now&&(x.Scope=="M.07"||x.Scope=="ALL"),ct);}
    private async Task<IReadOnlyList<string>> CurrentTaskRoles(Guid id,CancellationToken ct){var roles=await db.WorkflowTaskAssignments.AsNoTracking().Where(x=>x.AggregateType=="InternalAudit"&&x.AggregateId==id&&x.Status==WorkflowTaskStatus.Active).Select(x=>x.TaskRole).Distinct().ToListAsync(ct);var result=new List<string>();foreach(var role in roles)if(await CanAct(id,role,ct))result.Add(role);return result;}
    private async Task CompleteTasks(Guid id,string role,DateTimeOffset now,CancellationToken ct){var tasks=await db.WorkflowTaskAssignments.Where(x=>x.AggregateType=="InternalAudit"&&x.AggregateId==id&&x.TaskRole==role&&x.Status==WorkflowTaskStatus.Active).ToListAsync(ct);foreach(var task in tasks)task.Complete(now);}
    private async Task CompleteAllTasks(Guid id,DateTimeOffset now,CancellationToken ct){var tasks=await db.WorkflowTaskAssignments.Where(x=>x.AggregateType=="InternalAudit"&&x.AggregateId==id&&x.Status==WorkflowTaskStatus.Active).ToListAsync(ct);foreach(var task in tasks)task.Complete(now);}
    private async Task EnsureSignature(string? password,bool accepted,CancellationToken ct){if(!accepted||string.IsNullOrWhiteSpace(password))throw new ArgumentException("Elektronik imza için parola ve anlam kabulü zorunludur.");var target=await userManager.FindByIdAsync(user.Id.ToString())??throw new QmsForbiddenException("İmzalayan kullanıcı bulunamadı.");if(!await userManager.CheckPasswordAsync(target,password))throw new QmsForbiddenException("Elektronik imza parolası geçersizdir.");}
    private static string SignatureHash(Guid id,long version,string action,string? note)=>Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes($"{id:N}|{version}|{action}|{note}")));
    private void EnsurePlan() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance)) return; throw new QmsForbiddenException("Denetim planlama için KG rolü gerekir."); }
    private void EnsureExecute() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.Investigator)) return; throw new QmsForbiddenException("Denetim uygulaması için denetçi rolü gerekir."); }
    private void EnsureRespond() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.DepartmentManager) || user.IsInRole(QmsRoles.ActionOwner)) return; throw new QmsForbiddenException("Bulgu yanıtı için bölüm yetkisi gerekir."); }
    private void EnsureApprove() { if (user.IsInRole(QmsRoles.Administrator) || user.IsInRole(QmsRoles.QualityAssurance) || user.IsInRole(QmsRoles.Approver)) return; throw new QmsForbiddenException("Denetim onayı için onaylayan rolü gerekir."); }
    private void EnsureTransition(string t) { if (t is "prepare" or "submit-plan") EnsurePlan(); else if (t == "complete-responses") EnsureRespond(); else if (t is "approve-plan" or "start-finding-closure" or "request-audit-closure" or "close") EnsureApprove(); else EnsureExecute(); }
    private AuditEvent Audit(InternalAudit a, string type, DateTimeOffset now, object payload, string? reason = null) => AuditEvent.Create("InternalAudit", a.Id, a.Version, type, user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(payload), reason); private static IReadOnlyList<InternalAuditTransitionResponse> Transitions(InternalAuditStatus s) => s switch { InternalAuditStatus.AnnualPlan => [new("prepare", "Hazırlığı başlat", false)], InternalAuditStatus.Preparation => [new("submit-plan", "Plan onayına gönder", false)], InternalAuditStatus.PlanApproval => [new("approve-plan", "Planı ve soru listesini kilitle", false)], InternalAuditStatus.Execution => [new("complete-execution", "Uygulamayı tamamla", false)], InternalAuditStatus.Findings => [new("confirm-findings", "Bulguları kesinleştir", false)], InternalAuditStatus.ResponseAction => [new("complete-responses", "Yanıtları doğrulamaya gönder", false)], InternalAuditStatus.CapaVerification => [new("start-finding-closure", "Bulgu kapanışını başlat", false)], InternalAuditStatus.FindingClosure => [new("request-audit-closure", "Denetim kapanışına gönder", false)], InternalAuditStatus.AuditClosure => [new("close", "Denetimi kapat", true)], _ => [] };
    private static IQueryable<Row> Filter(IQueryable<Row> q, ColumnFilterRequest f) { var k = f.Field.Trim().ToLowerInvariant(); var v = f.Value?.Trim() ?? ""; return k switch { "recordnumber" => q.Where(x => x.Number.ToLower().Contains(v.ToLower())), "title" => q.Where(x => x.Audit.Title.ToLower().Contains(v.ToLower())), "audittype" => q.Where(x => x.Audit.AuditType.ToLower().Contains(v.ToLower())), "auditeedepartment" => q.Where(x => x.Audit.AuditeeDepartment.ToLower().Contains(v.ToLower())), "leadauditor" => q.Where(x => x.Audit.LeadAuditor.ToLower().Contains(v.ToLower())), "status" => Enum.TryParse<InternalAuditStatus>(v, true, out var s) ? q.Where(x => x.Audit.Status == s) : throw new ArgumentException("Durum geçersizdir."), "isunplanned" => bool.TryParse(v, out var b) ? q.Where(x => x.Audit.IsUnplanned == b) : throw new ArgumentException("Plansız filtresi geçersizdir."), "planyear" => int.TryParse(v, out var y) ? q.Where(x => x.Audit.PlanYear == y) : throw new ArgumentException("Plan yılı geçersizdir."), "plannedstartutc" => Date(q, f.Operator, f.Value, f.ValueTo), _ => throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}") }; }
    private static IQueryable<Row> Date(IQueryable<Row> q, string op, string? a, string? b) { var from = DateTimeOffset.Parse(a ?? "", CultureInfo.InvariantCulture).ToUniversalTime(); var to = string.IsNullOrWhiteSpace(b) ? from.AddDays(1) : DateTimeOffset.Parse(b, CultureInfo.InvariantCulture).ToUniversalTime(); return op switch { "before" => q.Where(x => x.Audit.PlannedStartUtc < from), "after" => q.Where(x => x.Audit.PlannedStartUtc > from), _ => q.Where(x => x.Audit.PlannedStartUtc >= from && x.Audit.PlannedStartUtc < to) }; }
    private static IQueryable<Row> Sort(IQueryable<Row> q, string f, string d) { var x = d.Equals("desc", StringComparison.OrdinalIgnoreCase); return f.ToLowerInvariant() switch { "recordnumber" => x ? q.OrderByDescending(z => z.Number) : q.OrderBy(z => z.Number), "title" => x ? q.OrderByDescending(z => z.Audit.Title) : q.OrderBy(z => z.Audit.Title), "plannedstartutc" => x ? q.OrderByDescending(z => z.Audit.PlannedStartUtc) : q.OrderBy(z => z.Audit.PlannedStartUtc), "status" => x ? q.OrderByDescending(z => z.Audit.Status) : q.OrderBy(z => z.Audit.Status), _ => x ? q.OrderByDescending(z => z.Audit.CreatedAtUtc) : q.OrderBy(z => z.Audit.CreatedAtUtc) }; }
    private async Task<long> Next(string type, int year, IDbContextTransaction tx, CancellationToken ct) { var c = db.Database.GetDbConnection(); if (c.State != ConnectionState.Open) await c.OpenAsync(ct); await using var cmd = c.CreateCommand(); cmd.Transaction = tx.GetDbTransaction(); cmd.CommandText = "INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@type,@year,1) ON CONFLICT (\"RecordType\",\"CalendarYear\") DO UPDATE SET \"LastValue\"=core.record_number_sequence.\"LastValue\"+1 RETURNING \"LastValue\";"; Add(cmd, "type", type); Add(cmd, "year", year); return Convert.ToInt64(await cmd.ExecuteScalarAsync(ct), CultureInfo.InvariantCulture); }
    private static void Add(DbCommand c, string n, object v) { var p = c.CreateParameter(); p.ParameterName = n; p.Value = v; c.Parameters.Add(p); }
    private sealed class Row { public required InternalAudit Audit { get; init; } public required string Number { get; init; } }
}
