using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using PdfSharp.Fonts;
using Qms.Application.InternalAudits;
using Qms.Contracts.InternalAudits;
namespace Qms.Infrastructure.InternalAudits;

public sealed class InternalAuditFinalReportService(IConfiguration configuration):IInternalAuditFinalReportService
{
    private const string FontFamily="QmsDejaVuSans";private static readonly Lock FontLock=new();
    public async Task<InternalAuditFinalReportFile>EnsureGeneratedAsync(InternalAuditDetailsResponse d,CancellationToken ct){if(d.Record.Status!="Closed")throw new InvalidOperationException("Nihai PDF yalnız kapatılmış iç denetimler için üretilebilir.");var root=configuration["FileStorage:RootPath"]??Path.Combine(AppContext.BaseDirectory,"qms-files");var dir=Path.Combine(root,"internal-audits",d.Record.Id.ToString("N"));Directory.CreateDirectory(dir);var safe=string.Concat(d.Record.RecordNumber.Select(c=>char.IsLetterOrDigit(c)||c is '-' or '_'?c:'_'));var name=$"{safe}-nihai-ic-denetim-v{d.Record.Version}.pdf";var path=Path.Combine(dir,name);var hashPath=path+".sha256";var reportIsNew = !File.Exists(path); if (reportIsNew){EnsureFont();var bytes=Build(d,SnapshotHash(d));try{await File.WriteAllBytesAsync(path,bytes,ct);}catch(IOException)when(File.Exists(path)){}var hash=Convert.ToHexStringLower(SHA256.HashData(await File.ReadAllBytesAsync(path,ct)));try{await File.WriteAllTextAsync(hashPath,hash,Encoding.ASCII,ct);}catch(IOException)when(File.Exists(hashPath)){}}var content=await File.ReadAllBytesAsync(path,ct);var actual=Convert.ToHexStringLower(SHA256.HashData(content));var expected=(await File.ReadAllTextAsync(hashPath,ct)).Trim();if(!CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(actual),Encoding.ASCII.GetBytes(expected)))throw new InvalidOperationException("Nihai iç denetim PDF bütünlük doğrulamasını geçemedi.");await Qms.Infrastructure.Integrity.FinalReportIntegrity.SealNewOrVerifyAsync(configuration, path, actual, reportIsNew); return new(content,name,actual);}
    private static byte[] Build(InternalAuditDetailsResponse d,string snapshotHash){var r=d.Record;var doc=new Document{Info={Title=$"{r.RecordNumber} Nihai İç Denetim",Author="QMS"}};doc.Styles["Normal"]!.Font.Name=FontFamily;doc.Styles["Normal"]!.Font.Size=9;var s=doc.AddSection();s.PageSetup.PageFormat=PageFormat.A4;s.PageSetup.TopMargin=Unit.FromCentimeter(1.4);s.PageSetup.BottomMargin=Unit.FromCentimeter(1.6);s.PageSetup.LeftMargin=s.PageSetup.RightMargin=Unit.FromCentimeter(1.5);Brand(s,"QMS  |  M.07 İÇ DENETİMLER");var title=s.AddParagraph(r.Title);title.Format.Font.Size=19;title.Format.Font.Bold=true;title.Format.Font.Color=Color.Parse("#0F5F61");s.AddParagraph($"{r.RecordNumber} | Kayıt sürümü {r.Version} | NİHAİ - KAPALI");Heading(s,"1. Plan ve kapsam");Grid(s,["Plan yılı / tür",$"{r.PlanYear} / {r.AuditType}","Denetlenen bölüm",r.AuditeeDepartment,"Baş denetçi",$"{r.LeadAuditor} / {r.LeadAuditorDepartment}","Planlanan dönem",$"{F(r.PlannedStartUtc)} - {F(r.PlannedEndUtc)}","Soru listesi",$"{r.ChecklistVersion} / {(r.ChecklistLockedAtUtc.HasValue?"Kilitli":"Açık")}","Bağımsızlık",r.IndependenceConfirmed?"Doğrulandı":"Doğrulanmadı"]);Block(s,"Kapsam",r.Scope);Block(s,"Amaçlar",r.Objectives);Block(s,"Kriterler",r.Criteria);Heading(s,"2. Soru listesi ve kanıtlar");var checklist=Table(s,["No","Soru / referans","Sonuç","Kanıt / not"]);foreach(var x in d.Checklist)Row(checklist,x.Order.ToString(),$"{x.Question}\n{x.Reference}",x.Status,$"{x.Evidence??"-"}\n{x.Note??"-"}");Heading(s,"3. Bulgular ve aksiyonlar");var findings=Table(s,["Bulgu","Sınıf / risk","Sorumlu / hedef","Yanıt / doğrulama"]);foreach(var x in d.Findings)Row(findings,$"{x.Number}\n{x.Title}",$"{x.Classification} / {x.RiskScore}",$"{x.Owner}\n{F(x.TargetDateUtc)}",$"{x.CorrectiveAction??"-"}\n{x.VerificationNote??"-"}");Heading(s,"4. Kapanış özeti");Block(s,"Nihai sonuç",r.Summary??"-");Heading(s,"5. Elektronik imzalar");var signs=Table(s,["Anlam","İmzalayan","Tarih / sürüm","İçerik hash"]);foreach(var x in d.Signatures)Row(signs,x.Meaning,x.Signer,$"{F(x.SignedAtUtc)} / v{x.RecordVersion}",x.ContentHash[..Math.Min(16,x.ContentHash.Length)]+"...");var proof=s.AddParagraph();proof.Format.SpaceBefore=10;proof.Format.Shading.Color=Color.Parse("#EAF4F2");proof.AddFormattedText("KAYIT SNAPSHOT SHA-256\n",TextFormat.Bold);proof.AddText(snapshotHash);var footer=s.Footers.Primary.AddParagraph();footer.Format.Alignment=ParagraphAlignment.Center;footer.AddText($"{r.RecordNumber} | Kontrollü elektronik kayıt | Sayfa ");footer.AddPageField();footer.AddText(" / ");footer.AddNumPagesField();var renderer=new PdfDocumentRenderer{Document=doc};renderer.RenderDocument();using var stream=new MemoryStream();renderer.PdfDocument.Save(stream,false);return stream.ToArray();}
    private static void Brand(Section s,string v){var p=s.AddParagraph(v);p.Format.Font.Bold=true;p.Format.Font.Color=Color.Parse("#0F7773");}private static void Heading(Section s,string v){var p=s.AddParagraph(v);p.Format.Font.Size=13;p.Format.Font.Bold=true;p.Format.Font.Color=Color.Parse("#173C46");p.Format.SpaceBefore=9;p.Format.SpaceAfter=4;}private static void Block(Section s,string l,string v){var p=s.AddParagraph();p.Format.SpaceAfter=5;p.AddFormattedText(l+"\n",TextFormat.Bold);p.AddText(v);}private static void Grid(Section s,string[] v){var t=Table(s,["Alan","Değer"]);for(var i=0;i<v.Length;i+=2)Row(t,v[i],v[i+1]);}private static Table Table(Section s,string[] h){var t=s.AddTable();t.Borders.Color=Color.Parse("#CBD9D7");t.Borders.Width=.5;var w=17.4/h.Length;foreach(var _ in h)t.AddColumn(Unit.FromCentimeter(w));var row=t.AddRow();row.Shading.Color=Color.Parse("#EAF4F2");for(var i=0;i<h.Length;i++)Cell(row.Cells[i],h[i],true);return t;}private static void Row(Table t,params string[] v){var row=t.AddRow();for(var i=0;i<v.Length;i++)Cell(row.Cells[i],v[i]);}private static void Cell(Cell c,string v,bool bold=false){var p=c.AddParagraph(v);p.Format.Font.Bold=bold;p.Format.Font.Size=8;c.VerticalAlignment=VerticalAlignment.Center;}private static string SnapshotHash(InternalAuditDetailsResponse d)=>Convert.ToHexStringLower(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(d)));private static string F(DateTimeOffset? v)=>v?.ToOffset(TimeSpan.FromHours(3)).ToString("dd.MM.yyyy HH:mm 'TRT'")??"-";private static void EnsureFont(){if(GlobalFontSettings.FontResolver is not null)return;lock(FontLock)GlobalFontSettings.FontResolver??=new Resolver();}private sealed class Resolver:IFontResolver{private static readonly string Regular=Path.Combine("/usr/share/fonts/truetype/dejavu","DejaVuSans.ttf");private static readonly string Bold=Path.Combine("/usr/share/fonts/truetype/dejavu","DejaVuSans-Bold.ttf");public byte[]GetFont(string face)=>File.ReadAllBytes(face.EndsWith("Bold",StringComparison.Ordinal)?Bold:Regular);public FontResolverInfo ResolveTypeface(string family,bool bold,bool italic)=>new(bold?"QmsBold":"QmsRegular",false,false);}
}
