using System.Text.Json;
namespace Qms.Contracts.Documents;

public sealed record ControlledDocumentListItemResponse(Guid Id, string RecordNumber, Guid? SourceChangeControlId, string? SourceRecordNumber, string DocumentCode, string Title, string DocumentType, string Owner, string Department, string Confidentiality, string CurrentRevision, string Status, DateTimeOffset PlannedEffectiveDateUtc, DateTimeOffset? NextReviewDateUtc, int PendingReviews, int PendingTrainings, DateTimeOffset CreatedAtUtc, long Version);
public sealed record ControlledDocumentResponse(Guid Id, Guid QualityRecordId, string RecordNumber, Guid? SourceChangeControlId, string? SourceRecordNumber, string DocumentCode, string Title, string DocumentType, string Owner, string Department, string Confidentiality, int ReviewPeriodMonths, DateTimeOffset PlannedEffectiveDateUtc, DateTimeOffset? NextReviewDateUtc, Guid CurrentRevisionId, string CurrentRevision, string Status, string? WithdrawalReason, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? ArchivedAtUtc, long Version);
public sealed record DocumentRevisionResponse(Guid Id, string VersionLabel, string Content, string ChangeSummary, string PreparedBy, string Status, DateTimeOffset CreatedAtUtc, DateTimeOffset? ApprovedAtUtc, DateTimeOffset? EffectiveAtUtc, bool IsCurrent);
public sealed record DocumentReviewResponse(Guid Id, Guid RevisionId, string Department, string Reviewer, string Status, string? Comment, DateTimeOffset? CompletedAtUtc);
public sealed record DocumentTrainingResponse(Guid Id, Guid RevisionId, string Position, string AssignedUser, string Status, string? Evidence, DateTimeOffset? CompletedAtUtc);
public sealed record ControlledCopyResponse(Guid Id, Guid RevisionId, string CopyNumber, string Recipient, string Purpose, string Status, DateTimeOffset IssuedAtUtc, DateTimeOffset? DueBackAtUtc, DateTimeOffset? ReturnedAtUtc, DateTimeOffset? DestroyedAtUtc);
public sealed record DocumentReadReceiptResponse(Guid Id, Guid RevisionId, Guid UserId, string UserDisplayName, string SignatureMeaning, DateTimeOffset AcknowledgedAtUtc);
public sealed record DocumentAuditEventResponse(Guid Id, long Version, string EventType, string Actor, DateTimeOffset OccurredAtUtc, string? Reason, JsonElement Payload);
public sealed record DocumentTransitionResponse(string Code, string Label, bool NoteRequired);
public sealed record ControlledDocumentDetailsResponse(ControlledDocumentResponse Record, IReadOnlyList<DocumentRevisionResponse> Revisions, IReadOnlyList<DocumentReviewResponse> Reviews, IReadOnlyList<DocumentTrainingResponse> TrainingRequirements, IReadOnlyList<ControlledCopyResponse> ControlledCopies, IReadOnlyList<DocumentReadReceiptResponse> ReadReceipts, IReadOnlyList<DocumentAuditEventResponse> AuditTrail, IReadOnlyList<DocumentTransitionResponse> AvailableTransitions);
