using System.Text.Json;
namespace Qms.Contracts.Documents;

public sealed record ControlledDocumentListItemResponse(Guid Id, string RecordNumber, Guid? SourceChangeControlId, string? SourceRecordNumber, string DocumentCode, string Title, string DocumentType, string Owner, string Department, string Confidentiality, string CurrentRevision, string Status, DateTimeOffset PlannedEffectiveDateUtc, DateTimeOffset? NextReviewDateUtc, int PendingReviews, int PendingTrainings, DateTimeOffset CreatedAtUtc, long Version);
public sealed record ControlledDocumentResponse(Guid Id, Guid QualityRecordId, string RecordNumber, Guid? SourceChangeControlId, string? SourceRecordNumber, string DocumentCode, string Title, string DocumentType, Guid? OwnerUserId, string Owner, Guid? DepartmentId, string Department, string Confidentiality, int ReviewPeriodMonths, DateTimeOffset PlannedEffectiveDateUtc, DateTimeOffset? NextReviewDateUtc, Guid CurrentRevisionId, string CurrentRevision, string Status, string? WithdrawalReason, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? ArchivedAtUtc, long Version);
public sealed record DocumentRevisionResponse(Guid Id, string VersionLabel, string Content, string ChangeSummary, string PreparedBy, string Status, DateTimeOffset CreatedAtUtc, DateTimeOffset? ApprovedAtUtc, DateTimeOffset? EffectiveAtUtc, bool IsCurrent);
public sealed record DocumentReviewResponse(Guid Id, Guid RevisionId, Guid? DepartmentId, string Department, Guid? ReviewerUserId, string Reviewer, string Status, string? Comment, DateTimeOffset? CompletedAtUtc);
public sealed record DocumentTrainingResponse(Guid Id, Guid RevisionId, Guid? PositionId, string Position, string AssignedUser, string Status, string? Evidence, DateTimeOffset? CompletedAtUtc);
public sealed record ControlledCopyResponse(Guid Id, Guid RevisionId, string CopyNumber, string Recipient, string Purpose, string Status, DateTimeOffset IssuedAtUtc, DateTimeOffset? DueBackAtUtc, DateTimeOffset? ReturnedAtUtc, DateTimeOffset? DestroyedAtUtc);
public sealed record DocumentReadReceiptResponse(Guid Id, Guid RevisionId, Guid UserId, string UserDisplayName, string SignatureMeaning, DateTimeOffset AcknowledgedAtUtc);
public sealed record DocumentAuditEventResponse(Guid Id, long Version, string EventType, string Actor, DateTimeOffset OccurredAtUtc, string? Reason, JsonElement Payload);
public sealed record DocumentTransitionResponse(string Code, string Label, bool NoteRequired);
public sealed record DocumentUserOptionResponse(Guid Id, string DisplayName, string? DepartmentName);
public sealed record DocumentDepartmentOptionResponse(Guid Id, string Code, string Name, Guid ReviewerUserId, string ReviewerName);
public sealed record DocumentPositionOptionResponse(Guid Id, string Code, string Name, string? DepartmentName);
public sealed record DocumentLookupOptionResponse(string Code, string Name);
public sealed record DocumentLookupDefinitionResponse(Guid Id, string Category, string Code, string Name, int SortOrder, bool IsActive);
public sealed record CreateDocumentLookupDefinitionRequest(string Category, string Code, string Name, int SortOrder);
public sealed record UpdateDocumentLookupDefinitionRequest(string Name, int SortOrder, bool IsActive);
public sealed record DocumentLookupsResponse(IReadOnlyList<DocumentUserOptionResponse> Owners, IReadOnlyList<DocumentDepartmentOptionResponse> Departments, IReadOnlyList<DocumentPositionOptionResponse> Positions, IReadOnlyList<DocumentLookupOptionResponse> DocumentTypes, IReadOnlyList<DocumentLookupOptionResponse> ConfidentialityLevels);
public sealed record DocumentSignatureResponse(Guid Id, long RecordVersion, Guid SignerUserId, string SignerName, string Meaning, DateTimeOffset SignedAtUtc, string ContentHash, string? Comment);
public sealed record ControlledDocumentDetailsResponse(ControlledDocumentResponse Record, IReadOnlyList<DocumentRevisionResponse> Revisions, IReadOnlyList<DocumentReviewResponse> Reviews, IReadOnlyList<DocumentTrainingResponse> TrainingRequirements, IReadOnlyList<ControlledCopyResponse> ControlledCopies, IReadOnlyList<DocumentReadReceiptResponse> ReadReceipts, IReadOnlyList<DocumentAuditEventResponse> AuditTrail, IReadOnlyList<DocumentSignatureResponse> Signatures, IReadOnlyList<DocumentTransitionResponse> AvailableTransitions, IReadOnlyList<string> ActionableTaskRoles);
