using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Qms.Application.Security;
using Qms.Application.ElectronicSignatures;
using Qms.Application.Trainings;
using Qms.Contracts.Common;
using Qms.Contracts.Trainings;
using Qms.Domain.AuditTrail;
using Qms.Domain.Notifications;
using Qms.Domain.QualityRecords;
using Qms.Domain.Trainings;
using Qms.Domain.Workflows;
using Qms.Infrastructure.Persistence;
namespace Qms.Infrastructure.Trainings;

public sealed class TrainingService(QmsDbContext db, TimeProvider clock, ICurrentUser user, IElectronicSignatureService signatures) : ITrainingService
{
    private static readonly HashSet<string> LookupCategories = ["AssessmentMode", "DeliveryMethod"];
    public async Task<PagedResponse<TrainingListItemResponse>> SearchAsync(TrainingSearchRequest r, CancellationToken ct) { if (r.Page < 1 || r.PageSize is not (10 or 25 or 50 or 100)) throw new ArgumentException("Sayfa ve sayfa boyutu geçersizdir."); var q = BaseRows(); foreach (var f in r.Filters ?? []) q = Filter(q, f); var total = await q.LongCountAsync(ct); q = Sort(q, r.SortBy, r.SortDirection); var items = await q.Skip((r.Page - 1) * r.PageSize).Take(r.PageSize).Select(x => new TrainingListItemResponse(x.Assignment.Id, x.RecordNumber, x.Assignment.EmployeeUserId, x.Assignment.EmployeeName, x.Assignment.PositionId, x.Assignment.Position, x.Assignment.CourseCode, x.Assignment.CourseTitle, x.DocumentCode, x.DocumentMajor == null ? null : x.DocumentMajor + "." + x.DocumentMinor, x.Assignment.AssessmentMode.ToString(), x.Assignment.DeliveryMethod.ToString(), x.Assignment.Status.ToString(), x.Assignment.ProgressPercent, x.Assignment.DueAtUtc, x.Assignment.ExpiresAtUtc, x.Assignment.IsCriticalQualification, x.Assignment.Attempts.Count, x.Assignment.CreatedAtUtc, x.Assignment.Version)).ToListAsync(ct); return new(items, r.Page, r.PageSize, total, total == 0 ? 0 : (int)Math.Ceiling(total / (double)r.PageSize)); }
    public async Task<TrainingDetailsResponse?> GetDetailsAsync(Guid id, CancellationToken ct) { var x = await BaseRows(true).SingleOrDefaultAsync(x => x.Assignment.Id == id, ct); if (x is null) return null; var a = x.Assignment; var audit = await db.AuditEvents.AsNoTracking().Where(e => e.AggregateType == "Training" && e.AggregateId == id).OrderByDescending(e => e.OccurredAtUtc).ToListAsync(ct); var signatures = await db.ElectronicSignatures.AsNoTracking().Where(e => e.QualityRecordId == a.QualityRecordId).OrderBy(e => e.SignedAtUtc).Select(e => new TrainingSignatureResponse(e.Id, e.RecordVersion, e.SignerUserId, e.SignerDisplayNameSnapshot, e.Meaning, e.SignedAtUtc, e.ContentHash, e.Comment)).ToListAsync(ct); var roles = await CurrentTaskRoles(id, ct); var record = new TrainingRecordResponse(a.Id, a.QualityRecordId, x.RecordNumber, a.MatrixRuleId, a.ControlledDocumentId, a.DocumentRevisionId, a.DocumentTrainingRequirementId, a.EmployeeUserId, a.EmployeeName, a.PositionId, a.Position, a.CourseCode, a.CourseTitle, x.DocumentCode, x.DocumentMajor == null ? null : $"{x.DocumentMajor}.{x.DocumentMinor}", a.AssessmentMode.ToString(), a.DeliveryMethod.ToString(), a.PassingScore, a.ValidityMonths, a.MaxAttempts, a.IsCriticalQualification, a.PlannedYear, a.SessionCode, a.Trainer, a.DueAtUtc, a.Status.ToString(), a.ProgressPercent, a.StartedAtUtc, a.AcknowledgedAtUtc, a.AcknowledgementMeaning, a.CompletedAtUtc, a.ExpiresAtUtc, a.TrainerApprovalNote, a.CreatedAtUtc, a.UpdatedAtUtc, a.Version); return new(record, a.Attempts.OrderByDescending(t => t.AttemptNumber).Select(t => new TrainingAttemptResponse(t.Id, t.AttemptNumber, t.Score, t.PracticalPassed, t.Passed, t.Evidence, t.Evaluator, t.AssessedAtUtc)).ToList(), audit.Select(e => new TrainingAuditResponse(e.Id, e.AggregateVersion, e.EventType, e.ActorDisplayNameSnapshot, e.OccurredAtUtc, e.Reason, e.Payload.RootElement.Clone())).ToList(), signatures, Transitions(a.Status, roles), roles); }
    public async Task<TrainingDetailsResponse> CreateAsync(CreateTrainingAssignmentRequest r, CancellationToken ct)
    {
        EnsureManager(); var employee = await Employee(r.EmployeeUserId, r.PositionId, ct); var position = await Position(r.PositionId, ct);
        if (r.MatrixRuleId is Guid matrixId && !await db.TrainingMatrixRules.AnyAsync(x => x.Id == matrixId && x.IsActive, ct)) throw new ArgumentException("Etkin eğitim matrisi kuralı bulunamadı.");
        if (r.ControlledDocumentId is Guid did && !await db.ControlledDocuments.AnyAsync(x => x.Id == did, ct)) throw new ArgumentException("Bağlı doküman bulunamadı.");
        var mode = await Mode(r.AssessmentMode, ct); var delivery = await Delivery(r.DeliveryMethod, ct); var creatorDepartment = user.DepartmentId ?? throw new InvalidOperationException("Eğitim planlayıcısının etkin bir organizasyon bölümü olmalıdır."); var now = clock.GetUtcNow();
        await using var tx = await db.Database.BeginTransactionAsync(ct); var number = $"EGT-{now.Year}-{await NextNumber(now.Year, tx, ct):000000}"; var qr = QualityRecord.Create(number, "training", user.Id, creatorDepartment, now); if (r.AssignNow) qr.Submit(now);
        var a = TrainingAssignment.Create(qr.Id, r.MatrixRuleId, r.ControlledDocumentId, r.DocumentRevisionId, null, r.EmployeeUserId, employee.Name, position.Id, position.Name, r.CourseCode, r.CourseTitle, mode, delivery, r.PassingScore, r.ValidityMonths, r.MaxAttempts, r.IsCriticalQualification, r.DueAtUtc.ToUniversalTime(), r.SessionCode, r.Trainer, r.AssignNow, now);
        db.QualityRecords.Add(qr); db.TrainingAssignments.Add(a); await Assign(a.Id, WorkflowTaskRoles.TrainingCoordinator, user.Id, now, a.DueAtUtc, ct); if (r.AssignNow) await Assign(a.Id, WorkflowTaskRoles.Learner, a.EmployeeUserId, now, a.DueAtUtc, ct);
        db.AuditEvents.Add(Audit(a, "TrainingAssignmentCreated", now, new { number, r.EmployeeUserId, positionId = position.Id, r.ControlledDocumentId })); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return (await GetDetailsAsync(a.Id, ct))!;
    }
    public async Task<TrainingDetailsResponse?> TransitionAsync(Guid id, TransitionTrainingRequest r, CancellationToken ct)
    {
        var a = await Load(id, ct); if (a is null) return null; var code = r.Transition.Trim().ToLowerInvariant();
        var required = code switch { "start" or "submit-assessment" => WorkflowTaskRoles.Learner, "approve" => WorkflowTaskRoles.Trainer, "assign" or "reassign" or "cancel" or "expire" => WorkflowTaskRoles.TrainingCoordinator, _ => throw new ArgumentException("Bilinmeyen eğitim geçişi.") };
        await EnsureActor(id, required, ct); if (code == "approve" && a.EmployeeUserId == user.Id) throw new QmsForbiddenException("Görev ayrılığı kuralı: Çalışan kendi eğitim yeterliliğini onaylayamaz."); if (code == "approve") await signatures.AuthenticateAsync(r.SignaturePassword, r.SignatureMeaningAccepted, ct);
        var qr = await db.QualityRecords.SingleAsync(x => x.Id == a.QualityRecordId, ct); var now = clock.GetUtcNow(); var from = a.Status; await using var tx = await db.Database.BeginTransactionAsync(ct); a.Transition(r.ExpectedVersion, code, r.Note, now);
        if (code == "assign") { qr.Submit(now); await Assign(a.Id, WorkflowTaskRoles.Learner, a.EmployeeUserId, now, a.DueAtUtc, ct); }
        if (code == "submit-assessment") { await CompleteTasks(a.Id, WorkflowTaskRoles.Learner, now, ct); await AssignTrainer(a, now, ct); }
        if (code == "reassign") await Assign(a.Id, WorkflowTaskRoles.Learner, a.EmployeeUserId, now, a.DueAtUtc, ct);
        if (code == "approve") { await CompleteTasks(a.Id, WorkflowTaskRoles.Trainer, now, ct); db.ElectronicSignatures.Add(signatures.CreateInternal(qr.Id, "Training", a.Id, a.Version, code, "Eğitim yeterlilik onayı", new { assignment = a, attempts = a.Attempts, code, r.Note }, now, r.Note)); }
        if (code == "cancel") await CompleteAllTasks(a.Id, now, ct); if (a.Status == TrainingAssignmentStatus.Completed) { qr.Close(now, false); await SyncDocumentRequirement(a, now, ct); }
        db.AuditEvents.Add(Audit(a, "TrainingStatusChanged", now, new { from = from.ToString(), to = a.Status.ToString(), transition = code }, r.Note)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct);
    }
    public async Task<TrainingDetailsResponse?> AcknowledgeAsync(Guid id, AcknowledgeTrainingRequest r, CancellationToken ct) { var a = await Load(id, ct); if (a is null) return null; await EnsureActor(id, WorkflowTaskRoles.Learner, ct); await signatures.AuthenticateAsync(r.SignaturePassword, r.SignatureMeaningAccepted, ct); var now = clock.GetUtcNow(); a.Acknowledge(r.ExpectedVersion, r.SignatureMeaning, now); db.ElectronicSignatures.Add(signatures.CreateInternal(a.QualityRecordId, "Training", a.Id, a.Version, "acknowledge", r.SignatureMeaning, new { assignment = a, attempts = a.Attempts, r.SignatureMeaning }, now, r.SignatureMeaning)); db.AuditEvents.Add(Audit(a, "TrainingReadAcknowledged", now, new { a.DocumentRevisionId }, r.SignatureMeaning)); await db.SaveChangesAsync(ct); return await GetDetailsAsync(id, ct); }
    public async Task<TrainingDetailsResponse?> RecordAssessmentAsync(Guid id, RecordTrainingAssessmentRequest r, CancellationToken ct) { await EnsureActor(id, WorkflowTaskRoles.Trainer, ct); var a = await Load(id, ct); if (a is null) return null; if (a.EmployeeUserId == user.Id) throw new QmsForbiddenException("Çalışan kendi değerlendirmesini kaydedemez."); await signatures.AuthenticateAsync(r.SignaturePassword, r.SignatureMeaningAccepted, ct); var now = clock.GetUtcNow(); var attempt = a.RecordAttempt(r.ExpectedVersion, r.Score, r.PracticalPassed, r.Evidence, user.DisplayName, now); db.TrainingAssessmentAttempts.Add(attempt); db.ElectronicSignatures.Add(signatures.CreateInternal(a.QualityRecordId, "Training", a.Id, a.Version, "assessment", "Eğitim değerlendirmesi", new { assignment = a, attempts = a.Attempts, currentAttempt = attempt }, now, r.Evidence)); db.AuditEvents.Add(Audit(a, attempt.Passed ? "TrainingAssessmentPassed" : "TrainingAssessmentFailed", now, new { attempt.AttemptNumber, r.Score, r.PracticalPassed }, r.Evidence)); if (a.Status == TrainingAssignmentStatus.InProgress) { await CompleteTasks(a.Id, WorkflowTaskRoles.Trainer, now, ct); await Assign(a.Id, WorkflowTaskRoles.Learner, a.EmployeeUserId, now, a.DueAtUtc, ct); } else if (a.Status == TrainingAssignmentStatus.Failed) await CompleteTasks(a.Id, WorkflowTaskRoles.Trainer, now, ct); await db.SaveChangesAsync(ct); return await GetDetailsAsync(id, ct); }
    public async Task<IReadOnlyList<TrainingMatrixRuleResponse>> GetMatrixAsync(CancellationToken ct) => await (from m in db.TrainingMatrixRules.AsNoTracking() join d in db.ControlledDocuments.AsNoTracking() on m.ControlledDocumentId equals d.Id into ds from d in ds.DefaultIfEmpty() orderby m.Position, m.CourseCode select new TrainingMatrixRuleResponse(m.Id, m.PositionId, m.Position, m.CourseCode, m.CourseTitle, m.ControlledDocumentId, d == null ? null : d.DocumentCode, m.AssessmentMode.ToString(), m.DeliveryMethod.ToString(), m.PassingScore, m.ValidityMonths, m.IsCriticalQualification, m.IsActive, m.EffectiveAtUtc)).ToListAsync(ct);
    public async Task<TrainingMatrixRuleResponse> CreateMatrixRuleAsync(CreateTrainingMatrixRuleRequest r, CancellationToken ct) { EnsureManager(); var position = await Position(r.PositionId, ct); var mode = await Mode(r.AssessmentMode, ct); var delivery = await Delivery(r.DeliveryMethod, ct); if (await db.TrainingMatrixRules.AnyAsync(x => x.PositionId == position.Id && x.CourseCode == r.CourseCode.Trim(), ct)) throw new ArgumentException("Bu pozisyon ve eğitim kodu matris içinde zaten tanımlı."); string? documentCode = null; if (r.ControlledDocumentId is Guid did) documentCode = await db.ControlledDocuments.Where(x => x.Id == did).Select(x => x.DocumentCode).SingleOrDefaultAsync(ct) ?? throw new ArgumentException("Bağlı doküman bulunamadı."); var m = TrainingMatrixRule.Create(position.Id, position.Name, r.CourseCode, r.CourseTitle, r.ControlledDocumentId, mode, delivery, r.PassingScore, r.ValidityMonths, r.IsCriticalQualification, r.EffectiveAtUtc.ToUniversalTime(), clock.GetUtcNow()); db.TrainingMatrixRules.Add(m); await db.SaveChangesAsync(ct); return new(m.Id, m.PositionId, m.Position, m.CourseCode, m.CourseTitle, m.ControlledDocumentId, documentCode, m.AssessmentMode.ToString(), m.DeliveryMethod.ToString(), m.PassingScore, m.ValidityMonths, m.IsCriticalQualification, m.IsActive, m.EffectiveAtUtc); }
    public async Task<TrainingOptionsResponse> GetOptionsAsync(CancellationToken ct) { var employees = await (from u in db.Users.AsNoTracking() join up in db.UserPositions.AsNoTracking().Where(x => x.EndsAtUtc == null && x.IsPrimary) on u.Id equals up.UserId join p in db.Positions.AsNoTracking() on up.PositionId equals p.Id where u.IsActive && p.IsActive orderby u.DisplayName select new TrainingEmployeeOptionResponse(u.Id, u.DisplayName, p.Id, p.Name)).ToListAsync(ct); var documents = await (from d in db.ControlledDocuments.AsNoTracking() join r in db.DocumentRevisions.AsNoTracking() on d.CurrentRevisionId equals r.Id where d.Status != Qms.Domain.Documents.ControlledDocumentStatus.Archived orderby d.DocumentCode select new TrainingDocumentOptionResponse(d.Id, r.Id, d.DocumentCode, d.Title, r.MajorVersion + "." + r.MinorVersion)).ToListAsync(ct); var positions = await db.Positions.AsNoTracking().Where(p => p.IsActive).OrderBy(p => p.Name).Select(p => new TrainingPositionOptionResponse(p.Id, p.Code, p.Name, null)).ToListAsync(ct); var defs = await db.TrainingLookupDefinitions.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync(ct); IReadOnlyList<TrainingLookupOptionResponse> Values(string c) => defs.Where(x => x.Category == c).Select(x => new TrainingLookupOptionResponse(x.Code, x.Name)).ToList(); return new(employees, documents, positions, Values("AssessmentMode"), Values("DeliveryMethod")); }
    public async Task<IReadOnlyList<TrainingLookupDefinitionResponse>> ListLookupDefinitionsAsync(CancellationToken ct) => await db.TrainingLookupDefinitions.AsNoTracking().OrderBy(x => x.Category).ThenBy(x => x.SortOrder).Select(x => new TrainingLookupDefinitionResponse(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive)).ToListAsync(ct);
    public async Task<TrainingLookupDefinitionResponse> CreateLookupDefinitionAsync(CreateTrainingLookupDefinitionRequest r, CancellationToken ct) { var category = r.Category.Trim(); if (!LookupCategories.Contains(category)) throw new ArgumentException("M.05 lookup kategorisi geçersizdir."); if (await db.TrainingLookupDefinitions.AnyAsync(x => x.Category == category && x.Code == r.Code.Trim(), ct)) throw new InvalidOperationException("Aynı kategori ve kodla lookup zaten mevcut."); var now = clock.GetUtcNow(); var x = TrainingLookupDefinition.Create(category, r.Code, r.Name, r.SortOrder, now); db.TrainingLookupDefinitions.Add(x); db.AuditEvents.Add(AuditEvent.Create("TrainingLookupDefinition", x.Id, 1, "TrainingLookupCreated", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { x.Category, x.Code, x.Name, x.SortOrder }))); await db.SaveChangesAsync(ct); return new(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive); }
    public async Task<TrainingLookupDefinitionResponse?> UpdateLookupDefinitionAsync(Guid id, UpdateTrainingLookupDefinitionRequest r, CancellationToken ct) { var x = await db.TrainingLookupDefinitions.SingleOrDefaultAsync(x => x.Id == id, ct); if (x is null) return null; var now = clock.GetUtcNow(); x.Update(r.Name, r.SortOrder, r.IsActive, now); db.AuditEvents.Add(AuditEvent.Create("TrainingLookupDefinition", x.Id, 1, "TrainingLookupUpdated", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { x.Category, x.Code, x.Name, x.SortOrder, x.IsActive }))); await db.SaveChangesAsync(ct); return new(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive); }
    private IQueryable<Row> BaseRows(bool include = false) { var assignments = include ? db.TrainingAssignments.AsNoTracking().Include(x => x.Attempts) : db.TrainingAssignments.AsNoTracking(); return from a in assignments join qr in db.QualityRecords.AsNoTracking() on a.QualityRecordId equals qr.Id join d in db.ControlledDocuments.AsNoTracking() on a.ControlledDocumentId equals d.Id into ds from d in ds.DefaultIfEmpty() join rev in db.DocumentRevisions.AsNoTracking() on a.DocumentRevisionId equals rev.Id into revs from rev in revs.DefaultIfEmpty() select new Row { Assignment = a, RecordNumber = qr.RecordNumber, DocumentCode = d == null ? null : d.DocumentCode, DocumentMajor = rev == null ? (int?)null : rev.MajorVersion, DocumentMinor = rev == null ? (int?)null : rev.MinorVersion }; }
    private async Task SyncDocumentRequirement(TrainingAssignment a, DateTimeOffset now, CancellationToken ct) { if (a.DocumentTrainingRequirementId is not Guid req || a.ControlledDocumentId is not Guid docId) return; if (await db.TrainingAssignments.AnyAsync(x => x.DocumentTrainingRequirementId == req && x.Id != a.Id && x.Status != TrainingAssignmentStatus.Completed, ct)) return; var d = await db.ControlledDocuments.Include(x => x.Revisions).Include(x => x.TrainingRequirements).SingleAsync(x => x.Id == docId, ct); var count = await db.TrainingAssignments.CountAsync(x => x.DocumentTrainingRequirementId == req && x.Id != a.Id && x.Status == TrainingAssignmentStatus.Completed, ct) + 1; d.CompleteTraining(d.Version, req, $"{a.CourseCode} · {count} çalışan · M.05 yeterlilik zinciri tamamlandı", now); db.AuditEvents.Add(AuditEvent.Create("Document", d.Id, d.Version, "DocumentTrainingCompleted", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { trainingAssignmentId = a.Id, requirementId = req, completedEmployeeCount = count, source = "M.05" }))); }
    private async Task AssignTrainer(TrainingAssignment a, DateTimeOffset now, CancellationToken ct) { var trainer = await (from ur in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on ur.RoleId equals role.Id join target in db.Users.AsNoTracking() on ur.UserId equals target.Id where (role.Name == QmsRoles.Trainer || role.Name == QmsRoles.TrainingCoordinator || role.Name == QmsRoles.DepartmentManager || role.Name == QmsRoles.QualityAssurance) && target.IsActive && target.Id != a.EmployeeUserId orderby role.Name == QmsRoles.Trainer ? 0 : role.Name == QmsRoles.TrainingCoordinator ? 1 : 2, target.DisplayName select target.Id).FirstOrDefaultAsync(ct); if (trainer == Guid.Empty) throw new InvalidOperationException("Eğitim için atanabilir etkin bir eğitmen bulunamadı."); await Assign(a.Id, WorkflowTaskRoles.Trainer, trainer, now, a.DueAtUtc, ct); }
    private async Task Assign(Guid id, string role, Guid userId, DateTimeOffset now, DateTimeOffset? due, CancellationToken ct) { var target = await db.Users.AsNoTracking().SingleAsync(x => x.Id == userId && x.IsActive, ct); var dep = target.DepartmentId is Guid did ? await db.Departments.AsNoTracking().Where(x => x.Id == did).Select(x => x.Name).SingleOrDefaultAsync(ct) : null; db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Training", id, role, target.Id, target.DepartmentId, now, due, null, target.DisplayName, dep)); db.UserNotifications.Add(UserNotification.Create(target.Id, "M.05", "Eğitim görevi atandı", $"{role} görevi size atandı.", $"/modules/m05?open={id}", now)); }
    private async Task EnsureActor(Guid id, string role, CancellationToken ct) { if (!await CanAct(id, role, ct)) throw new QmsForbiddenException("Bu eğitim görevi size veya etkin bir delegasyonla size atanmamış."); }
    private async Task<bool> CanAct(Guid id, string role, CancellationToken ct) { if (await db.WorkflowTaskAssignments.AsNoTracking().AnyAsync(x => x.AggregateType == "Training" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active && x.AssignedUserId == user.Id, ct)) return true; var assigned = await db.WorkflowTaskAssignments.AsNoTracking().Where(x => x.AggregateType == "Training" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active).Select(x => x.AssignedUserId).ToListAsync(ct); var now = clock.GetUtcNow(); return await db.Delegations.AsNoTracking().AnyAsync(x => assigned.Contains(x.DelegatorUserId) && x.DelegateUserId == user.Id && x.RevokedAtUtc == null && x.StartsAtUtc <= now && x.EndsAtUtc >= now && (x.Scope == "M.05" || x.Scope == "ALL"), ct); }
    private async Task<IReadOnlyList<string>> CurrentTaskRoles(Guid id, CancellationToken ct) { var active = await db.WorkflowTaskAssignments.AsNoTracking().Where(x => x.AggregateType == "Training" && x.AggregateId == id && x.Status == WorkflowTaskStatus.Active).ToListAsync(ct); var result = new List<string>(); foreach (var role in active.Select(x => x.TaskRole).Distinct()) if (await CanAct(id, role, ct)) result.Add(role); return result; }
    private async Task CompleteTasks(Guid id, string role, DateTimeOffset now, CancellationToken ct) { var tasks = await db.WorkflowTaskAssignments.Where(x => x.AggregateType == "Training" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active).ToListAsync(ct); foreach (var t in tasks) t.Complete(now); }
    private async Task CompleteAllTasks(Guid id, DateTimeOffset now, CancellationToken ct) { var tasks = await db.WorkflowTaskAssignments.Where(x => x.AggregateType == "Training" && x.AggregateId == id && x.Status == WorkflowTaskStatus.Active).ToListAsync(ct); foreach (var t in tasks) t.Complete(now); }
    private async Task<(Guid Id, string Name)> Position(Guid id, CancellationToken ct) => await db.Positions.AsNoTracking().Where(x => x.Id == id && x.IsActive).Select(x => new ValueTuple<Guid, string>(x.Id, x.Name)).SingleOrDefaultAsync(ct) is var p && p.Item1 != Guid.Empty ? p : throw new ArgumentException("Etkin pozisyon bulunamadı.");
    private async Task<(string Name, Guid? DepartmentId)> Employee(Guid id, Guid positionId, CancellationToken ct) { var x = await db.Users.AsNoTracking().Where(x => x.Id == id && x.IsActive).Select(x => new { x.DisplayName, x.DepartmentId }).SingleOrDefaultAsync(ct) ?? throw new ArgumentException("Etkin çalışan bulunamadı."); if (!await db.UserPositions.AsNoTracking().AnyAsync(p => p.UserId == id && p.PositionId == positionId && p.EndsAtUtc == null, ct)) throw new ArgumentException("Seçilen pozisyon çalışanın etkin organizasyon ataması değildir."); return (x.DisplayName, x.DepartmentId); }
    private async Task<TrainingAssessmentMode> Mode(string code, CancellationToken ct) { await Lookup("AssessmentMode", code, ct); return Enum.TryParse<TrainingAssessmentMode>(code, true, out var v) ? v : throw new ArgumentException("Değerlendirme yöntemi geçersiz."); }
    private async Task<TrainingDeliveryMethod> Delivery(string code, CancellationToken ct) { await Lookup("DeliveryMethod", code, ct); return Enum.TryParse<TrainingDeliveryMethod>(code, true, out var v) ? v : throw new ArgumentException("Eğitim yöntemi geçersiz."); }
    private async Task Lookup(string category, string code, CancellationToken ct) { if (!await db.TrainingLookupDefinitions.AsNoTracking().AnyAsync(x => x.Category == category && x.Code == code.Trim() && x.IsActive, ct)) throw new ArgumentException($"Seçilen {category} tanımı etkin lookup kayıtlarında bulunamadı."); }
    private Task<TrainingAssignment?> Load(Guid id, CancellationToken ct) => db.TrainingAssignments.Include(x => x.Attempts).SingleOrDefaultAsync(x => x.Id == id, ct); private void EnsureManager() { if (!user.IsInRole(QmsRoles.Administrator) && !user.IsInRole(QmsRoles.TrainingCoordinator) && !user.IsInRole(QmsRoles.QualityAssurance)) throw new QmsForbiddenException("Eğitim planlama için Eğitim Koordinatörü veya KG rolü gerekir."); }
    private static IReadOnlyList<TrainingTransitionResponse> Transitions(TrainingAssignmentStatus s, IReadOnlyList<string> roles) { var all = s switch { TrainingAssignmentStatus.Planned => new[] { new TrainingTransitionResponse("assign", "Çalışana ata", false) }, TrainingAssignmentStatus.Assigned => [new("start", "Eğitimi başlat", false), new("cancel", "İptal et", true)], TrainingAssignmentStatus.InProgress => [new("submit-assessment", "Değerlendirmeye gönder", false), new("cancel", "İptal et", true)], TrainingAssignmentStatus.TrainerApproval => [new("approve", "Yeterliliği onayla", true)], TrainingAssignmentStatus.Failed or TrainingAssignmentStatus.Expired => [new("reassign", "Yeniden ata", false)], TrainingAssignmentStatus.Completed => [new("expire", "Süresini doldu olarak işaretle", false)], _ => [] }; return all.Where(x => roles.Contains(x.Code switch { "start" or "submit-assessment" => WorkflowTaskRoles.Learner, "approve" => WorkflowTaskRoles.Trainer, _ => WorkflowTaskRoles.TrainingCoordinator })).ToList(); }
    private AuditEvent Audit(TrainingAssignment a, string type, DateTimeOffset now, object payload, string? reason = null) => AuditEvent.Create("Training", a.Id, a.Version, type, user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(payload), reason);
    private static IQueryable<Row> Filter(IQueryable<Row> q, ColumnFilterRequest f) { var field = f.Field.Trim().ToLowerInvariant(); var op = f.Operator.Trim().ToLowerInvariant(); var v = f.Value?.Trim() ?? ""; return field switch { "recordnumber" => Txt(q, op, v, 0), "employeename" => Txt(q, op, v, 1), "position" => Txt(q, op, v, 2), "coursecode" => Txt(q, op, v, 3), "coursetitle" => Txt(q, op, v, 4), "documentcode" => Txt(q, op, v, 5), "status" => Enum.TryParse<TrainingAssignmentStatus>(v, true, out var s) ? q.Where(x => x.Assignment.Status == s) : throw new ArgumentException("Eğitim durumu geçersiz."), "assessmentmode" => Enum.TryParse<TrainingAssessmentMode>(v, true, out var m) ? q.Where(x => x.Assignment.AssessmentMode == m) : throw new ArgumentException("Değerlendirme türü geçersiz."), "iscriticalqualification" => bool.TryParse(v, out var b) ? q.Where(x => x.Assignment.IsCriticalQualification == b) : q, "dueatutc" => Date(q, op, f.Value, f.ValueTo, true), "expiresatutc" => Date(q, op, f.Value, f.ValueTo, false), _ => throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}") }; }
    private static IQueryable<Row> Txt(IQueryable<Row> q, string op, string v, int f) => f switch { 0 => op == "equals" ? q.Where(x => x.RecordNumber == v) : q.Where(x => x.RecordNumber.ToLower().Contains(v.ToLower())), 1 => op == "equals" ? q.Where(x => x.Assignment.EmployeeName == v) : q.Where(x => x.Assignment.EmployeeName.ToLower().Contains(v.ToLower())), 2 => op == "equals" ? q.Where(x => x.Assignment.Position == v) : q.Where(x => x.Assignment.Position.ToLower().Contains(v.ToLower())), 3 => op == "equals" ? q.Where(x => x.Assignment.CourseCode == v) : q.Where(x => x.Assignment.CourseCode.ToLower().Contains(v.ToLower())), 4 => op == "equals" ? q.Where(x => x.Assignment.CourseTitle == v) : q.Where(x => x.Assignment.CourseTitle.ToLower().Contains(v.ToLower())), _ => op == "equals" ? q.Where(x => x.DocumentCode == v) : q.Where(x => x.DocumentCode != null && x.DocumentCode.ToLower().Contains(v.ToLower())) };
    private static IQueryable<Row> Date(IQueryable<Row> q, string op, string? a, string? b, bool due) { var from = DateTimeOffset.Parse(a ?? "", CultureInfo.InvariantCulture).ToUniversalTime(); var to = string.IsNullOrWhiteSpace(b) ? from.AddDays(1) : DateTimeOffset.Parse(b, CultureInfo.InvariantCulture).ToUniversalTime(); return (op, due) switch { ("before", true) => q.Where(x => x.Assignment.DueAtUtc < from), ("after", true) => q.Where(x => x.Assignment.DueAtUtc > from), (_, true) => q.Where(x => x.Assignment.DueAtUtc >= from && x.Assignment.DueAtUtc < to), ("before", false) => q.Where(x => x.Assignment.ExpiresAtUtc < from), ("after", false) => q.Where(x => x.Assignment.ExpiresAtUtc > from), _ => q.Where(x => x.Assignment.ExpiresAtUtc >= from && x.Assignment.ExpiresAtUtc < to) }; }
    private static IQueryable<Row> Sort(IQueryable<Row> q, string field, string dir) { var d = dir.Equals("desc", StringComparison.OrdinalIgnoreCase); return field.Trim().ToLowerInvariant() switch { "recordnumber" => d ? q.OrderByDescending(x => x.RecordNumber) : q.OrderBy(x => x.RecordNumber), "employeename" => d ? q.OrderByDescending(x => x.Assignment.EmployeeName) : q.OrderBy(x => x.Assignment.EmployeeName), "coursecode" => d ? q.OrderByDescending(x => x.Assignment.CourseCode) : q.OrderBy(x => x.Assignment.CourseCode), "status" => d ? q.OrderByDescending(x => x.Assignment.Status) : q.OrderBy(x => x.Assignment.Status), "dueatutc" => d ? q.OrderByDescending(x => x.Assignment.DueAtUtc) : q.OrderBy(x => x.Assignment.DueAtUtc), _ => d ? q.OrderByDescending(x => x.Assignment.CreatedAtUtc) : q.OrderBy(x => x.Assignment.CreatedAtUtc) }; }
    private async Task<long> NextNumber(int year, IDbContextTransaction tx, CancellationToken ct) { var c = db.Database.GetDbConnection(); if (c.State != ConnectionState.Open) await c.OpenAsync(ct); await using var cmd = c.CreateCommand(); cmd.Transaction = tx.GetDbTransaction(); cmd.CommandText = "INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@recordType, @calendarYear, 1) ON CONFLICT (\"RecordType\", \"CalendarYear\") DO UPDATE SET \"LastValue\" = core.record_number_sequence.\"LastValue\" + 1 RETURNING \"LastValue\";"; Add(cmd, "recordType", "training"); Add(cmd, "calendarYear", year); return Convert.ToInt64(await cmd.ExecuteScalarAsync(ct), CultureInfo.InvariantCulture); }
    private static void Add(DbCommand c, string n, object v) { var p = c.CreateParameter(); p.ParameterName = n; p.Value = v; c.Parameters.Add(p); }
    private sealed class Row { public required TrainingAssignment Assignment { get; init; } public required string RecordNumber { get; init; } public string? DocumentCode { get; init; } public int? DocumentMajor { get; init; } public int? DocumentMinor { get; init; } }
}
