using Qms.Domain.ExternalAudits;
namespace Qms.Domain.Tests.ExternalAudits;
public sealed class ExternalAuditTests
{
    private static readonly DateTimeOffset Now=new(2026,8,25,12,0,0,TimeSpan.Zero);
    [Fact] public void Government_Audit_Requires_Authorized_Closer(){var error=Assert.Throws<ArgumentException>(()=>Create(government:true,closerId:null));Assert.Contains("Mesul Müdür",error.Message);}
    [Fact] public void Controlled_Package_Must_Be_Exported_Before_Audit_Starts(){var audit=Create();audit.Transition(1,"start-preparation",null,Now);Assert.Throws<InvalidOperationException>(()=>audit.Transition(2,"start-audit",null,Now));var request=audit.DocumentRequests.Single();var access=audit.ExportDocument(2,request.Id,Guid.NewGuid(),"Doküman Kontrol","EMA denetim ekibi","Resmi talep paketi","EXP-2026-001 SHA256",Now);audit.Transition(3,"start-audit",null,Now);Assert.Equal(1,access.ExportVersion);Assert.Equal(ExternalAuditStatus.AuditInProgress,audit.Status);}
    [Fact] public void Open_Capa_And_Missing_Acceptance_Block_Closure(){var audit=Create(government:true,closerId:Guid.NewGuid());audit.Transition(1,"start-preparation",null,Now);var request=audit.DocumentRequests.Single();audit.ExportDocument(2,request.Id,Guid.NewGuid(),"Doküman Kontrol","TİTCK denetim ekibi","Resmi talep","EXP-001",Now);audit.Transition(3,"start-audit",null,Now);var finding=ExternalAuditFinding.Create(audit.Id,"DBG-2026-000001","Yetki matrisi güncel değil","Pozisyon değişikliği matrise işlenmemiş.","TİTCK-01",ExternalAuditFindingClassification.Major,true,Guid.NewGuid(),"İK Müdürü",Now.AddDays(20),Now);audit.AddFinding(4,finding,Now);audit.Transition(5,"complete-audit",null,Now);audit.Transition(6,"open-response-plan",null,Now);audit.RespondFinding(7,finding.Id,"Bulgu kabul edilmiştir.","Matris revize edilip eğitim tamamlanacaktır.",Now.AddDays(15),Now);audit.Transition(8,"start-capa-actions",null,Now);Assert.Throws<InvalidOperationException>(()=>audit.CloseFinding(9,finding.Id,"Kanıt incelendi.",false,Now));audit.CloseFinding(9,finding.Id,"DÖF kapanışı ve etkinlik kanıtı doğrulandı.",true,Now);audit.Transition(10,"complete-capa-actions",null,Now);audit.RecordClosureLetter(11,"TİTCK-KP-2026-17",Now,"Kapanış mektubu sisteme alındı.",false,Now);Assert.Throws<InvalidOperationException>(()=>audit.Transition(12,"submit-authority-closure",null,Now));}
    private static ExternalAudit Create(bool government=false,Guid? closerId=null)=>ExternalAudit.Create(Guid.NewGuid(),"Üretim tesisi dış denetimi",government?"Otorite denetimi":"Müşteri denetimi",government?"TİTCK":"Global Pharma",government,"Türkiye","EXT-2026-41","GMP ve veri bütünlüğü","İstanbul Üretim Tesisi","Dış Denetim Koordinatörü",Now.AddDays(-2),Now.AddDays(2),Now.AddDays(4),Now.AddDays(20),closerId,closerId.HasValue?"Mesul Müdür":null,[(null,"SOP-QA-001","Kalite Sistemleri Prosedürü","Kurum İçi")],Now);
}
