using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Qms.Application.Documents;
using Qms.Application.ElectronicSignatures;
using Qms.Application.Security;
using Qms.Contracts.Common;
using Qms.Contracts.Documents;
using Qms.Domain.AuditTrail;
using Qms.Domain.Documents;
using Qms.Domain.Notifications;
using Qms.Domain.QualityRecords;
using Qms.Domain.Trainings;
using Qms.Domain.Workflows;
using Qms.Infrastructure.Persistence;

namespace Qms.Infrastructure.Documents;

public sealed class DocumentService(QmsDbContext db, TimeProvider clock, ICurrentUser user, IElectronicSignatureService signatures) : IDocumentService
{
    private static readonly HashSet<string> LookupCategories = ["DocumentType", "Confidentiality"];

    public async Task<DocumentLookupsResponse> GetLookupsAsync(CancellationToken ct)
    {
        var owners = await (from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.IsActive orderby u.DisplayName select new DocumentUserOptionResponse(u.Id, u.DisplayName, d == null ? null : d.Name)).ToListAsync(ct);
        var departments = new List<DocumentDepartmentOptionResponse>();
        foreach (var department in await db.Departments.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.Name).ToListAsync(ct)) { var reviewer = await ResolveDepartmentReviewerAsync(department.Id, null, ct); if (reviewer is not null) departments.Add(new(department.Id, department.Code, department.Name, reviewer.Value.Id, reviewer.Value.Name)); }
        var positions = await db.Positions.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.Name).Select(x => new DocumentPositionOptionResponse(x.Id, x.Code, x.Name, null)).ToListAsync(ct);
        var definitions = await db.DocumentLookupDefinitions.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync(ct);
        IReadOnlyList<DocumentLookupOptionResponse> Values(string category) => definitions.Where(x => x.Category == category).Select(x => new DocumentLookupOptionResponse(x.Code, x.Name)).ToList();
        return new(owners, departments, positions, Values("DocumentType"), Values("Confidentiality"));
    }

    public async Task<IReadOnlyList<DocumentLookupDefinitionResponse>> ListLookupDefinitionsAsync(CancellationToken ct) => await db.DocumentLookupDefinitions.AsNoTracking().OrderBy(x => x.Category).ThenBy(x => x.SortOrder).ThenBy(x => x.Name).Select(x => new DocumentLookupDefinitionResponse(x.Id, x.Category, x.Code, x.Name, x.SortOrder, x.IsActive)).ToListAsync(ct);

    public async Task<DocumentLookupDefinitionResponse> CreateLookupDefinitionAsync(CreateDocumentLookupDefinitionRequest request, CancellationToken ct)
    {
        var category = request.Category.Trim();
        if (!LookupCategories.Contains(category)) throw new ArgumentException("M.04 lookup kategorisi geçersizdir.");
        var code = request.Code.Trim();
        if (await db.DocumentLookupDefinitions.AnyAsync(x => x.Category == category && x.Code == code, ct)) throw new InvalidOperationException("Aynı kategori ve kodla bir lookup zaten mevcut.");
        var now = clock.GetUtcNow(); var item = DocumentLookupDefinition.Create(category, code, request.Name, request.SortOrder, now); db.DocumentLookupDefinitions.Add(item);
        db.AuditEvents.Add(AuditEvent.Create("DocumentLookupDefinition", item.Id, 1, "DocumentLookupCreated", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { item.Category, item.Code, item.Name, item.SortOrder })));
        await db.SaveChangesAsync(ct); return new(item.Id, item.Category, item.Code, item.Name, item.SortOrder, item.IsActive);
    }

    public async Task<DocumentLookupDefinitionResponse?> UpdateLookupDefinitionAsync(Guid id, UpdateDocumentLookupDefinitionRequest request, CancellationToken ct)
    {
        var item = await db.DocumentLookupDefinitions.SingleOrDefaultAsync(x => x.Id == id, ct); if (item is null) return null; var now = clock.GetUtcNow(); item.Update(request.Name, request.SortOrder, request.IsActive, now);
        db.AuditEvents.Add(AuditEvent.Create("DocumentLookupDefinition", item.Id, 1, "DocumentLookupUpdated", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { item.Category, item.Code, item.Name, item.SortOrder, item.IsActive })));
        await db.SaveChangesAsync(ct); return new(item.Id, item.Category, item.Code, item.Name, item.SortOrder, item.IsActive);
    }

    public async Task<PagedResponse<ControlledDocumentListItemResponse>> SearchAsync(ControlledDocumentSearchRequest request, CancellationToken ct)
    {
        if (request.Page < 1 || request.PageSize is not (10 or 25 or 50 or 100)) throw new ArgumentException("Sayfa ve sayfa boyutu geçersizdir.");
        var query = from document in db.ControlledDocuments.AsNoTracking()
                    join record in db.QualityRecords.AsNoTracking() on document.QualityRecordId equals record.Id
                    join revision in db.DocumentRevisions.AsNoTracking() on document.CurrentRevisionId equals revision.Id
                    join source in db.ChangeControls.AsNoTracking() on document.SourceChangeControlId equals source.Id into sources
                    from source in sources.DefaultIfEmpty()
                    join sourceRecord in db.QualityRecords.AsNoTracking() on source.QualityRecordId equals sourceRecord.Id into sourceRecords
                    from sourceRecord in sourceRecords.DefaultIfEmpty()
                    select new DocumentRow { Document = document, Revision = revision, RecordNumber = record.RecordNumber, SourceRecordNumber = sourceRecord == null ? null : sourceRecord.RecordNumber };
        foreach (var filter in request.Filters ?? []) query = ApplyFilter(query, filter);
        var total = await query.LongCountAsync(ct); query = ApplySort(query, request.SortBy, request.SortDirection);
        var items = await query.Skip((request.Page - 1) * request.PageSize).Take(request.PageSize).Select(x => new ControlledDocumentListItemResponse(
            x.Document.Id, x.RecordNumber, x.Document.SourceChangeControlId, x.SourceRecordNumber, x.Document.DocumentCode, x.Document.Title, x.Document.DocumentType, x.Document.Owner, x.Document.Department, x.Document.Confidentiality,
            x.Revision.MajorVersion + "." + x.Revision.MinorVersion, x.Document.Status.ToString(), x.Document.PlannedEffectiveDateUtc, x.Document.NextReviewDateUtc,
            x.Document.Reviews.Count(r => r.RevisionId == x.Document.CurrentRevisionId && r.Status == DocumentReviewStatus.Pending),
            x.Document.TrainingRequirements.Count(t => t.RevisionId == x.Document.CurrentRevisionId && t.Status == DocumentTrainingStatus.Pending), x.Document.CreatedAtUtc, x.Document.Version)).ToListAsync(ct);
        return new(items, request.Page, request.PageSize, total, total == 0 ? 0 : (int)Math.Ceiling(total / (double)request.PageSize));
    }

    public async Task<ControlledDocumentDetailsResponse?> GetDetailsAsync(Guid id, CancellationToken ct)
    {
        var item = await (from document in db.ControlledDocuments.AsNoTracking().Include(x => x.Revisions).Include(x => x.Reviews).Include(x => x.TrainingRequirements).Include(x => x.Copies).Include(x => x.ReadReceipts)
                          join qr in db.QualityRecords.AsNoTracking() on document.QualityRecordId equals qr.Id
                          join source in db.ChangeControls.AsNoTracking() on document.SourceChangeControlId equals source.Id into sources from source in sources.DefaultIfEmpty()
                          join sourceRecord in db.QualityRecords.AsNoTracking() on source.QualityRecordId equals sourceRecord.Id into sourceRecords from sourceRecord in sourceRecords.DefaultIfEmpty()
                          where document.Id == id select new { Document = document, RecordNumber = qr.RecordNumber, SourceRecordNumber = sourceRecord == null ? null : sourceRecord.RecordNumber }).SingleOrDefaultAsync(ct);
        if (item is null) return null;
        var d = item.Document; var current = d.Revisions.Single(x => x.Id == d.CurrentRevisionId);
        var auditEvents = await db.AuditEvents.AsNoTracking().Where(x => x.AggregateType == "Document" && x.AggregateId == id).OrderByDescending(x => x.OccurredAtUtc).ToListAsync(ct);
        var signatures = await db.ElectronicSignatures.AsNoTracking().Where(x => x.QualityRecordId == d.QualityRecordId).OrderBy(x => x.SignedAtUtc).Select(x => new DocumentSignatureResponse(x.Id, x.RecordVersion, x.SignerUserId, x.SignerDisplayNameSnapshot, x.Meaning, x.SignedAtUtc, x.ContentHash, x.Comment)).ToListAsync(ct);
        var responseRecord = new ControlledDocumentResponse(d.Id, d.QualityRecordId, item.RecordNumber, d.SourceChangeControlId, item.SourceRecordNumber, d.DocumentCode, d.Title, d.DocumentType, d.OwnerUserId, d.Owner, d.DepartmentId, d.Department, d.Confidentiality, d.ReviewPeriodMonths, d.PlannedEffectiveDateUtc, d.NextReviewDateUtc, d.CurrentRevisionId, current.VersionLabel, d.Status.ToString(), d.WithdrawalReason, d.CreatedAtUtc, d.UpdatedAtUtc, d.ArchivedAtUtc, d.Version);
        return new(responseRecord,
            d.Revisions.OrderByDescending(x => x.MajorVersion).ThenByDescending(x => x.MinorVersion).Select(x => new DocumentRevisionResponse(x.Id, x.VersionLabel, x.Content, x.ChangeSummary, x.PreparedBy, x.Status.ToString(), x.CreatedAtUtc, x.ApprovedAtUtc, x.EffectiveAtUtc, x.Id == d.CurrentRevisionId)).ToList(),
            d.Reviews.OrderByDescending(x => x.RevisionId == d.CurrentRevisionId).ThenBy(x => x.Department).Select(x => new DocumentReviewResponse(x.Id, x.RevisionId, x.DepartmentId, x.Department, x.ReviewerUserId, x.Reviewer, x.Status.ToString(), x.Comment, x.CompletedAtUtc)).ToList(),
            d.TrainingRequirements.OrderByDescending(x => x.RevisionId == d.CurrentRevisionId).ThenBy(x => x.Position).Select(x => new DocumentTrainingResponse(x.Id, x.RevisionId, x.PositionId, x.Position, x.AssignedUser, x.Status.ToString(), x.Evidence, x.CompletedAtUtc)).ToList(),
            d.Copies.OrderByDescending(x => x.IssuedAtUtc).Select(x => new ControlledCopyResponse(x.Id, x.RevisionId, x.CopyNumber, x.Recipient, x.Purpose, x.Status.ToString(), x.IssuedAtUtc, x.DueBackAtUtc, x.ReturnedAtUtc, x.DestroyedAtUtc)).ToList(),
            d.ReadReceipts.OrderByDescending(x => x.AcknowledgedAtUtc).Select(x => new DocumentReadReceiptResponse(x.Id, x.RevisionId, x.UserId, x.UserDisplayName, x.SignatureMeaning, x.AcknowledgedAtUtc)).ToList(),
            auditEvents.Select(x => new DocumentAuditEventResponse(x.Id, x.AggregateVersion, x.EventType, x.ActorDisplayNameSnapshot, x.OccurredAtUtc, x.Reason, x.Payload.RootElement.Clone())).ToList(), signatures, (await CanCurrentUserPerformAsync(id, RequiredTaskRole(d.Status), ct)) ? Transitions(d.Status) : [], await GetCurrentUserTaskRolesAsync(id, ct));
    }

    public async Task<ControlledDocumentDetailsResponse> CreateAsync(CreateControlledDocumentRequest request, CancellationToken ct)
    {
        if (request.SourceChangeControlId is Guid source && !await db.ChangeControls.AnyAsync(x => x.Id == source, ct)) throw new ArgumentException("Kaynak M.03 değişiklik kontrolü bulunamadı.");
        if (await db.ControlledDocuments.AnyAsync(x => x.DocumentCode == request.DocumentCode.Trim(), ct)) throw new ArgumentException("Doküman kodu daha önce kullanılmış.");
        var now = clock.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var sequence = await NextRecordNumberAsync(now.Year, tx, ct); var number = $"DOC-{now.Year}-{sequence:000000}";
        await EnsureActiveLookupAsync("DocumentType", request.DocumentType, ct); await EnsureActiveLookupAsync("Confidentiality", request.Confidentiality, ct);
        var creatorDepartmentId = user.DepartmentId ?? throw new InvalidOperationException("Doküman oluşturacak kullanıcının etkin bir organizasyon bölümü olmalıdır."); var owner = await ActiveUserAsync(request.OwnerUserId, ct); var department = await db.Departments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == request.DepartmentId && x.IsActive, ct) ?? throw new ArgumentException("Seçilen doküman bölümü etkin değil.");
        var reviews = await ResolveReviewInputsAsync(request.ReviewDepartmentIds ?? [], qrCreatorId: user.Id, ct); var trainings = await ResolveTrainingInputsAsync(request.TrainingPositionIds ?? [], ct);
        var qr = QualityRecord.Create(number, "document", user.Id, creatorDepartmentId, now);
        var document = ControlledDocument.Create(qr.Id, request.SourceChangeControlId, request.DocumentCode, request.Title, request.DocumentType, owner.Id, owner.Name, department.Id, department.Name, request.Confidentiality, request.ReviewPeriodMonths, request.PlannedEffectiveDateUtc.ToUniversalTime(), request.Content, request.ChangeSummary, reviews, trainings, now);
        db.QualityRecords.Add(qr); db.ControlledDocuments.Add(document); await AssignUserAsync(document.Id, WorkflowTaskRoles.DocumentAuthor, owner.Id, now, request.PlannedEffectiveDateUtc, ct); db.AuditEvents.Add(Audit(document, "DocumentCreated", now, new { number, request.DocumentCode, request.SourceChangeControlId, ownerUserId = owner.Id, departmentId = department.Id }));
        await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return (await GetDetailsAsync(document.Id, ct))!;
    }

    public async Task<ControlledDocumentDetailsResponse?> UpdateDraftAsync(Guid id, UpdateDocumentDraftRequest r, CancellationToken ct) { await EnsureActorAsync(id, WorkflowTaskRoles.DocumentAuthor, ct); return await Mutate(id, ct, (d, now) => { d.UpdateDraft(r.ExpectedVersion, r.Content, r.ChangeSummary, now); return ("DocumentDraftUpdated", (object)new { d.CurrentRevision.VersionLabel }, r.ChangeSummary); }); }
    public async Task<ControlledDocumentDetailsResponse?> CompleteReviewAsync(Guid id, Guid reviewId, CompleteDocumentReviewRequest r, CancellationToken ct) { await EnsureActorAsync(id, $"DocumentReview:{reviewId}", ct); var result = await Mutate(id, ct, (d, now) => { d.CompleteReview(r.ExpectedVersion, reviewId, r.Approved, r.Comment, now); return (r.Approved ? "DocumentReviewApproved" : "DocumentChangesRequested", (object)new { reviewId, r.Approved }, r.Comment); }); if (result is not null) { await CompleteTasksAsync(id, $"DocumentReview:{reviewId}", clock.GetUtcNow(), ct); await db.SaveChangesAsync(ct); } return result; }
    public async Task<ControlledDocumentDetailsResponse?> CompleteTrainingAsync(Guid id, Guid requirementId, CompleteDocumentTrainingRequest r, CancellationToken ct) { await EnsureActorAsync(id, WorkflowTaskRoles.DocumentCoordinator, ct); if (await db.TrainingAssignments.AnyAsync(x => x.DocumentTrainingRequirementId == requirementId, ct)) throw new InvalidOperationException("Bu gereksinim M.05 eğitim kaydına bağlıdır ve yalnız M.05 süreci tamamlanarak kapatılabilir."); return await Mutate(id, ct, (d, now) => { d.CompleteTraining(r.ExpectedVersion, requirementId, r.Evidence, now); return ("DocumentTrainingCompleted", (object)new { requirementId }, r.Evidence); }); }
    public async Task<ControlledDocumentDetailsResponse?> StartRevisionAsync(Guid id, StartDocumentRevisionRequest r, CancellationToken ct) { await EnsureActorAsync(id, WorkflowTaskRoles.DocumentAuthor, ct); var reviews = await ResolveReviewInputsAsync(r.ReviewDepartmentIds ?? [], user.Id, ct); var trainings = await ResolveTrainingInputsAsync(r.TrainingPositionIds ?? [], ct); return await Mutate(id, ct, (d, now) => { d.StartRevision(r.ExpectedVersion, r.Major, r.ChangeSummary, reviews, trainings, now); db.DocumentRevisions.Add(d.CurrentRevision); db.DocumentReviews.AddRange(d.Reviews.Where(x => x.RevisionId == d.CurrentRevisionId)); db.DocumentTrainingRequirements.AddRange(d.TrainingRequirements.Where(x => x.RevisionId == d.CurrentRevisionId)); return ("DocumentRevisionStarted", (object)new { r.Major, d.CurrentRevision.VersionLabel }, r.ChangeSummary); }); }
    public async Task<ControlledDocumentDetailsResponse?> IssueCopyAsync(Guid id, IssueControlledCopyRequest r, CancellationToken ct) { await EnsureActorAsync(id, WorkflowTaskRoles.DocumentCoordinator, ct); return await Mutate(id, ct, (d, now) => { var copy = d.IssueCopy(r.ExpectedVersion, r.CopyNumber, r.Recipient, r.Purpose, r.DueBackAtUtc?.ToUniversalTime(), now); db.ControlledDocumentCopies.Add(copy); return ("ControlledCopyIssued", (object)new { copy.Id, copy.CopyNumber, copy.Recipient }, r.Purpose); }); }
    public async Task<ControlledDocumentDetailsResponse?> CloseCopyAsync(Guid id, Guid copyId, CloseControlledCopyRequest r, CancellationToken ct) { await EnsureActorAsync(id, WorkflowTaskRoles.DocumentCoordinator, ct); return await Mutate(id, ct, (d, now) => { d.CloseCopy(r.ExpectedVersion, copyId, r.Destroyed, now); return (r.Destroyed ? "ControlledCopyDestroyed" : "ControlledCopyReturned", (object)new { copyId }, (string?)null); }); }
    public async Task<ControlledDocumentDetailsResponse?> AcknowledgeReadAsync(Guid id, AcknowledgeDocumentReadRequest r, CancellationToken ct) { await signatures.AuthenticateAsync(r.SignaturePassword, r.SignatureMeaningAccepted, ct); var result = await Mutate(id, ct, (d, now) => { var receipt = d.Acknowledge(r.ExpectedVersion, user.Id, user.DisplayName, r.SignatureMeaning, now); db.DocumentReadReceipts.Add(receipt); db.ElectronicSignatures.Add(signatures.CreateInternal(d.QualityRecordId, "Document", d.Id, d.Version, "read-acknowledgement", r.SignatureMeaning, new { document = d, revision = d.CurrentRevision, receipt }, now, r.SignatureMeaning)); return ("DocumentReadAcknowledged", (object)new { receipt.Id, receipt.RevisionId }, r.SignatureMeaning); }); return result; }

    public async Task<ControlledDocumentDetailsResponse?> TransitionAsync(Guid id, TransitionDocumentRequest request, CancellationToken ct)
    {
        var document = await LoadAsync(id, ct); if (document is null) return null; var qr = await db.QualityRecords.SingleAsync(x => x.Id == document.QualityRecordId, ct); var transition = request.Transition.Trim().ToLowerInvariant(); var now = clock.GetUtcNow(); var from = document.Status;
        var requiredTask = TransitionTaskRole(transition); if (requiredTask is not null) await EnsureActorAsync(id, requiredTask, ct);
        if (transition is "approve" or "release" or "withdraw" or "archive" && qr.CreatedByUserId == user.Id) throw new QmsForbiddenException("Görev ayrılığı kuralı: Dokümanı hazırlayan kullanıcı aynı dokümanın onay veya yürürlük kararını veremez.");
        if (IsSignatureTransition(transition)) await signatures.AuthenticateAsync(request.SignaturePassword, request.SignatureMeaningAccepted, ct);
        await using var tx = await db.Database.BeginTransactionAsync(ct); document.Transition(request.ExpectedVersion, transition, request.Note, request.RequiresRevision, now);
        switch (transition)
        {
            case "start-writing": qr.Submit(now); break;
            case "submit-review": await CompleteTasksAsync(id, WorkflowTaskRoles.DocumentAuthor, now, ct); foreach (var review in document.Reviews.Where(x => x.RevisionId == document.CurrentRevisionId)) await AssignUserAsync(id, $"DocumentReview:{review.Id}", review.ReviewerUserId ?? await ResolveLegacyReviewUserAsync(review, qr.CreatedByUserId, ct), now, document.PlannedEffectiveDateUtc, ct); await AssignUserAsync(id, WorkflowTaskRoles.DocumentCoordinator, document.OwnerUserId ?? await ResolveLegacyOwnerAsync(document.Owner, ct), now, document.PlannedEffectiveDateUtc, ct); break;
            case "submit-approval": foreach (var review in document.Reviews.Where(x => x.RevisionId == document.CurrentRevisionId)) await CompleteTasksAsync(id, $"DocumentReview:{review.Id}", now, ct); await CompleteTasksAsync(id, WorkflowTaskRoles.DocumentCoordinator, now, ct); await AssignRoleAsync(id, WorkflowTaskRoles.DocumentApprover, QmsRoles.Approver, qr.CreatedByUserId, now, document.PlannedEffectiveDateUtc, ct); break;
            case "approve": await CompleteTasksAsync(id, WorkflowTaskRoles.DocumentApprover, now, ct); if (document.Status == ControlledDocumentStatus.TrainingWaiting) await CreateTrainingAssignmentsAsync(document, now, tx, ct); await AssignRoleAsync(id, WorkflowTaskRoles.DocumentCoordinator, document.Status == ControlledDocumentStatus.TrainingWaiting ? QmsRoles.TrainingCoordinator : QmsRoles.DocumentController, qr.CreatedByUserId, now, document.PlannedEffectiveDateUtc, ct); break;
            case "release": await CompleteTasksAsync(id, WorkflowTaskRoles.DocumentCoordinator, now, ct); await AssignRoleAsync(id, WorkflowTaskRoles.DocumentCoordinator, QmsRoles.DocumentController, qr.CreatedByUserId, now, document.NextReviewDateUtc, ct); break;
            case "request-revision": await CompleteTasksAsync(id, WorkflowTaskRoles.DocumentCoordinator, now, ct); await AssignUserAsync(id, WorkflowTaskRoles.DocumentAuthor, document.OwnerUserId ?? await ResolveLegacyOwnerAsync(document.Owner, ct), now, document.PlannedEffectiveDateUtc, ct); break;
            case "archive": qr.Close(now, false); break;
        }
        if (IsSignatureTransition(transition)) db.ElectronicSignatures.Add(signatures.CreateInternal(qr.Id, "Document", document.Id, document.Version, transition, SignatureMeaning(transition), new { document, revisions = document.Revisions, reviews = document.Reviews, trainingRequirements = document.TrainingRequirements, copies = document.Copies, transition, request.Note }, now, request.Note));
        db.AuditEvents.Add(Audit(document, "DocumentStatusChanged", now, new { from = from.ToString(), to = document.Status.ToString(), transition }, request.Note)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct);
    }

    private async Task<ControlledDocumentDetailsResponse?> Mutate(Guid id, CancellationToken ct, Func<ControlledDocument, DateTimeOffset, (string Type, object Payload, string? Reason)> action)
    { var document = await LoadAsync(id, ct); if (document is null) return null; var now = clock.GetUtcNow(); await using var tx = await db.Database.BeginTransactionAsync(ct); var evt = action(document, now); db.AuditEvents.Add(Audit(document, evt.Type, now, evt.Payload, evt.Reason)); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetDetailsAsync(id, ct); }
    private Task<ControlledDocument?> LoadAsync(Guid id, CancellationToken ct) => db.ControlledDocuments.Include(x => x.Revisions).Include(x => x.Reviews).Include(x => x.TrainingRequirements).Include(x => x.Copies).Include(x => x.ReadReceipts).SingleOrDefaultAsync(x => x.Id == id, ct);
    private AuditEvent Audit(ControlledDocument d, string type, DateTimeOffset now, object payload, string? reason = null) => AuditEvent.Create("Document", d.Id, d.Version, type, user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(payload), reason);

    private static IReadOnlyList<DocumentTransitionResponse> Transitions(ControlledDocumentStatus s) => s switch { ControlledDocumentStatus.Draft => [new("start-writing", "Yazımı başlat", false)], ControlledDocumentStatus.Writing => [new("submit-review", "İncelemeye gönder", false)], ControlledDocumentStatus.Review => [new("submit-approval", "Onaya gönder", false)], ControlledDocumentStatus.Approval => [new("approve", "Dokümanı onayla", false)], ControlledDocumentStatus.Approved or ControlledDocumentStatus.TrainingWaiting => [new("release", "Yürürlüğe al", false)], ControlledDocumentStatus.Effective => [new("request-revision", "Revizyon talep et", false), new("start-periodic-review", "Periyodik gözden geçirme", false), new("withdraw", "Yürürlükten kaldır", true)], ControlledDocumentStatus.RevisionPending => [], ControlledDocumentStatus.PeriodicReview => [new("complete-periodic-review", "Gözden geçirmeyi tamamla", true)], ControlledDocumentStatus.Withdrawn => [new("archive", "Arşivle", false)], _ => [] };
    private static IQueryable<DocumentRow> ApplyFilter(IQueryable<DocumentRow> q, ColumnFilterRequest f) { var field = f.Field.Trim().ToLowerInvariant(); var op = f.Operator.Trim().ToLowerInvariant(); var v = f.Value?.Trim() ?? ""; return field switch { "recordnumber" => Text(q, op, v, 0), "sourcerecordnumber" => Text(q, op, v, 1), "documentcode" => Text(q, op, v, 2), "title" => Text(q, op, v, 3), "owner" => Text(q, op, v, 4), "department" => op == "equals" ? q.Where(x => x.Document.Department == v) : q.Where(x => x.Document.Department.ToLower().Contains(v.ToLower())), "documenttype" => q.Where(x => x.Document.DocumentType == v), "confidentiality" => q.Where(x => x.Document.Confidentiality == v), "status" => Enum.TryParse<ControlledDocumentStatus>(v, true, out var status) ? q.Where(x => x.Document.Status == status) : throw new ArgumentException("Doküman durumu geçersizdir."), "plannedeffectivedateutc" => Date(q, op, f.Value, f.ValueTo, 0), "nextreviewdateutc" => Date(q, op, f.Value, f.ValueTo, 1), "createdatutc" => Date(q, op, f.Value, f.ValueTo, 2), _ => throw new ArgumentException($"Filtrelenmesine izin verilmeyen kolon: {f.Field}") }; }
    private static IQueryable<DocumentRow> Text(IQueryable<DocumentRow> q, string op, string v, int f) => f switch { 0 => op == "equals" ? q.Where(x => x.RecordNumber == v) : q.Where(x => x.RecordNumber.ToLower().Contains(v.ToLower())), 1 => op == "equals" ? q.Where(x => x.SourceRecordNumber == v) : q.Where(x => x.SourceRecordNumber != null && x.SourceRecordNumber.ToLower().Contains(v.ToLower())), 2 => op == "equals" ? q.Where(x => x.Document.DocumentCode == v) : q.Where(x => x.Document.DocumentCode.ToLower().Contains(v.ToLower())), 3 => op == "equals" ? q.Where(x => x.Document.Title == v) : q.Where(x => x.Document.Title.ToLower().Contains(v.ToLower())), _ => op == "equals" ? q.Where(x => x.Document.Owner == v) : q.Where(x => x.Document.Owner.ToLower().Contains(v.ToLower())) };
    private static IQueryable<DocumentRow> Date(IQueryable<DocumentRow> q, string op, string? a, string? b, int f) { var from = DateTimeOffset.Parse(a ?? "", CultureInfo.InvariantCulture).ToUniversalTime(); var to = string.IsNullOrWhiteSpace(b) ? from.AddDays(1) : DateTimeOffset.Parse(b, CultureInfo.InvariantCulture).ToUniversalTime(); return (f, op) switch { (0, "before") => q.Where(x => x.Document.PlannedEffectiveDateUtc < from), (0, "after") => q.Where(x => x.Document.PlannedEffectiveDateUtc > from), (0, _) => q.Where(x => x.Document.PlannedEffectiveDateUtc >= from && x.Document.PlannedEffectiveDateUtc < to), (1, "before") => q.Where(x => x.Document.NextReviewDateUtc < from), (1, "after") => q.Where(x => x.Document.NextReviewDateUtc > from), (1, _) => q.Where(x => x.Document.NextReviewDateUtc >= from && x.Document.NextReviewDateUtc < to), (2, "before") => q.Where(x => x.Document.CreatedAtUtc < from), (2, "after") => q.Where(x => x.Document.CreatedAtUtc > from), _ => q.Where(x => x.Document.CreatedAtUtc >= from && x.Document.CreatedAtUtc < to) }; }
    private static IQueryable<DocumentRow> ApplySort(IQueryable<DocumentRow> q, string f, string direction) { var d = direction.Equals("desc", StringComparison.OrdinalIgnoreCase); return f.Trim().ToLowerInvariant() switch { "recordnumber" => d ? q.OrderByDescending(x => x.RecordNumber) : q.OrderBy(x => x.RecordNumber), "documentcode" => d ? q.OrderByDescending(x => x.Document.DocumentCode) : q.OrderBy(x => x.Document.DocumentCode), "title" => d ? q.OrderByDescending(x => x.Document.Title) : q.OrderBy(x => x.Document.Title), "owner" => d ? q.OrderByDescending(x => x.Document.Owner) : q.OrderBy(x => x.Document.Owner), "status" => d ? q.OrderByDescending(x => x.Document.Status) : q.OrderBy(x => x.Document.Status), "plannedeffectivedateutc" => d ? q.OrderByDescending(x => x.Document.PlannedEffectiveDateUtc) : q.OrderBy(x => x.Document.PlannedEffectiveDateUtc), _ => d ? q.OrderByDescending(x => x.Document.CreatedAtUtc) : q.OrderBy(x => x.Document.CreatedAtUtc) }; }
    private async Task EnsureActorAsync(Guid id, string role, CancellationToken ct) { if (!await CanCurrentUserPerformAsync(id, role, ct)) throw new QmsForbiddenException("Bu doküman görevi size veya etkin bir delegasyonla size atanmamış."); }
    private void EnsureRole(params string[] roles) { if (user.IsInRole(QmsRoles.Administrator) || roles.Any(user.IsInRole)) return; throw new QmsForbiddenException("Bu doküman işlemi için gerekli sistem rolü sizde bulunmuyor."); }
    private async Task CompleteTasksAsync(Guid id, string role, DateTimeOffset now, CancellationToken ct) { var tasks = await db.WorkflowTaskAssignments.Where(x => x.AggregateType == "Document" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active).ToListAsync(ct); foreach (var task in tasks) task.Complete(now); }
    private async Task AssignRoleAsync(Guid id, string taskRole, string roleName, Guid? excluded, DateTimeOffset now, DateTimeOffset? due, CancellationToken ct) { var userId = await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id join target in db.Users.AsNoTracking() on link.UserId equals target.Id where role.Name == roleName && target.IsActive && target.Id != excluded orderby target.DisplayName select target.Id).FirstOrDefaultAsync(ct); if (userId == Guid.Empty) throw new InvalidOperationException($"{roleName} rolünde atanabilir etkin kullanıcı bulunamadı."); await AssignUserAsync(id, taskRole, userId, now, due, ct); }
    private async Task AssignUserAsync(Guid id, string taskRole, Guid userId, DateTimeOffset now, DateTimeOffset? due, CancellationToken ct) { var target = await (from u in db.Users.AsNoTracking() join d in db.Departments.AsNoTracking() on u.DepartmentId equals d.Id into ds from d in ds.DefaultIfEmpty() where u.Id == userId && u.IsActive select new { u.Id, u.DisplayName, u.DepartmentId, DepartmentName = d == null ? null : d.Name }).SingleOrDefaultAsync(ct) ?? throw new InvalidOperationException("Doküman görevi için seçilen kullanıcı etkin değil."); db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Document", id, taskRole, target.Id, target.DepartmentId, now, due, assignedUserNameSnapshot: target.DisplayName, assignedDepartmentNameSnapshot: target.DepartmentName)); db.UserNotifications.Add(UserNotification.Create(target.Id, "M.04", "Yeni doküman görevi", $"{TaskRoleLabel(taskRole)} görevi size atandı.", $"/modules/documents?open={id}", now)); }
    private async Task<bool> CanCurrentUserPerformAsync(Guid id, string? role, CancellationToken ct) { if (role is null) return false; var owners = await db.WorkflowTaskAssignments.AsNoTracking().Where(x => x.AggregateType == "Document" && x.AggregateId == id && x.TaskRole == role && x.Status == WorkflowTaskStatus.Active).Select(x => x.AssignedUserId).ToListAsync(ct); if (owners.Contains(user.Id)) return true; if (owners.Count == 0) return false; var now = clock.GetUtcNow(); return await db.Delegations.AsNoTracking().AnyAsync(x => owners.Contains(x.DelegatorUserId) && x.DelegateUserId == user.Id && x.RevokedAtUtc == null && x.StartsAtUtc <= now && x.EndsAtUtc >= now && (x.Scope == "ALL" || x.Scope == "M.04"), ct); }
    private async Task<IReadOnlyList<string>> GetCurrentUserTaskRolesAsync(Guid id, CancellationToken ct) { var assignments = await db.WorkflowTaskAssignments.AsNoTracking().Where(x => x.AggregateType == "Document" && x.AggregateId == id && x.Status == WorkflowTaskStatus.Active).Select(x => new { x.TaskRole, x.AssignedUserId }).ToListAsync(ct); var roles = assignments.Where(x => x.AssignedUserId == user.Id).Select(x => x.TaskRole).ToHashSet(); var owners = assignments.Select(x => x.AssignedUserId).Distinct().ToList(); var now = clock.GetUtcNow(); var delegated = await db.Delegations.AsNoTracking().Where(x => owners.Contains(x.DelegatorUserId) && x.DelegateUserId == user.Id && x.RevokedAtUtc == null && x.StartsAtUtc <= now && x.EndsAtUtc >= now && (x.Scope == "ALL" || x.Scope == "M.04")).Select(x => x.DelegatorUserId).ToListAsync(ct); foreach (var role in assignments.Where(x => delegated.Contains(x.AssignedUserId)).Select(x => x.TaskRole)) roles.Add(role); return roles.OrderBy(x => x).ToList(); }
    private async Task CreateTrainingAssignmentsAsync(ControlledDocument document, DateTimeOffset now, IDbContextTransaction tx, CancellationToken ct)
    {
        var candidates = from target in db.Users.AsNoTracking()
                         join link in db.UserPositions.AsNoTracking().Where(x => x.EndsAtUtc == null && x.IsPrimary) on target.Id equals link.UserId
                         join position in db.Positions.AsNoTracking() on link.PositionId equals position.Id
                         where target.IsActive
                         orderby target.DisplayName
                         select new TrainingEmployee(target.Id, target.DisplayName, position.Id, position.Name, target.DepartmentId);
        var candidateList = await candidates.ToListAsync(ct);
        var coordinators = await (from link in db.UserRoles.AsNoTracking()
                                  join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id
                                  join target in db.Users.AsNoTracking() on link.UserId equals target.Id
                                  join department in db.Departments.AsNoTracking() on target.DepartmentId equals department.Id into departments
                                  from department in departments.DefaultIfEmpty()
                                  where role.Name == QmsRoles.TrainingCoordinator && target.IsActive
                                  orderby target.DisplayName
                                  select new { target.Id, target.DisplayName, target.DepartmentId, DepartmentName = department == null ? null : department.Name }).ToListAsync(ct);
        if (coordinators.Count == 0) throw new InvalidOperationException("Doküman eğitimleri için atanabilir etkin bir Eğitim Koordinatörü bulunamadı.");
        foreach (var requirement in document.TrainingRequirements.Where(x => x.RevisionId == document.CurrentRevisionId && x.Status == DocumentTrainingStatus.Pending))
        {
            if (await db.TrainingAssignments.AnyAsync(x => x.DocumentTrainingRequirementId == requirement.Id, ct)) continue;
            var employees = candidateList.Where(x => requirement.PositionId.HasValue ? x.PositionId == requirement.PositionId : x.Position.Equals(requirement.Position, StringComparison.OrdinalIgnoreCase)).ToList();
            if (employees.Count == 0) throw new InvalidOperationException($"{requirement.Position} pozisyonunda etkin çalışan bulunamadı.");
            foreach (var employee in employees)
            {
                var sequence = await NextRecordNumberAsync(now.Year, tx, ct, "training");
                var number = $"EGT-{now.Year}-{sequence:000000}";
                var employeeDepartmentId = employee.DepartmentId ?? throw new InvalidOperationException($"{employee.DisplayName} kullanıcısının organizasyon bölümü bulunmuyor."); var record = QualityRecord.Create(number, "training", user.Id, employeeDepartmentId, now); record.Submit(now);
                var assignment = TrainingAssignment.Create(record.Id, null, document.Id, document.CurrentRevisionId, requirement.Id, employee.Id, employee.DisplayName, requirement.PositionId ?? throw new InvalidOperationException("Doküman eğitim gereksiniminin pozisyon kimliği bulunamadı."), requirement.Position, document.DocumentCode, $"{document.Title} · Sürüm {document.CurrentRevision.VersionLabel}", TrainingAssessmentMode.ReadAndAcknowledge, TrainingDeliveryMethod.Electronic, 100, document.ReviewPeriodMonths, 3, true, document.PlannedEffectiveDateUtc, null, null, true, now);
                var coordinator = coordinators.FirstOrDefault(x => x.Id != employee.Id) ?? throw new InvalidOperationException($"{employee.DisplayName} çalışanından farklı atanabilir bir Eğitim Koordinatörü bulunamadı.");
                db.QualityRecords.Add(record); db.TrainingAssignments.Add(assignment);
                db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Training", assignment.Id, WorkflowTaskRoles.TrainingCoordinator, coordinator.Id, coordinator.DepartmentId, now, document.PlannedEffectiveDateUtc, assignedUserNameSnapshot: coordinator.DisplayName, assignedDepartmentNameSnapshot: coordinator.DepartmentName));
                db.WorkflowTaskAssignments.Add(WorkflowTaskAssignment.Create("Training", assignment.Id, WorkflowTaskRoles.Learner, employee.Id, employee.DepartmentId, now, document.PlannedEffectiveDateUtc, assignedUserNameSnapshot: employee.DisplayName, assignedDepartmentNameSnapshot: null));
                db.UserNotifications.Add(UserNotification.Create(coordinator.Id, "M.05", "Yeni eğitim koordinasyon görevi", $"{number} numaralı doküman eğitiminin koordinasyonu size atandı.", $"/modules/m05?open={assignment.Id}", now));
                db.UserNotifications.Add(UserNotification.Create(employee.Id, "M.05", "Yeni eğitim görevi", $"{document.DocumentCode} doküman eğitimi size atandı.", $"/modules/m05?open={assignment.Id}", now));
                db.AuditEvents.Add(AuditEvent.Create("Training", assignment.Id, assignment.Version, "TrainingAssignmentCreatedFromDocument", user.Id, user.DisplayName, now, Guid.CreateVersion7().ToString(), JsonSerializer.SerializeToDocument(new { number, documentId = document.Id, documentRevisionId = document.CurrentRevisionId, requirementId = requirement.Id, employeeId = employee.Id })));
            }
        }
    }
    private async Task<IReadOnlyList<(Guid DepartmentId, string Department, Guid ReviewerUserId, string Reviewer)>> ResolveReviewInputsAsync(IReadOnlyList<Guid> ids, Guid qrCreatorId, CancellationToken ct)
    {
        var requested = ids.ToHashSet(); var qa = await db.Departments.AsNoTracking().SingleOrDefaultAsync(x => x.Code == "KG" && x.IsActive, ct) ?? throw new InvalidOperationException("Kalite Güvence bölümü organizasyonda etkin değil."); requested.Add(qa.Id); var result = new List<(Guid, string, Guid, string)>();
        foreach (var id in requested) { var department = await db.Departments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.IsActive, ct) ?? throw new ArgumentException("Seçilen inceleme bölümü etkin değil."); var reviewer = await ResolveDepartmentReviewerAsync(id, qrCreatorId, ct) ?? throw new InvalidOperationException($"{department.Name} için etkin doküman inceleyicisi bulunamadı."); result.Add((department.Id, department.Name, reviewer.Id, reviewer.Name)); }
        return result;
    }
    private async Task<IReadOnlyList<(Guid PositionId, string Position)>> ResolveTrainingInputsAsync(IReadOnlyList<Guid> ids, CancellationToken ct) { var rows = await db.Positions.AsNoTracking().Where(x => ids.Contains(x.Id) && x.IsActive).OrderBy(x => x.Name).Select(x => new { x.Id, x.Name }).ToListAsync(ct); if (rows.Count != ids.Distinct().Count()) throw new ArgumentException("Seçilen eğitim pozisyonlarından biri etkin değil."); return rows.Select(x => (x.Id, x.Name)).ToList(); }
    private async Task<(Guid Id, string Name)> ActiveUserAsync(Guid id, CancellationToken ct) { var target = await db.Users.AsNoTracking().Where(x => x.Id == id && x.IsActive).Select(x => new { x.Id, x.DisplayName }).SingleOrDefaultAsync(ct) ?? throw new ArgumentException("Seçilen doküman sahibi etkin değil."); return (target.Id, target.DisplayName); }
    private async Task<(Guid Id, string Name)?> ResolveDepartmentReviewerAsync(Guid departmentId, Guid? excluded, CancellationToken ct) { var department = await db.Departments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == departmentId && x.IsActive, ct); if (department is null) return null; if (department.ManagerUserId is Guid managerId && managerId != excluded) { var manager = await db.Users.AsNoTracking().Where(x => x.Id == managerId && x.IsActive).Select(x => new { x.Id, x.DisplayName }).SingleOrDefaultAsync(ct); if (manager is not null) return (manager.Id, manager.DisplayName); } var roleName = department.Code == "KG" ? QmsRoles.QualityAssurance : department.Code == "RUH" ? QmsRoles.RegulatoryAffairs : QmsRoles.DepartmentManager; var candidate = await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id join target in db.Users.AsNoTracking() on link.UserId equals target.Id where role.Name == roleName && target.IsActive && target.DepartmentId == departmentId && target.Id != excluded orderby target.DisplayName select new { target.Id, target.DisplayName }).FirstOrDefaultAsync(ct); return candidate is null ? null : (candidate.Id, candidate.DisplayName); }
    private async Task<Guid> ResolveLegacyReviewUserAsync(DocumentReview review, Guid excluded, CancellationToken ct) { var departmentId = review.DepartmentId ?? await db.Departments.AsNoTracking().Where(x => x.IsActive && x.Name == review.Department).Select(x => (Guid?)x.Id).SingleOrDefaultAsync(ct) ?? throw new InvalidOperationException($"{review.Department} bölümü organizasyonda bulunamadı."); return (await ResolveDepartmentReviewerAsync(departmentId, excluded, ct) ?? throw new InvalidOperationException($"{review.Department} için inceleyici bulunamadı.")).Id; }
    private async Task<Guid> ResolveLegacyOwnerAsync(string snapshot, CancellationToken ct) { var id = await db.Users.AsNoTracking().Where(x => x.IsActive && x.DisplayName == snapshot).Select(x => x.Id).FirstOrDefaultAsync(ct); if (id != Guid.Empty) return id; id = await (from link in db.UserRoles.AsNoTracking() join role in db.Roles.AsNoTracking() on link.RoleId equals role.Id join target in db.Users.AsNoTracking() on link.UserId equals target.Id where role.Name == QmsRoles.DocumentController && target.IsActive orderby target.DisplayName select target.Id).FirstOrDefaultAsync(ct); return id == Guid.Empty ? throw new InvalidOperationException("Eski doküman için atanabilir sahip bulunamadı.") : id; }
    private async Task EnsureActiveLookupAsync(string category, string code, CancellationToken ct) { if (!await db.DocumentLookupDefinitions.AsNoTracking().AnyAsync(x => x.Category == category && x.Code == code.Trim() && x.IsActive, ct)) throw new ArgumentException($"Seçilen {category} tanımı etkin lookup kayıtlarında bulunamadı."); }
    private static bool IsSignatureTransition(string transition) => transition is "approve" or "release" or "complete-periodic-review" or "withdraw" or "archive";
    private static string SignatureMeaning(string transition) => transition switch { "approve" => "Doküman sürüm onayı", "release" => "Dokümanı yürürlüğe alma onayı", "complete-periodic-review" => "Periyodik gözden geçirme kararı", "withdraw" => "Dokümanı yürürlükten kaldırma kararı", "archive" => "Doküman arşivleme onayı", _ => "Doküman kararı" };
    private static string? TransitionTaskRole(string transition) => transition switch { "start-writing" or "submit-review" => WorkflowTaskRoles.DocumentAuthor, "submit-approval" or "release" or "request-revision" or "start-periodic-review" or "complete-periodic-review" or "withdraw" or "archive" => WorkflowTaskRoles.DocumentCoordinator, "approve" => WorkflowTaskRoles.DocumentApprover, _ => null };
    private static string? RequiredTaskRole(ControlledDocumentStatus status) => status switch { ControlledDocumentStatus.Draft or ControlledDocumentStatus.Writing or ControlledDocumentStatus.RevisionPending => WorkflowTaskRoles.DocumentAuthor, ControlledDocumentStatus.Review or ControlledDocumentStatus.Approved or ControlledDocumentStatus.TrainingWaiting or ControlledDocumentStatus.Effective or ControlledDocumentStatus.PeriodicReview or ControlledDocumentStatus.Withdrawn => WorkflowTaskRoles.DocumentCoordinator, ControlledDocumentStatus.Approval => WorkflowTaskRoles.DocumentApprover, _ => null };
    private static string TaskRoleLabel(string role) => role.StartsWith("DocumentReview:") ? "Doküman incelemesi" : role switch { WorkflowTaskRoles.DocumentAuthor => "Doküman yazarlığı", WorkflowTaskRoles.DocumentApprover => "Doküman onayı", WorkflowTaskRoles.DocumentCoordinator => "Doküman koordinasyonu", _ => role };
    private async Task<long> NextRecordNumberAsync(int year, IDbContextTransaction tx, CancellationToken ct, string recordType = "document") { var connection = db.Database.GetDbConnection(); if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.Transaction = tx.GetDbTransaction(); command.CommandText = "INSERT INTO core.record_number_sequence (\"RecordType\", \"CalendarYear\", \"LastValue\") VALUES (@recordType, @calendarYear, 1) ON CONFLICT (\"RecordType\", \"CalendarYear\") DO UPDATE SET \"LastValue\" = core.record_number_sequence.\"LastValue\" + 1 RETURNING \"LastValue\";"; Add(command, "recordType", recordType); Add(command, "calendarYear", year); return Convert.ToInt64(await command.ExecuteScalarAsync(ct), CultureInfo.InvariantCulture); }
    private static void Add(DbCommand command, string name, object value) { var p = command.CreateParameter(); p.ParameterName = name; p.Value = value; command.Parameters.Add(p); }
    private sealed class DocumentRow { public required ControlledDocument Document { get; init; } public required DocumentRevision Revision { get; init; } public required string RecordNumber { get; init; } public string? SourceRecordNumber { get; init; } }
    private sealed record TrainingEmployee(Guid Id, string DisplayName, Guid PositionId, string Position, Guid? DepartmentId);
}
