using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using PdfSharp.Fonts;
using Qms.Application.SupplierAudits;
using Qms.Contracts.SupplierAudits;

namespace Qms.Infrastructure.SupplierAudits;

public sealed class SupplierAuditFinalReportService(IConfiguration configuration) : ISupplierAuditFinalReportService
{
    private const string FontFamily = "QmsDejaVuSans"; private static readonly Lock FontLock = new();
    public async Task<SupplierAuditFinalReportFile> EnsureGeneratedAsync(SupplierAuditDetailsResponse d, CancellationToken ct)
    {
        if (d.Record.Status != "Closed") throw new InvalidOperationException("Nihai PDF yalnız kapatılmış tedarikçi denetimleri için üretilebilir.");
        var root = configuration["FileStorage:RootPath"] ?? Path.Combine(AppContext.BaseDirectory, "qms-files"); var directory = Path.Combine(root, "supplier-audits", d.Record.Id.ToString("N")); Directory.CreateDirectory(directory);
        var safe = string.Concat(d.Record.RecordNumber.Select(c => char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '_')); var fileName = $"{safe}-nihai-tedarikci-denetimi-v{d.Record.Version}.pdf"; var path = Path.Combine(directory, fileName); var hashPath = path + ".sha256";
        if (!File.Exists(path)) { EnsureFont(); var bytes = Build(d, SnapshotHash(d)); try { await File.WriteAllBytesAsync(path, bytes, ct); } catch (IOException) when (File.Exists(path)) { } var hash = Convert.ToHexStringLower(SHA256.HashData(await File.ReadAllBytesAsync(path, ct))); try { await File.WriteAllTextAsync(hashPath, hash, Encoding.ASCII, ct); } catch (IOException) when (File.Exists(hashPath)) { } }
        var content = await File.ReadAllBytesAsync(path, ct); var actual = Convert.ToHexStringLower(SHA256.HashData(content)); var expected = (await File.ReadAllTextAsync(hashPath, ct)).Trim(); if (!CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(actual), Encoding.ASCII.GetBytes(expected))) throw new InvalidOperationException("Nihai M.09 PDF bütünlük doğrulamasını geçemedi."); return new(content, fileName, actual);
    }
    private static byte[] Build(SupplierAuditDetailsResponse d, string snapshotHash)
    {
        var r = d.Record; var document = new Document { Info = { Title = $"{r.RecordNumber} Nihai Tedarikçi Denetimi", Author = "QMS" } }; document.Styles["Normal"]!.Font.Name = FontFamily; document.Styles["Normal"]!.Font.Size = 9;
        var s = document.AddSection(); s.PageSetup.PageFormat = PageFormat.A4; s.PageSetup.TopMargin = Unit.FromCentimeter(1.4); s.PageSetup.BottomMargin = Unit.FromCentimeter(1.6); s.PageSetup.LeftMargin = s.PageSetup.RightMargin = Unit.FromCentimeter(1.5); Brand(s, "QMS  |  M.09 TEDARİKÇİ DENETİMİ"); var title = s.AddParagraph($"{r.SupplierName} · {r.SupplierScope}"); title.Format.Font.Size = 19; title.Format.Font.Bold = true; title.Format.Font.Color = Color.Parse("#0F5F61"); s.AddParagraph($"{r.RecordNumber} | Kayıt sürümü {r.Version} | NİHAİ - KAPALI");
        Heading(s, "1. Tedarikçi, risk ve plan"); Grid(s, ["Tedarikçi kodu", r.SupplierCode, "Malzeme / hizmet", r.MaterialOrService, "Ülke / saha", $"{r.Country} / {r.Site}", "Kritiklik", r.Criticality, "Risk", $"{r.RiskScore} · {r.RiskBand}", "Önerilen sıklık", $"{r.RecommendedFrequencyMonths} ay", "Planlanan dönem", $"{F(r.PlannedStartUtc)} - {F(r.PlannedEndUtc)}", "Soru listesi", r.ChecklistVersion]); Block(s, "Kapsam", r.Scope);
        Heading(s, "2. Görev ayrılığı"); Grid(s, ["Baş denetçi", $"{r.LeadAuditor} · {r.LeadAuditorDepartment}", "Tedarikçi yanıt sorumlusu", r.PurchasingOwner, "Kanıt doğrulayıcısı", r.Verifier, "Kalite onaylayanı", r.QualityApprover]);
        Heading(s, "3. Soru listesi ve kanıtlar"); var checklist = Table(s, ["No / kategori", "Soru / referans", "Sonuç", "Kanıt / not"]); foreach (var x in d.Checklist) Row(checklist, $"{x.Order} · {x.Category}", $"{x.Question}\n{x.Reference}", ChecklistLabel(x.Status), $"{x.Evidence ?? "-"}\n{x.Note ?? "-"}");
        Heading(s, "4. Bulgular ve DÖF bağları"); var findings = Table(s, ["Bulgu", "Sınıf / DÖF", "Sorumlu / hedef", "Yanıt / doğrulama"]); foreach (var x in d.Findings) Row(findings, $"{x.Number}\n{x.Title}", $"{x.Classification} / {(x.CapaRequired ? x.LinkedCapaNumber ?? "DÖF" : "Gerekli değil")}", $"{x.Owner}\n{F(x.ResponseDueAtUtc)}", $"{x.SupplierResponse ?? "-"}\n{x.VerificationNote ?? "-"}");
        Heading(s, "5. Nitelendirme kararı ve e-imzalar"); Grid(s, ["Karar", QualificationLabel(r.QualificationStatus), "Geçerlilik", F(r.QualificationValidUntilUtc), "Yeniden nitelendirme", r.RequalificationRequired ? "Gerekli" : "Gerekli değil", "Gerekçe", r.ResultRationale ?? "-"]); var signatures = Table(s, ["Anlam", "İmzalayan", "Tarih / sürüm", "İçerik hash"]); foreach (var x in d.Signatures) Row(signatures, x.Meaning, x.SignedBy, $"{F(x.SignedAtUtc)} / v{x.RecordVersion}", x.Hash[..Math.Min(16, x.Hash.Length)] + "...");
        s.AddPageBreak(); Brand(s, $"{r.RecordNumber}  |  KONTROLLÜ DENETİM İZİ"); Heading(s, "6. Denetim izi"); var trail = Table(s, ["Sürüm / olay", "İşlemi yapan", "Tarih", "Gerekçe"]); foreach (var x in d.AuditTrail.OrderBy(x => x.Version)) Row(trail, $"v{x.Version} / {x.EventType}", x.Actor, F(x.OccurredAtUtc), x.Reason ?? "-"); var proof = s.AddParagraph(); proof.Format.SpaceBefore = 10; proof.Format.Shading.Color = Color.Parse("#EAF4F2"); proof.AddFormattedText("KAYIT SNAPSHOT SHA-256\n", TextFormat.Bold); proof.AddText(snapshotHash); var footer = s.Footers.Primary.AddParagraph(); footer.Format.Alignment = ParagraphAlignment.Center; footer.AddText($"{r.RecordNumber} | Sayfa "); footer.AddPageField(); footer.AddText(" / "); footer.AddNumPagesField(); var renderer = new PdfDocumentRenderer { Document = document }; renderer.RenderDocument(); using var stream = new MemoryStream(); renderer.PdfDocument.Save(stream, false); return stream.ToArray();
    }
    private static string ChecklistLabel(string value) => value switch { "Conform" => "Uygun", "Nonconform" => "Uygun değil", "NotApplicable" => "Uygulanamaz", _ => value };
    private static string QualificationLabel(string value) => value switch { "Approved" => "Onaylı", "Conditional" => "Koşullu", "Suspended" => "Askıda", "RequalificationRequired" => "Yeniden nitelendirme", "Rejected" => "Reddedildi", _ => value };
    private static void Brand(Section s,string v){var p=s.AddParagraph(v);p.Format.Font.Bold=true;p.Format.Font.Color=Color.Parse("#0F7773");} private static void Heading(Section s,string v){var p=s.AddParagraph(v);p.Format.Font.Size=13;p.Format.Font.Bold=true;p.Format.Font.Color=Color.Parse("#173C46");p.Format.SpaceBefore=9;p.Format.SpaceAfter=4;} private static void Block(Section s,string l,string v){var p=s.AddParagraph();p.Format.SpaceAfter=5;p.AddFormattedText(l+"\n",TextFormat.Bold);p.AddText(v);} private static void Grid(Section s,string[] v){var t=Table(s,["Alan","Değer"]);for(var i=0;i<v.Length;i+=2)Row(t,v[i],v[i+1]);} private static Table Table(Section s,string[] h){var t=s.AddTable();t.Borders.Color=Color.Parse("#CBD9D7");t.Borders.Width=.5;var w=17.4/h.Length;foreach(var _ in h)t.AddColumn(Unit.FromCentimeter(w));var r=t.AddRow();r.HeadingFormat=true;r.Shading.Color=Color.Parse("#EAF4F2");for(var i=0;i<h.Length;i++)Cell(r.Cells[i],h[i],true);return t;} private static void Row(Table t,params string[] v){var r=t.AddRow();for(var i=0;i<v.Length;i++)Cell(r.Cells[i],v[i]);} private static void Cell(Cell c,string v,bool b=false){var p=c.AddParagraph(v);p.Format.Font.Bold=b;p.Format.Font.Size=8;c.VerticalAlignment=VerticalAlignment.Center;} private static string SnapshotHash(SupplierAuditDetailsResponse d)=>Convert.ToHexStringLower(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(d))); private static string F(DateTimeOffset? v)=>v?.ToOffset(TimeSpan.FromHours(3)).ToString("dd.MM.yyyy HH:mm 'TRT'")??"-"; private static void EnsureFont(){if(GlobalFontSettings.FontResolver is not null)return;lock(FontLock)GlobalFontSettings.FontResolver??=new Resolver();} private sealed class Resolver:IFontResolver{private static readonly string Regular=Path.Combine("/usr/share/fonts/truetype/dejavu","DejaVuSans.ttf");private static readonly string Bold=Path.Combine("/usr/share/fonts/truetype/dejavu","DejaVuSans-Bold.ttf");public byte[] GetFont(string face)=>File.ReadAllBytes(face.EndsWith("Bold",StringComparison.Ordinal)?Bold:Regular);public FontResolverInfo ResolveTypeface(string family,bool bold,bool italic)=>new(bold?"QmsBold":"QmsRegular",false,false);}
}
