namespace Qms.Domain.InternalAudits;

public enum InternalAuditStatus { AnnualPlan, Preparation, PlanApproval, Execution, Findings, ResponseAction, CapaVerification, FindingClosure, AuditClosure, Closed, Cancelled }
public enum AuditAnswerStatus { Pending, Conform, Nonconform, NotApplicable }
public enum AuditFindingClassification { Critical, Major, Minor, Observation }
public enum AuditFindingStatus { Open, ResponseSubmitted, Verification, Closed }

public sealed class AuditChecklistItem
{
    private AuditChecklistItem() { }
    public Guid Id { get; private set; } public Guid InternalAuditId { get; private set; } public int Order { get; private set; } public string Question { get; private set; }=""; public string Reference { get; private set; }=""; public AuditAnswerStatus Status { get; private set; } public string? Evidence { get; private set; } public string? Note { get; private set; } public DateTimeOffset? AnsweredAtUtc { get; private set; }
    internal static AuditChecklistItem Create(Guid auditId,int order,string question,string reference){Text(question,nameof(question),1000);Text(reference,nameof(reference),300);return new(){Id=Guid.CreateVersion7(),InternalAuditId=auditId,Order=order,Question=question.Trim(),Reference=reference.Trim(),Status=AuditAnswerStatus.Pending};}
    internal void Answer(AuditAnswerStatus status,string evidence,string note,DateTimeOffset now){if(status==AuditAnswerStatus.Pending)throw new ArgumentException("Soru sonucu seçilmelidir.");if(status==AuditAnswerStatus.Nonconform)Text(evidence,nameof(evidence),3000);Status=status;Evidence=string.IsNullOrWhiteSpace(evidence)?null:evidence.Trim();Note=string.IsNullOrWhiteSpace(note)?null:note.Trim();AnsweredAtUtc=now;}
    private static void Text(string v,string n,int m){if(string.IsNullOrWhiteSpace(v)||v.Trim().Length>m)throw new ArgumentException($"{n} zorunludur ve en fazla {m} karakter olabilir.");}
}

public sealed class AuditFinding
{
    private AuditFinding() { }
    public Guid Id{get;private set;}public Guid InternalAuditId{get;private set;}public string Number{get;private set;}="";public string Title{get;private set;}="";public string Description{get;private set;}="";public string RequirementReference{get;private set;}="";public int Impact{get;private set;}public int Likelihood{get;private set;}public int RiskScore{get;private set;}public AuditFindingClassification Classification{get;private set;}public bool CapaRequired{get;private set;}public Guid? LinkedCapaId{get;private set;}public string Owner{get;private set;}="";public DateTimeOffset TargetDateUtc{get;private set;}public string? Response{get;private set;}public string? CorrectiveAction{get;private set;}public string? VerificationNote{get;private set;}public AuditFindingStatus Status{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public DateTimeOffset? ClosedAtUtc{get;private set;}
    public static AuditFinding Create(Guid auditId,string number,string title,string description,string reference,int impact,int likelihood,bool capaRequired,Guid? capaId,string owner,DateTimeOffset target,DateTimeOffset now){Text(title,nameof(title),240);Text(description,nameof(description),5000);Text(reference,nameof(reference),500);Text(owner,nameof(owner),200);if(impact is <1 or >5||likelihood is <1 or >5)throw new ArgumentException("Etki ve olasılık 1–5 arasında olmalıdır.");var score=impact*likelihood;var cls=score>=20?AuditFindingClassification.Critical:score>=12?AuditFindingClassification.Major:score>=6?AuditFindingClassification.Minor:AuditFindingClassification.Observation;if(cls is AuditFindingClassification.Critical or AuditFindingClassification.Major)capaRequired=true;if(capaRequired&&!capaId.HasValue)throw new InvalidOperationException("DÖF gerekli bulgu ilişkili M.02 kaydı olmadan oluşturulamaz.");return new(){Id=Guid.CreateVersion7(),InternalAuditId=auditId,Number=number,Title=title.Trim(),Description=description.Trim(),RequirementReference=reference.Trim(),Impact=impact,Likelihood=likelihood,RiskScore=score,Classification=cls,CapaRequired=capaRequired,LinkedCapaId=capaId,Owner=owner.Trim(),TargetDateUtc=target,Status=AuditFindingStatus.Open,CreatedAtUtc=now};}
    internal void Respond(string response,string action,DateTimeOffset now){Text(response,nameof(response),5000);Text(action,nameof(action),5000);Response=response.Trim();CorrectiveAction=action.Trim();Status=AuditFindingStatus.ResponseSubmitted;}
    internal void Close(string note,bool linkedCapaClosed,DateTimeOffset now){Text(note,nameof(note),3000);if(Status!=AuditFindingStatus.ResponseSubmitted&&Status!=AuditFindingStatus.Verification)throw new InvalidOperationException("Yanıtı olmayan bulgu kapatılamaz.");if(CapaRequired&&!linkedCapaClosed)throw new InvalidOperationException("İlişkili DÖF kapanmadan bulgu kapatılamaz.");VerificationNote=note.Trim();Status=AuditFindingStatus.Closed;ClosedAtUtc=now;}
    private static void Text(string v,string n,int m){if(string.IsNullOrWhiteSpace(v)||v.Trim().Length>m)throw new ArgumentException($"{n} zorunludur ve en fazla {m} karakter olabilir.");}
}

public sealed class InternalAudit
{
    private readonly List<AuditChecklistItem> _checklist=[];private readonly List<AuditFinding> _findings=[];private InternalAudit(){}
    public Guid Id{get;private set;}public Guid QualityRecordId{get;private set;}public int PlanYear{get;private set;}public string Title{get;private set;}="";public string AuditType{get;private set;}="";public string Scope{get;private set;}="";public string Objectives{get;private set;}="";public string Criteria{get;private set;}="";public string AuditeeDepartment{get;private set;}="";public Guid LeadAuditorUserId{get;private set;}public string LeadAuditor{get;private set;}="";public string LeadAuditorDepartment{get;private set;}="";public DateTimeOffset PlannedStartUtc{get;private set;}public DateTimeOffset PlannedEndUtc{get;private set;}public bool IsUnplanned{get;private set;}public string? UnplannedReason{get;private set;}public string ChecklistVersion{get;private set;}="";public DateTimeOffset? ChecklistLockedAtUtc{get;private set;}public bool IndependenceConfirmed{get;private set;}public string? Summary{get;private set;}public InternalAuditStatus Status{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public DateTimeOffset UpdatedAtUtc{get;private set;}public DateTimeOffset? ClosedAtUtc{get;private set;}public long Version{get;private set;}public IReadOnlyCollection<AuditChecklistItem> Checklist=>_checklist;public IReadOnlyCollection<AuditFinding> Findings=>_findings;
    public static InternalAudit Create(Guid qr,int year,string title,string type,string scope,string objectives,string criteria,string auditee,Guid auditorId,string auditor,string auditorDepartment,DateTimeOffset start,DateTimeOffset end,bool unplanned,string? reason,string checklistVersion,IEnumerable<(string Question,string Reference)> questions,DateTimeOffset now){if(qr==Guid.Empty||auditorId==Guid.Empty)throw new ArgumentException("Kalite kaydı ve baş denetçi zorunludur.");foreach(var(v,n,m)in new[]{(title,nameof(title),240),(type,nameof(type),100),(scope,nameof(scope),3000),(objectives,nameof(objectives),2000),(criteria,nameof(criteria),2000),(auditee,nameof(auditee),160),(auditor,nameof(auditor),200),(auditorDepartment,nameof(auditorDepartment),160),(checklistVersion,nameof(checklistVersion),80)})Text(v,n,m);if(end<=start)throw new ArgumentException("Denetim bitişi başlangıçtan sonra olmalıdır.");if(unplanned)Text(reason??"",nameof(reason),2000);var q=questions.Where(x=>!string.IsNullOrWhiteSpace(x.Question)).ToArray();if(q.Length==0)throw new ArgumentException("En az bir soru listesi maddesi gerekir.");var a=new InternalAudit{Id=Guid.CreateVersion7(),QualityRecordId=qr,PlanYear=year,Title=title.Trim(),AuditType=type.Trim(),Scope=scope.Trim(),Objectives=objectives.Trim(),Criteria=criteria.Trim(),AuditeeDepartment=auditee.Trim(),LeadAuditorUserId=auditorId,LeadAuditor=auditor.Trim(),LeadAuditorDepartment=auditorDepartment.Trim(),PlannedStartUtc=start,PlannedEndUtc=end,IsUnplanned=unplanned,UnplannedReason=unplanned?reason!.Trim():null,ChecklistVersion=checklistVersion.Trim(),Status=InternalAuditStatus.AnnualPlan,CreatedAtUtc=now,UpdatedAtUtc=now,Version=1};var i=1;foreach(var item in q)a._checklist.Add(AuditChecklistItem.Create(a.Id,i++,item.Question,item.Reference));return a;}
    public void Transition(long version,string code,string? note,DateTimeOffset now){EnsureVersion(version);switch(code.Trim().ToLowerInvariant()){case"prepare":Ensure(InternalAuditStatus.AnnualPlan);Move(InternalAuditStatus.Preparation,now);break;case"submit-plan":Ensure(InternalAuditStatus.Preparation);if(LeadAuditorDepartment.Equals(AuditeeDepartment,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Baş denetçi denetlenen bölümden bağımsız olmalıdır.");IndependenceConfirmed=true;Move(InternalAuditStatus.PlanApproval,now);break;case"approve-plan":Ensure(InternalAuditStatus.PlanApproval);ChecklistLockedAtUtc=now;Move(InternalAuditStatus.Execution,now);break;case"complete-execution":Ensure(InternalAuditStatus.Execution);if(_checklist.Any(x=>x.Status==AuditAnswerStatus.Pending))throw new InvalidOperationException("Tüm soru listesi maddeleri cevaplanmadan uygulama tamamlanamaz.");Move(InternalAuditStatus.Findings,now);break;case"confirm-findings":Ensure(InternalAuditStatus.Findings);Move(InternalAuditStatus.ResponseAction,now);break;case"complete-responses":Ensure(InternalAuditStatus.ResponseAction);if(_findings.Any(x=>x.Status==AuditFindingStatus.Open))throw new InvalidOperationException("Tüm bulguların bölüm yanıtı olmadan doğrulamaya geçilemez.");Move(InternalAuditStatus.CapaVerification,now);break;case"start-finding-closure":Ensure(InternalAuditStatus.CapaVerification);Move(InternalAuditStatus.FindingClosure,now);break;case"request-audit-closure":Ensure(InternalAuditStatus.FindingClosure);if(_findings.Any(x=>x.Status!=AuditFindingStatus.Closed))throw new InvalidOperationException("Tüm bulgular kapanmadan denetim kapanışa gönderilemez.");Move(InternalAuditStatus.AuditClosure,now);break;case"close":Ensure(InternalAuditStatus.AuditClosure);Text(note??"",nameof(note),3000);Summary=note!.Trim();ClosedAtUtc=now;Move(InternalAuditStatus.Closed,now);break;default:throw new ArgumentException("Bilinmeyen iç denetim geçişi.");}}
    public void Answer(long version,Guid itemId,AuditAnswerStatus status,string evidence,string note,DateTimeOffset now){EnsureVersion(version);Ensure(InternalAuditStatus.Execution);(_checklist.SingleOrDefault(x=>x.Id==itemId)??throw new ArgumentException("Soru bulunamadı.")).Answer(status,evidence,note,now);Touch(now);}
    public void AddFinding(long version,AuditFinding finding,DateTimeOffset now){EnsureVersion(version);if(Status is not(InternalAuditStatus.Execution or InternalAuditStatus.Findings))throw new InvalidOperationException("Bulgu yalnız denetim uygulaması veya bulgular aşamasında açılabilir.");_findings.Add(finding);Touch(now);}
    public void RespondFinding(long version,Guid findingId,string response,string action,DateTimeOffset now){EnsureVersion(version);if(Status!=InternalAuditStatus.ResponseAction)throw new InvalidOperationException("Bulgu yanıtı yalnız cevap/aksiyon aşamasında girilebilir.");(_findings.SingleOrDefault(x=>x.Id==findingId)??throw new ArgumentException("Bulgu bulunamadı.")).Respond(response,action,now);Touch(now);}
    public void CloseFinding(long version,Guid findingId,string note,bool linkedCapaClosed,DateTimeOffset now){EnsureVersion(version);if(Status is not(InternalAuditStatus.CapaVerification or InternalAuditStatus.FindingClosure))throw new InvalidOperationException("Bulgu bu aşamada kapatılamaz.");(_findings.SingleOrDefault(x=>x.Id==findingId)??throw new ArgumentException("Bulgu bulunamadı.")).Close(note,linkedCapaClosed,now);Touch(now);}
    public void RegisterFindingChange(long version,DateTimeOffset now){EnsureVersion(version);Touch(now);}private void EnsureVersion(long v){if(Version!=v)throw new InvalidOperationException("Denetim başka bir kullanıcı tarafından değiştirilmiş. Ekranı yenileyin.");}private void Ensure(InternalAuditStatus s){if(Status!=s)throw new InvalidOperationException($"Geçersiz denetim aşaması. Beklenen: {s}, mevcut: {Status}.");}private void Move(InternalAuditStatus s,DateTimeOffset n){Status=s;Touch(n);}private void Touch(DateTimeOffset n){UpdatedAtUtc=n;Version++;}private static void Text(string v,string n,int m){if(string.IsNullOrWhiteSpace(v)||v.Trim().Length>m)throw new ArgumentException($"{n} zorunludur ve en fazla {m} karakter olabilir.");}
}
