namespace Qms.Domain.RiskManagement;
public enum RiskAssessmentStatus{Draft,Scoring,ActionPlan,ResidualReview,Approved,Closed}
public enum RiskItemStatus{Open,ActionRequired,ActionCompleted,Accepted}
public sealed class RiskAssessment
{
 private readonly List<RiskItem> _items=[];private RiskAssessment(){}
 public Guid Id{get;private set;}public Guid QualityRecordId{get;private set;}public string Process{get;private set;}="";public string Scope{get;private set;}="";public string Category{get;private set;}="";public string Methodology{get;private set;}="";public string MatrixVersion{get;private set;}="";public int ActionThreshold{get;private set;}public Guid OwnerUserId{get;private set;}public string Owner{get;private set;}="";public Guid? OwnerDepartmentId{get;private set;}public string? OwnerDepartment{get;private set;}public Guid ApproverUserId{get;private set;}public string Approver{get;private set;}="";public RiskAssessmentStatus Status{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public DateTimeOffset UpdatedAtUtc{get;private set;}public DateTimeOffset? ClosedAtUtc{get;private set;}public long Version{get;private set;}public IReadOnlyCollection<RiskItem> Items=>_items;
 public static RiskAssessment Create(Guid qr,string process,string scope,string category,string methodology,string matrixVersion,int threshold,Guid ownerId,string owner,Guid? deptId,string? dept,Guid approverId,string approver,DateTimeOffset now){Text(process,240);Text(scope,6000);Text(category,80);Text(methodology,80);Text(matrixVersion,80);Text(owner,200);Text(approver,200);if(qr==Guid.Empty||ownerId==Guid.Empty||approverId==Guid.Empty||threshold is<1 or>125)throw new ArgumentException("Risk kaydı kimlikleri veya eşik değeri geçersizdir.");return new(){Id=Guid.CreateVersion7(),QualityRecordId=qr,Process=process.Trim(),Scope=scope.Trim(),Category=category.Trim(),Methodology=methodology.Trim(),MatrixVersion=matrixVersion.Trim(),ActionThreshold=threshold,OwnerUserId=ownerId,Owner=owner.Trim(),OwnerDepartmentId=deptId,OwnerDepartment=dept?.Trim(),ApproverUserId=approverId,Approver=approver.Trim(),Status=RiskAssessmentStatus.Draft,CreatedAtUtc=now,UpdatedAtUtc=now,Version=1};}
 public void AddItem(long v,RiskItem item,DateTimeOffset now){EnsureVersion(v);if(Status is not(RiskAssessmentStatus.Draft or RiskAssessmentStatus.Scoring))throw new InvalidOperationException("Bu aşamada risk satırı eklenemez.");_items.Add(item);Touch(now);}
 public void StartScoring(long v,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.Draft);if(_items.Count==0)throw new InvalidOperationException("En az bir risk satırı gereklidir.");Move(RiskAssessmentStatus.Scoring,now);}
 public void CompleteScoring(long v,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.Scoring);if(_items.Any(x=>x.InitialRpn>=ActionThreshold&&string.IsNullOrWhiteSpace(x.Action)))throw new InvalidOperationException("Eşik üzerindeki tüm riskler için aksiyon planı zorunludur.");Move(RiskAssessmentStatus.ActionPlan,now);}
 public void CompleteAction(long v,Guid itemId,string evidence,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.ActionPlan);_items.Single(x=>x.Id==itemId).CompleteAction(evidence,now);Touch(now);}
 public void StartResidualReview(long v,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.ActionPlan);if(_items.Any(x=>x.InitialRpn>=ActionThreshold&&x.Status!=RiskItemStatus.ActionCompleted))throw new InvalidOperationException("Zorunlu aksiyonlar tamamlanmadan kalıntı risk değerlendirmesine geçilemez.");Move(RiskAssessmentStatus.ResidualReview,now);}
 public void SetResidual(long v,Guid itemId,int s,int o,int d,string rationale,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.ResidualReview);_items.Single(x=>x.Id==itemId).SetResidual(s,o,d,rationale,ActionThreshold,now);Touch(now);}
 public void Approve(long v,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.ResidualReview);if(_items.Any(x=>!x.ResidualRpn.HasValue||x.Status!=RiskItemStatus.Accepted))throw new InvalidOperationException("Tüm kalıntı riskler değerlendirilip kabul edilmelidir.");Move(RiskAssessmentStatus.Approved,now);}
 public void Close(long v,DateTimeOffset now){Ensure(v,RiskAssessmentStatus.Approved);ClosedAtUtc=now;Move(RiskAssessmentStatus.Closed,now);}
 private void Ensure(long v,RiskAssessmentStatus s){EnsureVersion(v);if(Status!=s)throw new InvalidOperationException($"Geçersiz risk aşaması. Beklenen: {s}, mevcut: {Status}.");}private void EnsureVersion(long v){if(Version!=v)throw new InvalidOperationException("Risk kaydı değişti; ekranı yenileyin.");}private void Move(RiskAssessmentStatus s,DateTimeOffset n){Status=s;Touch(n);}private void Touch(DateTimeOffset n){UpdatedAtUtc=n;Version++;}private static void Text(string v,int max){if(string.IsNullOrWhiteSpace(v)||v.Trim().Length>max)throw new ArgumentException("Risk metni zorunludur veya uzunluk sınırını aşmıştır.");}
}
public sealed class RiskItem
{
 private RiskItem(){}public Guid Id{get;private set;}public Guid RiskAssessmentId{get;private set;}public string FailureMode{get;private set;}="";public string Effect{get;private set;}="";public string Cause{get;private set;}="";public string ExistingControls{get;private set;}="";public int Severity{get;private set;}public int Occurrence{get;private set;}public int Detectability{get;private set;}public int InitialRpn=>Severity*Occurrence*Detectability;public string? Action{get;private set;}public Guid? ActionOwnerUserId{get;private set;}public string? ActionOwner{get;private set;}public DateTimeOffset? ActionDueAtUtc{get;private set;}public string? ActionEvidence{get;private set;}public int? ResidualSeverity{get;private set;}public int? ResidualOccurrence{get;private set;}public int? ResidualDetectability{get;private set;}public int? ResidualRpn=>ResidualSeverity*ResidualOccurrence*ResidualDetectability;public string? ResidualRationale{get;private set;}public RiskItemStatus Status{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public DateTimeOffset? CompletedAtUtc{get;private set;}
 public static RiskItem Create(Guid assessmentId,string mode,string effect,string cause,string controls,int s,int o,int d,string? action,Guid? actionOwnerId,string? actionOwner,DateTimeOffset? due,int threshold,DateTimeOffset now){Text(mode);Text(effect);Text(cause);Text(controls);Score(s);Score(o);Score(d);var required=s*o*d>=threshold;if(required&&(string.IsNullOrWhiteSpace(action)||!actionOwnerId.HasValue||!due.HasValue||due<=now))throw new ArgumentException("Eşik üzerindeki risk için aksiyon, gerçek sorumlu ve ileri hedef tarih zorunludur.");return new(){Id=Guid.CreateVersion7(),RiskAssessmentId=assessmentId,FailureMode=mode.Trim(),Effect=effect.Trim(),Cause=cause.Trim(),ExistingControls=controls.Trim(),Severity=s,Occurrence=o,Detectability=d,Action=Clean(action),ActionOwnerUserId=actionOwnerId,ActionOwner=Clean(actionOwner),ActionDueAtUtc=due,Status=required?RiskItemStatus.ActionRequired:RiskItemStatus.Open,CreatedAtUtc=now};}
 public void CompleteAction(string evidence,DateTimeOffset now){if(Status!=RiskItemStatus.ActionRequired)throw new InvalidOperationException("Bu risk satırı aksiyon tamamlamaya açık değildir.");Text(evidence);ActionEvidence=evidence.Trim();CompletedAtUtc=now;Status=RiskItemStatus.ActionCompleted;}
 public void SetResidual(int s,int o,int d,string rationale,int threshold,DateTimeOffset now){Score(s);Score(o);Score(d);Text(rationale);if(s*o*d>=threshold)throw new InvalidOperationException("Kalıntı risk eşik altında olmadan kabul edilemez; ek kontrol planlayın.");ResidualSeverity=s;ResidualOccurrence=o;ResidualDetectability=d;ResidualRationale=rationale.Trim();Status=RiskItemStatus.Accepted;CompletedAtUtc??=now;}
 private static void Score(int v){if(v is<1 or>5)throw new ArgumentException("FMEA puanları 1-5 arasında olmalıdır.");}private static void Text(string v){if(string.IsNullOrWhiteSpace(v)||v.Trim().Length>6000)throw new ArgumentException("Risk satırı metni zorunludur.");}private static string? Clean(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();
}
