namespace Qms.Domain.ExternalAudits;

public enum ExternalAuditStatus { Notified, Preparation, AuditInProgress, Findings, ResponsePlan, CapaAction, ClosureLetter, AuthorityClosure, Closed, Cancelled }
public enum ExternalAuditDocumentStatus { Requested, Exported }
public enum ExternalAuditFindingClassification { Critical, Major, Minor, Observation }
public enum ExternalAuditFindingStatus { Open, ResponseSubmitted, Closed }

public sealed class ExternalAuditDocumentRequest
{
    private ExternalAuditDocumentRequest() { }
    public Guid Id { get; private set; } public Guid ExternalAuditId { get; private set; } public Guid? ControlledDocumentId { get; private set; } public string DocumentCode { get; private set; } = ""; public string Title { get; private set; } = ""; public string Confidentiality { get; private set; } = ""; public ExternalAuditDocumentStatus Status { get; private set; } public int ExportVersion { get; private set; } public DateTimeOffset? ExportedAtUtc { get; private set; }
    internal static ExternalAuditDocumentRequest Create(Guid auditId, Guid? documentId, string code, string title, string confidentiality) { Text(code, nameof(code), 120); Text(title, nameof(title), 300); Text(confidentiality, nameof(confidentiality), 80); return new() { Id = Guid.CreateVersion7(), ExternalAuditId = auditId, ControlledDocumentId = documentId, DocumentCode = code.Trim(), Title = title.Trim(), Confidentiality = confidentiality.Trim(), Status = ExternalAuditDocumentStatus.Requested }; }
    internal void Export(DateTimeOffset now) { if (Status == ExternalAuditDocumentStatus.Exported) throw new InvalidOperationException("Doküman talebi daha önce kontrollü dışa aktarılmıştır."); Status = ExternalAuditDocumentStatus.Exported; ExportVersion++; ExportedAtUtc = now; }
    private static void Text(string value, string name, int max) { if (string.IsNullOrWhiteSpace(value) || value.Trim().Length > max) throw new ArgumentException($"{name} zorunludur ve en fazla {max} karakter olabilir."); }
}

public sealed class ExternalAuditPackageAccess
{
    private ExternalAuditPackageAccess() { }
    public Guid Id { get; private set; } public Guid ExternalAuditId { get; private set; } public Guid DocumentRequestId { get; private set; } public Guid ExportedByUserId { get; private set; } public string ExportedBy { get; private set; } = ""; public string Recipient { get; private set; } = ""; public string Purpose { get; private set; } = ""; public string Evidence { get; private set; } = ""; public int ExportVersion { get; private set; } public DateTimeOffset AccessedAtUtc { get; private set; }
    internal static ExternalAuditPackageAccess Create(Guid auditId, Guid requestId, Guid userId, string actor, string recipient, string purpose, string evidence, int version, DateTimeOffset now) { Text(actor, nameof(actor), 200); Text(recipient, nameof(recipient), 300); Text(purpose, nameof(purpose), 1000); Text(evidence, nameof(evidence), 2000); return new() { Id = Guid.CreateVersion7(), ExternalAuditId = auditId, DocumentRequestId = requestId, ExportedByUserId = userId, ExportedBy = actor.Trim(), Recipient = recipient.Trim(), Purpose = purpose.Trim(), Evidence = evidence.Trim(), ExportVersion = version, AccessedAtUtc = now }; }
    private static void Text(string value, string name, int max) { if (string.IsNullOrWhiteSpace(value) || value.Trim().Length > max) throw new ArgumentException($"{name} zorunludur ve en fazla {max} karakter olabilir."); }
}

public sealed class ExternalAuditFinding
{
    private ExternalAuditFinding() { }
    public Guid Id { get; private set; } public Guid ExternalAuditId { get; private set; } public Guid OwnerUserId { get; private set; } public string Number { get; private set; } = ""; public string Title { get; private set; } = ""; public string Description { get; private set; } = ""; public string OfficialReference { get; private set; } = ""; public ExternalAuditFindingClassification Classification { get; private set; } public bool CapaRequired { get; private set; } public Guid? LinkedCapaId { get; private set; } public string Owner { get; private set; } = ""; public DateTimeOffset ResponseDueAtUtc { get; private set; } public string? OfficialResponse { get; private set; } public string? Commitment { get; private set; } public DateTimeOffset? CommitmentDueAtUtc { get; private set; } public string? VerificationNote { get; private set; } public ExternalAuditFindingStatus Status { get; private set; } public DateTimeOffset CreatedAtUtc { get; private set; } public DateTimeOffset? ClosedAtUtc { get; private set; }
    public static ExternalAuditFinding Create(Guid auditId, string number, string title, string description, string reference, ExternalAuditFindingClassification classification, bool capaRequired, Guid? capaId, string owner, DateTimeOffset responseDue, DateTimeOffset now) { Text(number, nameof(number), 80); Text(title, nameof(title), 240); Text(description, nameof(description), 5000); Text(reference, nameof(reference), 500); Text(owner, nameof(owner), 200); if (classification is ExternalAuditFindingClassification.Critical or ExternalAuditFindingClassification.Major) capaRequired = true; if (capaRequired && !capaId.HasValue) throw new InvalidOperationException("DÖF gerekli dış denetim bulgusu ilişkili M.02 kaydı olmadan oluşturulamaz."); return new() { Id = Guid.CreateVersion7(), ExternalAuditId = auditId, Number = number.Trim(), Title = title.Trim(), Description = description.Trim(), OfficialReference = reference.Trim(), Classification = classification, CapaRequired = capaRequired, LinkedCapaId = capaId, Owner = owner.Trim(), ResponseDueAtUtc = responseDue, Status = ExternalAuditFindingStatus.Open, CreatedAtUtc = now }; }
    public void AssignOwnerIdentity(Guid ownerUserId) { if (ownerUserId == Guid.Empty) throw new ArgumentException("Bulgu sorumlusu kimliği zorunludur."); OwnerUserId = ownerUserId; }
    internal void Respond(string response, string commitment, DateTimeOffset commitmentDue, DateTimeOffset now) { Text(response, nameof(response), 8000); Text(commitment, nameof(commitment), 5000); if (commitmentDue <= now) throw new ArgumentException("Taahhüt hedef tarihi gelecekte olmalıdır."); OfficialResponse = response.Trim(); Commitment = commitment.Trim(); CommitmentDueAtUtc = commitmentDue; Status = ExternalAuditFindingStatus.ResponseSubmitted; }
    internal void Close(string note, bool linkedCapaClosed, DateTimeOffset now) { Text(note, nameof(note), 3000); if (Status != ExternalAuditFindingStatus.ResponseSubmitted) throw new InvalidOperationException("Resmi cevabı olmayan bulgu kapatılamaz."); if (CapaRequired && !linkedCapaClosed) throw new InvalidOperationException("İlişkili DÖF kapanmadan dış denetim bulgusu kapatılamaz."); VerificationNote = note.Trim(); Status = ExternalAuditFindingStatus.Closed; ClosedAtUtc = now; }
    private static void Text(string value, string name, int max) { if (string.IsNullOrWhiteSpace(value) || value.Trim().Length > max) throw new ArgumentException($"{name} zorunludur ve en fazla {max} karakter olabilir."); }
}

public sealed class ExternalAudit
{
    private readonly List<ExternalAuditDocumentRequest> _documentRequests = []; private readonly List<ExternalAuditFinding> _findings = []; private ExternalAudit() { }
    public Guid Id { get; private set; } public Guid QualityRecordId { get; private set; } public Guid OwnerUserId { get; private set; } public string Title { get; private set; } = ""; public string AuditKind { get; private set; } = ""; public string AuditorOrganization { get; private set; } = ""; public bool IsGovernmentAuthority { get; private set; } public string AuthorityCountry { get; private set; } = ""; public string OfficialReference { get; private set; } = ""; public string Scope { get; private set; } = ""; public string Site { get; private set; } = ""; public string Owner { get; private set; } = ""; public DateTimeOffset NotifiedAtUtc { get; private set; } public DateTimeOffset PlannedStartUtc { get; private set; } public DateTimeOffset PlannedEndUtc { get; private set; } public DateTimeOffset ResponseDueAtUtc { get; private set; } public Guid? AuthorizedCloserUserId { get; private set; } public string? AuthorizedCloser { get; private set; } public string? ClosureLetterReference { get; private set; } public string? ClosureEvidence { get; private set; } public bool? AuthorityAccepted { get; private set; } public DateTimeOffset? ClosureLetterReceivedAtUtc { get; private set; } public string? ClosureNote { get; private set; } public ExternalAuditStatus Status { get; private set; } public DateTimeOffset CreatedAtUtc { get; private set; } public DateTimeOffset UpdatedAtUtc { get; private set; } public DateTimeOffset? ClosedAtUtc { get; private set; } public long Version { get; private set; } public IReadOnlyCollection<ExternalAuditDocumentRequest> DocumentRequests => _documentRequests; public IReadOnlyCollection<ExternalAuditFinding> Findings => _findings;
    public static ExternalAudit Create(Guid qualityRecordId, string title, string kind, string organization, bool government, string country, string officialReference, string scope, string site, string owner, DateTimeOffset notified, DateTimeOffset start, DateTimeOffset end, DateTimeOffset responseDue, Guid? closerId, string? closer, IEnumerable<(Guid? DocumentId, string Code, string Title, string Confidentiality)> documents, DateTimeOffset now) { if (qualityRecordId == Guid.Empty) throw new ArgumentException("Kalite kaydı zorunludur."); foreach (var (v, n, m) in new[] { (title, nameof(title), 240), (kind, nameof(kind), 100), (organization, nameof(organization), 240), (country, nameof(country), 100), (officialReference, nameof(officialReference), 200), (scope, nameof(scope), 4000), (site, nameof(site), 200), (owner, nameof(owner), 200) }) Text(v, n, m); if (end <= start || responseDue <= notified) throw new ArgumentException("Denetim ve cevap tarih sırası geçersizdir."); if (government && (!closerId.HasValue || string.IsNullOrWhiteSpace(closer))) throw new ArgumentException("Devlet kurumu denetiminde Mesul Müdür/atanmış kapanış yetkilisi zorunludur."); var package = documents.ToArray(); if (package.Length == 0) throw new ArgumentException("Denetim talep paketinde en az bir doküman bulunmalıdır."); var audit = new ExternalAudit { Id = Guid.CreateVersion7(), QualityRecordId = qualityRecordId, Title = title.Trim(), AuditKind = kind.Trim(), AuditorOrganization = organization.Trim(), IsGovernmentAuthority = government, AuthorityCountry = country.Trim(), OfficialReference = officialReference.Trim(), Scope = scope.Trim(), Site = site.Trim(), Owner = owner.Trim(), NotifiedAtUtc = notified, PlannedStartUtc = start, PlannedEndUtc = end, ResponseDueAtUtc = responseDue, AuthorizedCloserUserId = closerId, AuthorizedCloser = string.IsNullOrWhiteSpace(closer) ? null : closer.Trim(), Status = ExternalAuditStatus.Notified, CreatedAtUtc = now, UpdatedAtUtc = now, Version = 1 }; foreach (var item in package) audit._documentRequests.Add(ExternalAuditDocumentRequest.Create(audit.Id, item.DocumentId, item.Code, item.Title, item.Confidentiality)); return audit; }
    public void AssignOwnerIdentity(Guid ownerUserId) { if (ownerUserId == Guid.Empty) throw new ArgumentException("Dış denetim sorumlusu kimliği zorunludur."); OwnerUserId = ownerUserId; }
    public ExternalAuditPackageAccess ExportDocument(long version, Guid requestId, Guid userId, string actor, string recipient, string purpose, string evidence, DateTimeOffset now) { EnsureVersion(version); Ensure(ExternalAuditStatus.Preparation); var item = _documentRequests.SingleOrDefault(x => x.Id == requestId) ?? throw new ArgumentException("Doküman talebi bulunamadı."); item.Export(now); var access = ExternalAuditPackageAccess.Create(Id, item.Id, userId, actor, recipient, purpose, evidence, item.ExportVersion, now); Touch(now); return access; }
    public void AddFinding(long version, ExternalAuditFinding finding, DateTimeOffset now) { EnsureVersion(version); if (Status is not (ExternalAuditStatus.AuditInProgress or ExternalAuditStatus.Findings)) throw new InvalidOperationException("Bulgu yalnız dış denetim veya bulgular aşamasında açılabilir."); _findings.Add(finding); Touch(now); }
    public void RespondFinding(long version, Guid findingId, string response, string commitment, DateTimeOffset due, DateTimeOffset now) { EnsureVersion(version); Ensure(ExternalAuditStatus.ResponsePlan); (_findings.SingleOrDefault(x => x.Id == findingId) ?? throw new ArgumentException("Bulgu bulunamadı.")).Respond(response, commitment, due, now); Touch(now); }
    public void CloseFinding(long version, Guid findingId, string note, bool capaClosed, DateTimeOffset now) { EnsureVersion(version); Ensure(ExternalAuditStatus.CapaAction); (_findings.SingleOrDefault(x => x.Id == findingId) ?? throw new ArgumentException("Bulgu bulunamadı.")).Close(note, capaClosed, now); Touch(now); }
    public void RecordClosureLetter(long version, string reference, DateTimeOffset receivedAt, string evidence, bool accepted, DateTimeOffset now) { EnsureVersion(version); Ensure(ExternalAuditStatus.ClosureLetter); Text(reference, nameof(reference), 300); Text(evidence, nameof(evidence), 4000); if (receivedAt > now) throw new ArgumentException("Kapanış mektubu tarihi gelecekte olamaz."); ClosureLetterReference = reference.Trim(); ClosureEvidence = evidence.Trim(); AuthorityAccepted = accepted; ClosureLetterReceivedAtUtc = receivedAt; Touch(now); }
    public void Transition(long version, string code, string? note, DateTimeOffset now) { EnsureVersion(version); switch (code.Trim().ToLowerInvariant()) { case "start-preparation": Ensure(ExternalAuditStatus.Notified); Move(ExternalAuditStatus.Preparation, now); break; case "start-audit": Ensure(ExternalAuditStatus.Preparation); if (_documentRequests.Any(x => x.Status != ExternalAuditDocumentStatus.Exported)) throw new InvalidOperationException("Talep paketindeki tüm dokümanlar kontrollü dışa aktarılmadan denetim başlatılamaz."); Move(ExternalAuditStatus.AuditInProgress, now); break; case "complete-audit": Ensure(ExternalAuditStatus.AuditInProgress); Move(ExternalAuditStatus.Findings, now); break; case "open-response-plan": Ensure(ExternalAuditStatus.Findings); Move(ExternalAuditStatus.ResponsePlan, now); break; case "start-capa-actions": Ensure(ExternalAuditStatus.ResponsePlan); if (_findings.Any(x => x.Status == ExternalAuditFindingStatus.Open)) throw new InvalidOperationException("Tüm bulguların resmi cevabı ve taahhüdü kaydedilmeden DÖF/aksiyon aşamasına geçilemez."); Move(ExternalAuditStatus.CapaAction, now); break; case "complete-capa-actions": Ensure(ExternalAuditStatus.CapaAction); if (_findings.Any(x => x.Status != ExternalAuditFindingStatus.Closed)) throw new InvalidOperationException("Tüm bulgular kapanmadan kapanış mektubu aşamasına geçilemez."); Move(ExternalAuditStatus.ClosureLetter, now); break; case "submit-authority-closure": Ensure(ExternalAuditStatus.ClosureLetter); if (string.IsNullOrWhiteSpace(ClosureLetterReference) || string.IsNullOrWhiteSpace(ClosureEvidence) || AuthorityAccepted != true) throw new InvalidOperationException("Kapanış mektubu veya otorite/müşteri kabul kanıtı eksiktir."); Move(ExternalAuditStatus.AuthorityClosure, now); break; case "close": Ensure(ExternalAuditStatus.AuthorityClosure); Text(note ?? "", nameof(note), 3000); ClosureNote = note!.Trim(); ClosedAtUtc = now; Move(ExternalAuditStatus.Closed, now); break; default: throw new ArgumentException("Bilinmeyen dış denetim geçişi."); } }
    private void EnsureVersion(long version) { if (Version != version) throw new InvalidOperationException("Dış denetim başka bir kullanıcı tarafından değiştirilmiş. Ekranı yenileyin."); } private void Ensure(ExternalAuditStatus status) { if (Status != status) throw new InvalidOperationException($"Geçersiz dış denetim aşaması. Beklenen: {status}, mevcut: {Status}."); } private void Move(ExternalAuditStatus status, DateTimeOffset now) { Status = status; Touch(now); } private void Touch(DateTimeOffset now) { UpdatedAtUtc = now; Version++; } private static void Text(string value, string name, int max) { if (string.IsNullOrWhiteSpace(value) || value.Trim().Length > max) throw new ArgumentException($"{name} zorunludur ve en fazla {max} karakter olabilir."); }
}
